### ISSUE TITLE
Missing open codecs in AppImage

### ISSUE THREAD

**Issue by daleglass** [vircadia/vircadia#1005]
The AppImage build fails to play the steams on fosdem.org:

![vircadia-snap-by-dale_glass-on-2021-02-06_19-41-52](https://user-images.githubusercontent.com/51060919/107126998-8a150480-68b3-11eb-9435-441222ccc8df.jpg)

I built against system Qt on Fedora 33 with PR #936, and it works on that:

![vircadia-snap-by--on-2021-02-06_19-39-47](https://user-images.githubusercontent.com/51060919/107126992-7f5a6f80-68b3-11eb-877f-b8970e51639e.jpg)

Some codec is missing, and given that FOSDEM are big on openness it has to be an open one.

**Comment by Zakor** [comment]
The stream at https://stream.fosdem.org/drtc.m3u8 uses the H264 codec. 
You can check for yourself loading the network stream in VLC and pressing Ctrl+J to open the Codec Information window.

**Comment by daleglass** [comment]
Hm, for some reason I thought FOSDEM would be using WebM. Well, not a bug then I suppose.
