### ISSUE TITLE
Create AudioConstants.h

### ISSUE THREAD

**Issue by digisomni** [vircadia/vircadia#1010]
There are some small things such as defaults that should probably be shared between some files (e.g. Audio.h and AudioClient.h)

**Comment by digisomni** [comment]
Still a thing. :)

**Comment by daleglass** [comment]
`./libraries/audio/src/AudioConstants.h` exists

**Comment by digisomni** [comment]
This file apparently does exist but there are audio files that have constants shared across them that do not use this, can't remember off the top of my head which ones those were so closing this for now. It was probably related to the files modified in this PR: https://github.com/vircadia/vircadia/pull/1007
