### ISSUE TITLE
Missing community and Android support

### ISSUE THREAD

**Issue by leolux** [vircadia/vircadia#1011]
Vircadia should create a free and open world. Where to find the community? Is there any forum or messaging service or is github the only place to discuss ideas?

Does the project support Android or WebXR? Please have in mind that WebXR is the first standard that creates interoperability accross platforms and manufacturers.

**Comment by digisomni** [comment]
Hey there! We have lots of things in the works. Android for example is supported by the codebase but still needs some maintainers to take it full force and get it tested and deployed again.

We hang out on Discord (I know) for the time being. https://discordapp.com/invite/Pvx2vke

**Comment by JulianGro** [comment]
Main reason why don't have anything other than GitHub, Discord and the community meetings is that we just don't have enough users to justify that. Personally I have been interested in a forum. The main messaging service will likely change depending on what gets implemented into the metaverse in the end.

Also on another note Discord can be used in browser without an account. So people can come in and search for answers, ask questions or discuss without getting too involved in the proprietary platform.
