### ISSUE TITLE
Vircadia Builder fails to complete

### ISSUE THREAD

**Issue by Steve-Pruneau** [vircadia/vircadia#1037]
I am running Vircadia Builder in an AWS Linux 2 instance. 16 cores and 32gb of RAM (c5a.4xlarge).

Thus far, Vircadia Builder has thrown a fatal error related to CMake at line 504:

actual value
`run("cmake", "../source")`

value needed
`run("cmake3", "../source")`

And also, a fatal error related to CMake at line 91:

```
CMake Error at CMakeLists.txt:91 (message):
  vcpkg configuration missing.
```

**Comment by Steve-Pruneau** [comment]
The attached text file shows Vircadia Builder steps that I am following.

[Vircadia_Builder_steps.txt](https://github.com/vircadia/vircadia/files/5976491/Vircadia_Builder_steps.txt)

**Comment by JulianGro** [comment]
@Steve-Pruneau please test https://github.com/daleglass/vircadia-builder/pull/43 when you get a chance. ( https://github.com/JulianGro/vircadia-builder/tree/amznlin2 )

**Comment by daleglass** [comment]
Please test the latest https://github.com/daleglass/vircadia-builder 

There's a new script called `install_amazon_linux_deps.sh` that should be run first, and should hopefully take care of all the issues, including #1038

**Comment by Steve-Pruneau** [comment]
Thanks Dale!  I just now ran the test. Results attached.

Fatal error:
Command 'rpm -qa --qf %{NAME}\n' exited with value 1

![vircadia-builder_test_1_2021-02-14](https://user-images.githubusercontent.com/74510038/107888498-69efd180-6ec1-11eb-9d93-86ff8063dfc1.jpg)
[vircadia-builder_test_1_2021-02-14.txt](https://github.com/vircadia/vircadia/files/5978471/vircadia-builder_test_1_2021-02-14.txt)

**Comment by daleglass** [comment]
Hmm, that's odd. I think you probably have some sort of auto-update service running on the background and keeping the package database busy. Please wait a few minutes and try again.

**Comment by Steve-Pruneau** [comment]
Vircadia Builder test 2

```
Fatal error:
Command 'cmake3 ../source' exited with value 1
```

![vircadia-builder_test_2_2021-02-14](https://user-images.githubusercontent.com/74510038/107892326-3751d300-6ed9-11eb-8cfa-966a536333ad.jpg)

[vircadia-builder_test_2_2021-02-14.txt](https://github.com/vircadia/vircadia/files/5978729/vircadia-builder_test_2_2021-02-14.txt)

**Comment by JulianGro** [comment]
That's an easy one. It says that your server is full.

**Comment by Steve-Pruneau** [comment]
> That's an easy one. It says that your server is full.

OK. I will terminate the machine and make a bigger one. I would rather terminate it than increase the disk that I have.

**Comment by Steve-Pruneau** [comment]
Build was successful.

![vircadia-builder_test_3_build-success_2021-02-14](https://user-images.githubusercontent.com/74510038/107903908-464b7c00-6eff-11eb-9e83-c3a1eae44b0f.jpg)

**Comment by Steve-Pruneau** [comment]
Package script failed because it is expecting a different file path. There is no "root" folder. Is a folder named "root" common across all other versions of Linux? The vircadia folder is located here:

/home/vircadia

![vircadia-builder_test_3_package-fail_2021-02-14](https://user-images.githubusercontent.com/74510038/107904020-8a3e8100-6eff-11eb-95af-8a5a8cbeba1c.jpg)

**Comment by digisomni** [comment]
Well, actually... you need RPMBuild.

Try `yum install rpmbuild` or `yum install rpm-build`.

**Comment by Steve-Pruneau** [comment]
That seemed to have worked. But it looks like it packaged another version and not what was just built.

`Wrote: /root/rpmbuild/RPMS/x86_64/vircadia-server-2020.2.0_ASTERIA_20210213_26894b4-1.amzn2.x86_64.rpm`

In any case, where does the package file get written?

![vircadia-builder_test_3_package-success_2021-02-14](https://user-images.githubusercontent.com/74510038/107905085-8fe99600-6f02-11eb-8e4e-ecf3bafd9753.jpg)

**Comment by Steve-Pruneau** [comment]
If it went into root, access is denied to that folder. I either need to change permissions on root or in future, make it to write files elsewhere.

**Comment by digisomni** [comment]
No, that's correct. Unfortunately it's just got the hardcoded old version in the name there, it should be the correct version when you install it. I just rename the file before uploading it. Try and install that package using `yum localinstall [insert package name and path here]`

You can also run the commands as sudo in order to ensure they have access to the correct folders.

**Comment by JulianGro** [comment]
Closing this as vircadia-builder seems to do it's job fine now.
We should fix up the package scripts some more at some point and add more for more popular distributions, but that is another matter for now.
