### ISSUE TITLE
Vircadia Builder prompts are blank before starting

### ISSUE THREAD

**Issue by Steve-Pruneau** [vircadia/vircadia#1038]
I am running Vircadia Builder in an AWS Linux 2 instance. 16 cores and 32gb of RAM (c5a.4xlarge).

Version of Vircadia Builder in use was obtained from GitHub
sudo git clone https://github.com/vircadia/vircadia-builder.git

When the Vircadia Builder app is started, prompts are blank.
sudo ./vircadia-builder --build server

[PROMPT 1] Git repository             : 
[PROMPT 2] Git tag                    : 
[PROMPT 3] Release type               : 
[PROMPT 4] Release number             : 
[PROMPT 5] Build number               : 
[PROMPT 6] Installation dir           : 
[PROMPT 7] CPU cores to use for Vircadia: 
[PROMPT 8] CPU cores to use for Qt5   :

**Comment by JulianGro** [comment]
This is an easy one `perl-Term-ReadLine-Gnu` is missing as a dependency

**Comment by JulianGro** [comment]
I would make this a wont-fix. Amazon Linux 2 does not have the required package available in their repositories. Building it ourselves without modifying the system is beyond my capabilities and frankly speaking just doesn't seem worth it. Maybe @daleglass has a different option on this and is up for doing something about this.

In the meantime you can install `perl-Term-ReadLine-Gnu` from EPEL 7 if you want the prompts to be properly pre-filled. https://centos.pkgs.org/7/epel-x86_64/perl-Term-ReadLine-Gnu-1.26-2.el7.x86_64.rpm.html

**Comment by JulianGro** [comment]
Closing this as this has apparently been fixed by Dale providing a dependency install script for Amazon Linux 2.
