### ISSUE TITLE
Nametags display broken

### ISSUE THREAD

**Issue by ctrlaltdavid** [vircadia/vircadia#1039]
The display of nametags in click-on-person-to-display-nametag is broken: it doesn't billboard properly to face you. (The display depends on the relative orientation of your and the other person's avatars.)

**Comment by HifiExperiments** [comment]
they need to have their orientation set to 0,0,0.  the behavior of billboarding has changed slightly, so now the rotation of the entity is applied first, allowing you to rotate them to control which axis faces you.  domain content was automatically updated to address this, but scripts will need to be updated to take this into account

**Comment by digisomni** [comment]
Oh, kewlio.

**Comment by digisomni** [comment]
So found a bug in that though... so for avatars, it's taking the orientation of the avatar its parented to and applying that. I don't think we have any real way to handle... that?

**Comment by HifiExperiments** [comment]
ah...fuck...I'll need to think about how to handle that...
