### ISSUE TITLE
Signing and notarizing interface.app on macOS

### ISSUE THREAD

**Issue by yuriymacdev** [vircadia/vircadia#1045]
# Signing and notarizing interface.app on macOS

### Required steps
To make the "This app is from an unidentified developer" warning go away when launching interface.app, before distributing you will need to:

1. Code sign interface.app and all its internal binaries
2. Notarize the signed app
3. Staple it

### Prerequisites
1. You need an Apple developer's account and a dev certificate installed on your Mac. Most likely you will want a company dev account registered under your company name. It costs $99/year.
2. The cert can be installed from the Xcode's preferences panel or manually by generating a signing request via Keychain app and submitting it on your dev account dashboard. You need to download "Developer ID Application" cert.
3. For notarization you will need to generate an app password (it's a different thing from your Apple account password). Sign in with your company apple id at [https://appleid.apple.com](), open Settings->Security, find there "Generate an app password" and save it somewhere on your Mac.

### Signing interface.app
Currently generated bundle has incorrect format. There are two problems:

* Incorrect frameworks packaging
* executables (.app bundles, dylib's and plain binaries) are located in Resources subdirectory, which is designed to contain only static content and scripts

The **first issue** is caused most likely by a deep copying (cp -r) somewhere in your Makefiles.
Any Framework bundle must be structured like so:

```
frameworkname.framework:
  frameworkname(symlink) --> Versions/A/frameworkname
  Resources(symlink) --> Versions/A/Resources
  [anyotherdirs](symlink) --> Versions/A/[anyotherdirs]
  Versions:
     Current(symlink) --> A
     A:
        frameworkname
        Resources
        [anyotherdirs]
  
```

when you deep-copy the frameworks into your bundle you are losing symlinks, creating duplicates. To keep the symlinks on Mac use `cp -a` (or `cp --preserve=links` on Linux).

Alternatively you can manually fix all the frameworks by deleting duplicate files and creating symlinks using `ln -s` (which is what I did).
List of incorrectly bundled frameworks:

* interface.app/Contents/Resources/hifi-screenshare.app/Contents/Frameworks/Electron Framework.framework
* interface.app/Contents/Resources/hifi-screenshare.app/Contents/Frameworks/ReactiveCocoa.framework
* interface.app/Contents/Resources/hifi-screenshare.app/Contents/Frameworks/Mantle.framework
* interface.app/Contents/Resources/hifi-screenshare.app/Contents/Frameworks/Squirrel.framework

**The second issue** is not critical and you don't need to restructure the bundles. 

1. The codesign utility however won't be able to traverse and sign binaries in Resources dirs, so you'll have to do it explicitly:

 `codesign --timestamp --force -o runtime --verbose -s "Developer ID Application" "interface.app/Contents/Resources/hifi-screenshare.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/crashpad_handler"`

`codesign --timestamp --force -o runtime --verbose -s "Developer ID Application" "interface.app/Contents/Resources/hifi-screenshare.app/Contents/Frameworks/Squirrel.framework/Versions/A/Resources/ShipIt"`

2. The same applies to the Libraries dir, it is not a standard designated location for the binary code, and therefore the contents must be signed explicitly:

`for x in interface.app/Contents/Resources/hifi-screenshare.app/Contents/Frameworks/Electron\ Framework.framework/Libraries/*; do codesign --timestamp --force -o runtime --verbose -s "Developer ID Application" $x; done`

3. After this is done, you can deep-sign the outer bundle inside Resources (*deep* meaning it will sign all the Frameworks/libraries inside the bundle as well given they are located in expected dirs):

`codesign --deep --timestamp --force -o runtime --verbose -s "Developer ID Application"  interface.app/Contents/Resources/hifi-screenshare.app`

Now you can sign the interface.app itself. Its code however is using library calls which are not allowed when hardened runtime is enabled (which in turn is mandatory for notarization), and the app will eventually crash on launch. This issue can be overcome by disabling library validation.

To do that, create a file `interface.entitlements` with the contents:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.security.cs.disable-library-validation</key>
	<true/>
</dict>
</plist>
```

and finally codesign the app:

`codesign --timestamp --force -o runtime --verbose --deep -s "Developer ID Application" --entitlements interface.entitlements interface.app`

### Notarization
Once you have a code signed interface.app, zip it using
`ditto -ck --sequesterRsrc --keepParent interface.app interface.zip`

and submit for notarization
`xcrun altool -f myinterface.zip --primary-bundle-id "com.vircadia.interface"  --notarize-app --username "<your company appleid>" --password "<here goes your app password>"`

in a few minutes you will get an email saying whether notarization was successful or not.

Finally, you can staple the .app so it opens for the users who didn't have internet connection:
`xcrun stapler staple interface.app`

Only now you can package the app into a dmg.

Once notarized, the system will not show untrusted warnings *when launched on a new system*, apart from "This software was downloaded from internet. Are you sure you want to open it?"

### Final notes
Apple also recommends signing and notarizing the dmg, although I haven't seen any warnings if I didn't. 

To do that, run
`codesign --timestamp --force -o runtime --verbose -s "Developer ID Application" Vircadia.dmg`

and 

`xcrun altool -f Vircadia.dmg --primary-bundle-id "com.vircadia.dmg  --notarize-app --username "<your company appleid>" --password "<here goes your app password>"`

and eventually staple it:

`xcrun stapler staple Vircadia.dmg`

All of these steps can be scripted and integrated into your CI/CD process.
I recommend following these steps manually first.

**Comment by daleglass** [comment]
Thanks, this is very useful. I only have slight doubts about this part:

> Now you can sign the interface.app itself. Its code however is using library calls which are not allowed when hardened runtime is enabled (which in turn is mandatory for notarization), and the app will eventually crash on launch. This issue can be overcome by disabling library validation.

I'm not a seasoned OSX developer, so I don't know what the implications of this are. Which calls aren't allowed, and what are the effects of disabling library validation?

**Comment by yuriymacdev** [comment]
>I'm not a seasoned OSX developer, so I don't know what the implications of this are. Which calls aren't allowed, and what are the effects of disabling library validation?

mmap() loading of a dylib (libavatar). I didn't go into details of what exactly vircadia code does and why does it do it (could be done by a system framework when a dlopen()/dlsym() are called?).
You can skip this step and see what will happen.

Disabling lib validation makes it possible to inject code into your process by other processes (this is possible to do now too while it's not signed at all).

**Comment by daleglass** [comment]
Thanks, and what are the implications for us here? Only security related? Does Apple care in any way about whether one disables library validation?

**Comment by yuriymacdev** [comment]
> Only security related?
Yes

> Does Apple care in any way about whether one disables library validation?
No

**Comment by ctrlaltdavid** [comment]
I question why the hifi-screenshare.app is in \interface.app\Contents\Resources\ rather than \interface.app\Contents\MacOS\.

**Comment by ctrlaltdavid** [comment]
Dale found the following OSX dev doc on DMG contents: https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html#//apple_ref/doc/uid/10000123i-CH101-SW1

**Comment by ctrlaltdavid** [comment]
The screenshare app is copied to its DMG location in \interface\CMakeLists.txt:
```
    # copy screenshare app to the resource folder
    COMMAND "${CMAKE_COMMAND}" -E copy_directory
      "${CMAKE_CURRENT_BINARY_DIR}/../screenshare/hifi-screenshare-darwin-x64/hifi-screenshare.app"
      "${RESOURCES_DEV_DIR}/hifi-screenshare.app"
```

Instead of `copy_directory`, perhaps `symlink_or_copy_directory_beside_target` should be used?

**Comment by digisomni** [comment]
I believe these changes may be necessary or helpful in the effort:
https://github.com/digisomni/vircadia/commit/25f43945a17c54712698778eb6b6f5308217ee75

Also, here is the list of commands so far that can (maybe) bring us closer to getting a signed app after making a CLIENT_ONLY build.

```bash
find "Vircadia.app" -name "*.framework" | xargs -I $ /usr/bin/codesign --deep --force --verbose --timestamp -o runtime --sign "[insert signing cert ID or name here]" $

find "Vircadia.app/Contents/Frameworks" -name "*.dylib" | xargs -I $ /usr/bin/codesign --force --verbose --timestamp -o runtime --sign "[insert signing cert ID or name here]" $

find "Vircadia.app/Contents/Plugins" -name "*.dylib" | xargs -I $ /usr/bin/codesign --force --verbose --timestamp -o runtime --sign "[insert signing cert ID or name here]" $

/usr/bin/codesign --force --verbose --timestamp -o runtime --sign "[insert signing cert ID or name here]" --entitlements ../../Vircadia.entitlements Vircadia.app

/usr/bin/ditto -ck -rsrc --sequesterRsrc --keepParent Vircadia.app Vircadia.zip

xcrun altool --notarize-app --primary-bundle-id "com.vircadia.interface" --username [insert account email here] --password [insert app password here] --file Vircadia.zip

xcrun stapler staple Vircadia.app
```
