### ISSUE TITLE
When doing a clean install or PR the world looks blurry with automatic texture memory

### ISSUE THREAD

**Issue by Basinsky** [vircadia/vircadia#1048]
I have to set the texture memory to maximum to get a clear view everytime I do a clean install or PR install. I use a RTX 3080 which should default to use max texture memory it seems to take a lower setting for automatic.

**Comment by JulianGro** [comment]
Could you send us a screenshot of the expanded statistics?
Press `/` and click on the statistics to expand them.

**Comment by Basinsky** [comment]
if I delete my interface.json it returns to the automatic setting. Look in the pictures to the floor and see how blurry it is with automatic.
![initial-automatic texture memory](https://user-images.githubusercontent.com/51274563/108626582-219c5a80-7451-11eb-96ac-5d9fbe7ef9cb.PNG)
![initial- max texture memory](https://user-images.githubusercontent.com/51274563/108626583-23661e00-7451-11eb-8f2a-327b74d50c1f.PNG)

**Comment by JulianGro** [comment]
Yeah for some reason it seems to think that you video memory is full. Have you tried restarting Interface? Have you tried letting it run for some time (like 10 minutes or something)?

It seems unlikely that you 10gb of video memory are full, unless you have something like VRChat or multiple Blender instance with lots of high resolution textures running in the background.

Also could you post a log file with the automatic texture memory setting on? I *think* Dale put some logging in that part of the code.

**Comment by Aitolda** [comment]
Checking in with a 2070 super. No issue here.  Wonder if we can narrow it down to the card or family.

**Comment by Aitolda** [comment]
Not sure if it's the same bug exactly but DrFran was unable to see textures on her models she was bringing it. Eventually had her open the max texture option and discovered that nothing was selected, not even automatic (not dot), and switching to 4096 from nothing solved her issues.  She's on a 2080 TI

**Comment by JulianGro** [comment]
> Not sure if it's the same bug exactly but DrFran was unable to see textures on her models she was bringing it. Eventually had her open the max texture option and discovered that nothing was selected, not even automatic (no dot), and switching to 4096 from nothing solved her issues. She's on a 2080 TI

It's not the same. This is downscaling the textures to minimum size. It won't just get rid of textures.

**Comment by daleglass** [comment]
Hi, could you attach a full log to this ticket?

**Comment by ksuprynowicz** [comment]
I have same problem on Windows with RTX 2070. I've attached the log file.
I think it's suspicious that the last line mentioning GPU memory is : 
`[07/04 21:31:56] [DEBUG] [hifi.gpu] New MAX texture memory  0  MB`
[vircadia-log_2021-07-04_21.32.21.txt](https://github.com/vircadia/vircadia/files/6760636/vircadia-log_2021-07-04_21.32.21.txt)
