### ISSUE TITLE
Feature Request: Create - Show missing entities in the entities list.

### ISSUE THREAD

**Issue by Aitolda** [vircadia/vircadia#1051]
Right now the only way to know if a link to an entity is broken is to fly around and hope to spot the green cube.  If there was a column in the entity list that was able to note this it would help with general cleanup.

It's possible this could be expanded later to show missing scripts and such, but you've got to start somewhere.

**Comment by SilverfishVR** [comment]
good idea and related to https://github.com/vircadia/vircadia/issues/121

**Comment by daleglass** [comment]
Dev meeting: PR #1069 fixes this satisfactorily
