### ISSUE TITLE
"Send data to High Fidelity" settings option

### ISSUE THREAD

**Issue by ctrlaltdavid** [vircadia/vircadia#1059]
Down the bottom of Settings > General ...

![image](https://user-images.githubusercontent.com/7455448/108814405-9e793100-7617-11eb-9c66-3cc155078312.png)

Firstly, it shouldn't mention "High Fidelity".
Secondly, perhaps this option should be removed if we're not currently using and unlikely to use the option?

**Comment by JulianGro** [comment]
To be fair, error logging and system details sound useful.
