### ISSUE TITLE
Create app - Tooltips not showing

### ISSUE THREAD

**Issue by Basinsky** [vircadia/vircadia#1060]
On 2021.1.0 Eos the tooltips are not showing when you hover the text (For example on "Description". You used to see the JS entitiy variable, which is handy when you are scripting.

**Comment by AleziaKurdis** [comment]
Clearly the file 
scripts/system/create/assets/data/createAppTooltips.json
failed to be parsed.

That json seems well formated, but fail to parse
The issue with line 590.
![image](https://user-images.githubusercontent.com/60075796/108944799-7db9d700-7629-11eb-8bdc-a296d3ee64ec.png)

It works when I remove that comma.

Here's where the problem started:
![image](https://user-images.githubusercontent.com/60075796/108945743-2c124c00-762b-11eb-961c-2b66e912e858.png)

**Comment by HifiExperiments** [comment]
😅

**Comment by AleziaKurdis** [comment]
You owe me 35 minutes ;-)

**Comment by HifiExperiments** [comment]
@AleziaKurdis 
```
_______________________________
|                             |
|     coupon good for one     |
|        free bug fix or      |
|            feature          |
|                             |
-------------------------------
```
