### ISSUE TITLE
OSX crash on start-up with Qt 5.15.2

### ISSUE THREAD

**Issue by ctrlaltdavid** [vircadia/vircadia#1072]
Happens for some people all the time - EricP, unless configures graphics to use only discrete graphics.
Happens for some people every second time - Steve ... Update, 11 Mar: It's no longer crashing for Steve.
Doesn't happen for some people - Dave K?

Qt 5.15.2 builds are provide in: https://github.com/vircadia/vircadia/pull/938

We need a call stack of the crash.

**Comment by ArcadeFever** [comment]
I was not able to get PR 938 to crash, until I
1. plugged in my second monitor
2. or dragged the window from first monitor over to second monitor

This is a known issue with PR builds, and does not happen in release builds (for what reason I don't know), but this got me thinking.  I started the EOS client, moved the screen to my second monitor and then exited.  I started PR 938, but no crash on startup.  I then started EOS client and made the client maximized on second monitor, then exited.  I then started PR 938 build and it crashed on startup with the following known OSX PR build issue:

Process 98334 stopped
* thread #40, name = 'Presentation Thread', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
    frame #0: 0x00007fff317a609d AppKit`-[NSOpenGLContext update] + 525
AppKit`-[NSOpenGLContext update]:
->  0x7fff317a609d <+525>: ud2    
    0x7fff317a609f <+527>: movq   %rax, %r14
    0x7fff317a60a2 <+530>: jmp    0x7fff317a60ab            ; <+539>
    0x7fff317a60a4 <+532>: movq   %rax, %r14
Target 0: (interface) stopped.
(lldb) bt
* thread #40, name = 'Presentation Thread', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
  * frame #0: 0x00007fff317a609d AppKit`-[NSOpenGLContext update] + 525
    frame #1: 0x00000001162dad3a libqcocoa.dylib`___lldb_unnamed_symbol1147$$libqcocoa.dylib + 298
    frame #2: 0x00000001162da045 libqcocoa.dylib`___lldb_unnamed_symbol1145$$libqcocoa.dylib + 405
    frame #3: 0x000000010cf97dc7 QtGui`QOpenGLContext::makeCurrent(QSurface*) + 167
    frame #4: 0x000000010cd74ba6 libgl.dylib`gl::Context::makeCurrent() + 38
    frame #5: 0x0000000100a0ae5e libdisplay-plugins.dylib`___lldb_unnamed_symbol158$$libdisplay-plugins.dylib + 670
    frame #6: 0x000000010d53ad19 QtCore`___lldb_unnamed_symbol239$$QtCore + 329
    frame #7: 0x00007fff6e42f109 libsystem_pthread.dylib`_pthread_start + 148
    frame #8: 0x00007fff6e42ab8b libsystem_pthread.dylib`thread_start + 15
(lldb) 

If Steve and others that were seeing this startup crash use multiple monitors, and were switching between release builds and PR builds, while running client on second monitor, this could perhaps explain the start up crashes?

**Comment by digisomni** [comment]
What are the specs of the machine you got the crash on?

**Comment by ArcadeFever** [comment]
MacBook Pro (16-inch, 2019)
Processor 2.4 GHz 8-Core Intel Core i9
Memory 16 GB 2667 MHz DDR4
Graphics AMD Radeon Pro 5500M 4 GB
    Intel UHD Graphics 630 1536 MB

**Comment by daleglass** [comment]
Is this still happening?
