### ISSUE TITLE
Update Unity Avatar Exporter - "High Fidelity Projects" -> "Vircadia Projects"

### ISSUE THREAD

**Issue by digisomni** [vircadia/vircadia#1073]
No promise that it still works as it should though.

**Comment by daleglass** [comment]
Fixed by d406b81b47e

**Comment by digisomni** [comment]
Was this confirmed to be fixed in the relevant spot? I could have sworn someone noted this issue this year.

**Comment by digisomni** [comment]
Fixed with https://github.com/vircadia/vircadia/pull/1579.
