### ISSUE TITLE
Building with HIFI_MEMORY_DEBUGGING doesn't work

### ISSUE THREAD

**Issue by daleglass** [vircadia/vircadia#1119]
It builds, but the resulting application doesn't run:

    $ interface/interface
    ==31730==Your application is linked against incompatible ASan runtimes.

This is weird, interface links against the library:

    $ ldd interface/interface | grep -i asan
	libasan.so.6 => /lib64/libasan.so.6 (0x00007f0ada161000)

And nothing seems to link against another one:

```
for lib in `ldd interface/interface | awk '{print $3}'` ; do ldd $lib  |grep -i asan ; done                                  1 
	libasan.so.6 => /lib64/libasan.so.6 (0x00007f42f3de2000)
	libasan.so.6 => /lib64/libasan.so.6 (0x00007f2256f2d000)
	libasan.so.6 => /lib64/libasan.so.6 (0x00007f10a4e12000)
	libasan.so.6 => /lib64/libasan.so.6 (0x00007f8079580000)
	libasan.so.6 => /lib64/libasan.so.6 (0x00007fb30ca75000)
	libasan.so.6 => /lib64/libasan.so.6 (0x00007f39e4cb8000)
	libasan.so.6 => /lib64/libasan.so.6 (0x00007fe3fc865000)
	libasan.so.6 => /lib64/libasan.so.6 (0x00007f3400ae5000)
	libasan.so.6 => /lib64/libasan.so.6 (0x00007fd0585a6000)
	libasan.so.6 => /lib64/libasan.so.6 (0x00007f01d614a000)
	libasan.so.6 => /lib64/libasan.so.6 (0x00007f8468d04000)
	libasan.so.6 => /lib64/libasan.so.6 (0x00007f87325be000)
	libasan.so.6 => /lib64/libasan.so.6 (0x00007fce61bd5000)
	libasan.so.6 => /lib64/libasan.so.6 (0x00007f68ff470000)
	libasan.so.6 => /lib64/libasan.so.6 (0x00007fcb3f210000)
	libasan.so.6 => /lib64/libasan.so.6 (0x00007f2e098e0000)
	libasan.so.6 => /lib64/libasan.so.6 (0x00007f05f3468000)
```

**Comment by daleglass** [comment]
Thought: could anything from vcpkg be involved here?

**Comment by JulianGro** [comment]
I might take a look at this as well since I have dabbled a lot with vcpkg on different architectures.

**Comment by daleglass** [comment]
This would be a very good one to fix, because there seems to be some sort of memory corruption issue currently that's hard to debug. Valgrind isn't working unfortunately since it makes the interface run extremely slowly to the point it's completely unusable.
