### ISSUE TITLE
interface needs much better performance monitoring

### ISSUE THREAD

**Issue by daleglass** [vircadia/vircadia#1120]
SL has amazing tools for performance monitoring:

![sl_performance](https://user-images.githubusercontent.com/51060919/112730104-f44f3a80-8f2f-11eb-9537-7d63058980e0.png)

We could really use more of this kind of thing.

**Comment by daleglass** [comment]
Dev meeting: see if any sort of stats logging functionality is present in the code

**Comment by JulianGro** [comment]
There is a good amount of external software to generate graphs out of text files. It will probably make sense to use a fairly standard format for logging so it can be parsed by a tool of our liking.

**Comment by daleglass** [comment]
Yes, I am thinking dump CSV, JSON or something else sensible, and then maybe at a later time develop a specific tool for it, if there's no suitable third party software.

Graphing is easy enough, but what I'd really like is something in the style of what SL provides: real time, with functionality that allows you to how detailed of a view you want.

**Comment by HifiExperiments** [comment]
we have some of this already.  for offline traces, hifi_tests contains instructions for generating traces which can be viewed in chrome: https://github.com/vircadia/hifi_tests/blob/master/benchmarks/README.md#creating-a-trace

for real-time, the scripting interface supports some graphing tools that I’ve never used, but there are demos in some of the render utility scripts, like for tracking LOD and physics workload performance

**Comment by daleglass** [comment]
I just gave that a try, and I think this still needs more work.

This is very much a developer tool. Using --testScript requires a restart, and dumps me into the void for some reason.

What I think we could really use is a version that an end user could easily use, to capture the problem as it's happening, without interrupting what they're doing. Something permanently present in the Developer menu, perhaps.

**Comment by daleglass** [comment]
Also, I'm not sure if I'm doing something wrong, but there seems to be extremely little information in the trace I get. I see some render stats like GPU memory, but no way to get deeper, like how much time is getting spent on what part of the rendering process.

**Comment by JulianGro** [comment]
> Also, I'm not sure if I'm doing something wrong, but there seems to be extremely little information in the trace I get. I see some render stats like GPU memory, but no way to get deeper, like how much time is getting spent on what part of the rendering process.

According to their documentation, you need to put "Profile Ranges" in first. https://github.com/vircadia/hifi_tests/blob/master/benchmarks/README.md#adding-profile-ranges
Just looking at that part of the repo, it looks like a good benchmark utility for developers. All performance issues that I know of right now, can probably be traced with this. But I guess we would need some soft of benchmark build to really get all the information we need.

**Comment by HifiExperiments** [comment]
there are already a lot of profile ranges, the traces should definitely be showing more.  are you on linux?  maybe it’s broken there.  I can take a screenshot of what a trace looks like to me when I get a chance, but if you scroll down below the general stats at the top, you should see a breakdown for each individual thread, including scripts

in terms of “render performance”, all of the different stages of the graphics pipeline have these profile ranges, but they only measure CPU time for enqueuing all the times.  generally, capturing GPU time is a bit trickier and I don’t think we have anything for that yet (one of the many reasons why we don’t have a better LOD solution: we don’t actually know exactly how long each object takes to render)

similarly, we have real-time timing stats exposed via the Stats, which can be toggled in Developer > Timing.  these times are accessible via JS, so someone could write a script to graph them in real time

I will say that all of these timing measurements have a non-zero cost.  just enabling the stats actually has a measurable impact on performance

**Comment by daleglass** [comment]
I'm on Linux, yes. I get this:

![trace](https://user-images.githubusercontent.com/51060919/113601189-4df6e980-9641-11eb-8821-9020d7e2312f.png)

**Comment by HifiExperiments** [comment]
oh you’ve got everything.  select the bottom tool on the right, use it to zoom in to a smaller timestep, and then each of those threads (Main Thread, Render Thread, etc) will show you all the individual profile ranges

**Comment by daleglass** [comment]
Ah, I see now. Yes, that does look very useful.

I still think some improvements at least UI-wise would be very helpful. First, a way for any random user to easily create a trace, without needing anything external or restarting. Just select something from the menu.

So perhaps we could include a modified `manual.js` with interface, and put an option somewhere in the Developer menu.

**Comment by HifiExperiments** [comment]
I think the only thing necessary for that would be to remove this if check: https://github.com/vircadia/vircadia/blob/1751a59c00ef52725e6837403ae929e7b6609cbe/interface/src/Application.cpp#L7491

(and obviously add that developer option to the menu to run the script)

trying to remember why this requires restarting with the flag, I think the concern was that some of the test scripting interface API had the potential to be used for griefing (writing to files on a users system).  in particular, testscriptinginterface::saveObject is dangerous

**Comment by daleglass** [comment]
Oof, good point.

This reminds me that we should start coming up with some sort of plan for script security, because right now there's almost none, and QtScript is deprecated and will need a replacement. It's gone in Qt 6.

Maybe we could create some sort of temporary simpler way of dealing with such functionality meanwhile, because replacing the script engine will be a big project.

**Comment by JulianGro** [comment]
:anger:
