### ISSUE TITLE
Entities at edge of FOV start rendering late

### ISSUE THREAD

**Issue by ctrlaltdavid** [vircadia/vircadia#1135]
Alezia reports ...
"
Using the valve index headset, since the FOV is larger, small entities with a visual perception of less than 20 degrees are starting to render within the FOV.
Basically, you see the entities appear instead of being already there on the edge of your visual field (horizontally).
This happens when the position and the position of the entities' edge are both within the angle gap (index fov versus the fov use by the renderer).
"
See also: "Valve Index Rendering effects do not extend all the way" https://github.com/vircadia/vircadia/issues/263

**Comment by AleziaKurdis** [comment]
![image](https://user-images.githubusercontent.com/60075796/113085798-83698600-91ae-11eb-96b8-84c8b4009c38.png)

**Comment by AleziaKurdis** [comment]
I got confirmation from XaosPrincess that the the Pimax (5k+) have similar issues. (and even worse)

According her:
- The entities are glitching on the last third of the Pimax FOV (which is 200 degree). Entities get displayed suddenly or disappears as the head move (which correspond to the issue seen on Valve Index).
- She also described issue with the haze that seem to be rendered differently over a certain % of the FOV (from the Pimax FOV edge), letting think that the wrong FOV could be also applied in this part of the rendering too. (We don't experience this on the Valve Index, but I suspect that it would if the FOV was to be larger.)
- This was originally rending correctly under the Hifi age, but it would have got broken during the last year of their reign. I suspect next to any optimization.

She also mentioned 2 developer names “Canny" and "Sarazen” who had a possible solution for that. (That never be initiated)
I don’t know if those names are involved in the optimization that might have broken this. (I put the info here, in case this could be helpful to figure something.)

**Comment by HifiExperiments** [comment]
see: openvrdisplayplugin::getCullingProjection
and lower down:
`// FIXME Calculate the proper combined projection by using GetProjectionRaw values from both eyes
        _cullingProjection = _eyeProjections[0]; `
basically, we’re only using the left eye for culling, which doesn’t completely overlap the right eye.  hifi gave up on this problem (how to get a projection matrix that encompasses both eyes), but luckily, that’s what math is for: https://computergraphics.stackexchange.com/questions/1736/vr-and-frustum-culling

**Comment by Aitolda** [comment]
> She also mentioned 2 developer names “Canny" and "Sarazen” who had a possible solution for that. (That never be initiated)

[Canny](https://canny.io/) was the reporting tool used by High Fidelity the last year of the project and the user/developer "Saracen" had made some comments and suggestions on this.  Not sure if we have any way to reference this anymore without contacting him directly.

**Comment by ctrlaltdavid** [comment]
There are at least two items here, possibly three:
1) Fix "regular" HMDs' view frustum so that it encompasses both eyes rather than being just the view frustum of the left eye.
2) Address combined eyes' FOV > 180 degree (e.g., PiMax HMD). This will likely involve combining the output of two separate view frustums because frustum maths breaks down for angles > 180 degrees. Probably warrants a separate code path to avoid extra computation for "regular" HMDs.
3) There might be some buffer size irregularities resulting in parts of rendering not making it into the RHS of the view.

**Comment by AleziaKurdis** [comment]
-

**Comment by ksuprynowicz** [comment]
It is still a problem on HP Reverb G2 too

**Comment by AleziaKurdis** [comment]
yes it is
