### ISSUE TITLE
Unused 'forward' variable in GizmoEntityRenderer::doRender(RenderArgs* args)

### ISSUE THREAD

**Issue by daleglass** [vircadia/vircadia#1146]
Here:

https://github.com/vircadia/vircadia/blob/master/libraries/entities-renderer/src/RenderableGizmoEntityItem.cpp#L265

I'm not quite sure if it's supposed to be used, or remains from something no longer needed.

@HifiExperiments any ideas?

**Comment by HifiExperiments** [comment]
whoops...yeah, I believe this is unneeded
