### ISSUE TITLE
ReadyPlayerMe full support (easy).

### ISSUE THREAD

**Issue by Aitolda** [vircadia/vircadia#1168]
All we have to do is translate a few blendshapes.  jawOpen on RPM matches JawOpen for Vircaida. eyeblinkleft for RPM matches EyeBlink_L in Vircadia.  Otherwise works perfectly.

Note: The Kiosk in the Hub is adding the translation on those avatars, but we need to make it so one that's imported or stored elsewhere works automatically too.  I assume we can just borrow the list from the kiosk for this.

Values from the FST generated by the kiosk.  I believe there are other shapes supported that we don't mention in the docs.
bs = BrowsU_L = browOuterUpLeft = 0.3
bs = BrowsU_C = browInnerUp = 0.3
bs = BrowsU_R = browOuterUpRight = 0.3
bs = BrowsD_R = browDownRight = 0.5
bs = BrowsD_L = browDownLeft = 0.5
bs = EyeBlink_L = eyeBlinkLeft = 1
bs = EyeBlink_R = eyeBlinkRight = 1
bs = EyeOpen_L = eyeWideLeft = 1
bs = EyeOpen_R = eyeWideRight = 1
bs = JawOpen = mouthOpen = 1
bs = MouthSmile_R = mouthRight = 0.6
bs = MouthSmile_L = mouthLeft = 0.6
bs = LipsFunnel = viseme_O = 0.5
bs = LipsUpperClose = mouthShrugLower = 0.1

**Comment by Aitolda** [comment]
![Blendshapes](https://user-images.githubusercontent.com/21160271/114245600-a0881c80-9945-11eb-878c-f0e4f6c7aea8.jpeg)

I believe all the shapes mentioned here are actually supported, but someone may need to look at the code to verify this.

**Comment by AleziaKurdis** [comment]
That blendshape mapping for "Ready Player me" was from me.
To make it, I started with an old wolf3d avatar (one from the 1rst tool they provided to High Fidelity)
I have assumed that it was established by High Fidelity and seems to be a good minimum. (I didn't have any exhaustive list of what we are supporting, as you pasted just before.)
So I compared the blendhape of that avatar and find what was corresponding the most on the new  "Ready Player me" avatar (the check was done visually in Blender (as you can't trust name only, most of them were different anyway.)
"Ready Player me" avatar support many other blendshape, certainly many could be also mapped with this picture. But that will need a visual check in blender to figure that new mapping.

"Ready Player me" support also "viseme" blendshape. That seems to be a standard to manage lipsync. Maybe this should be explored too.

**Comment by AleziaKurdis** [comment]
Here's the list supported by ReadyPlayerMe:

![image](https://user-images.githubusercontent.com/60075796/114254595-52433f80-997e-11eb-8ae6-220a42aea1f5.png)

**Comment by SilverfishVR** [comment]
regarding supported blendshapes:
https://github.com/vircadia/vircadia-docs-sphinx/issues/58
