### ISSUE TITLE
API Docs front page not showing correctly

### ISSUE THREAD

**Issue by digisomni** [vircadia/vircadia#1169]
Currently the body of the front page does not load at https://apidocs.vircadia.dev/ after I pushed the latest deployment. A bug must have been introduced in a JSDocs reference somewhere in the last 6 months probably unless someone's looked at their compiled docs sooner than that.

**Comment by JulianGro** [comment]
If I build the documentation on latest master it works fine. This is on JSDoc 3.6.4

**Comment by digisomni** [comment]
Works now after I installed jsdoc globally. I did reinstall my OS in the last 6 months, odd though that there were no build issues...
