### ISSUE TITLE
User-real world height in Settings/Controls... can only be edited with steps of 1 meter

### ISSUE THREAD

**Issue by Basinsky** [vircadia/vircadia#117]
The field user-real world height in Settings/Controls.. can not be edited to the correct number. 1 meter is minimum and 2.2 is maximum. Pushing on the up and down buttons increases the height with 1 meter instead of 0.001 meter. Multiple input fields dont allow typing of decimal numbers.

**Comment by daleglass** [comment]
This is partially fixed by PR #1161, but there are still localization issues.
