### ISSUE TITLE
add option to disable click events when in create menu

### ISSUE THREAD

**Issue by SilverfishVR** [vircadia/vircadia#1208]
When selecting and moving entities that have scripts that react to mouse or controller input you end up triggering them all the time, for a sit script it is just mildly annoying, but if it is a script that teleports you to the end of the known universe and turn you into a platypus you really need to "break" the script URL's before attempting anything.

maybe halting script execution altogether is the best option but the main culprits, I think, are:

```
clickReleaseOnEntity
clickDownOnEntity
mousePressOnEntity
mouseReleaseOnEntity
hoverEnterEntity
hoverLeaveEntity
startFarTrigger
stopFarTrigger
startNearTrigger
continueNearTrigger
stopNearTrigger
```

**Comment by Aitolda** [comment]
This would be a nice feature.

**Comment by JulianGro** [comment]
#873
