### ISSUE TITLE
Feature: Allow selecting "green cubes"

### ISSUE THREAD

**Issue by SilverfishVR** [vircadia/vircadia#121]
Whenever I see a “green wire cube of not loaded entity” I want to click or laser it to see whats wrong or just delete it.

But for some reason, “green wire cube of not loaded entity”’s will have none of that, they ignore intersect.

I propose making “green wire cube of not loaded entity”’s intersectable when in create mode.

**Comment by HifiExperiments** [comment]
hmmm they should be selectable I think?  there is however an issue where they always render at size 1 meter, regardless of their actual dimensions (which control pick intersection).  so a .2 meter^3 model will show up as 1 meter^3, but only be clickable right at its center

**Comment by kasenvr** [comment]
I tried adjusting the local dimensions myself, even at a 1 meter local dimensioned broken model... I can't seem to click it, which it should be clickable in a 1 meter area, not only at its center.

So is this just a bug then?

**Comment by SilverfishVR** [comment]
Well, the green cube's size can't really be dependent on the size of the model that failed to load because, logic, it wouldn't have to be as big as  1M<sup>3</sup>, as long as it is all a selection target.
I think if it was a bug someone would have noticed, it's been like that forever.

**Comment by SilverfishVR** [comment]
The improvements to the create menu has made it easier, but I still want to able to select the green cube directly though.

**Comment by AleziaKurdis** [comment]
Seems to not be something that can be fixed on Create app side.

**Comment by SilverfishVR** [comment]
yes, from a UI perspective, the green be indicate an issue so you will want the user to easily find and fix it, currently you have to limit by distance and then test entity in the entity list /to see where it is)
