### ISSUE TITLE
PR builds broken for Ubuntu Android

### ISSUE THREAD

**Issue by ctrlaltdavid** [vircadia/vircadia#1215]
```
Welcome to Gradle 4.10.1!

Here are the highlights of this release:
 - Incremental Java compilation by default
 - Periodic Gradle caches cleanup
 - Gradle Kotlin DSL 1.0-RC6
 - Nested included builds
 - SNAPSHOT plugin versions in the `plugins {}` block

For more details see https://docs.gradle.org/4.10.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :framePlayer
Observed package id 'ndk;21.4.7075529' in inconsistent location '/usr/local/lib/android/sdk/ndk-bundle' (Expected '/usr/local/lib/android/sdk/ndk/21.4.7075529')

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':framePlayer'.
> Invalid revision: 3.18.1-g262b901
```

**Comment by JulianGro** [comment]
Is there just something wrong with the GitHub servers right now? Looks like everything is not working properly right now. https://github.com/vircadia/vircadia/runs/2591498588

**Comment by ctrlaltdavid** [comment]
No, it's an ongoing issue on PR builds - none have fully built for the last 4 days whereas merge to master builds have fully built, apart from one.

**Comment by JulianGro** [comment]
Yeah I think we will need some more info to fix this. It only says 
```
A problem occurred configuring project ':framePlayer'.
> Invalid revision: 3.18.1-g262b901
```
But there is no mention of `3.18.1` or `g262b901` in the repo, and it doesn't even tell us what has this invalid revision.

**Comment by ctrlaltdavid** [comment]
Example GHA build with log files that have more info: https://github.com/vircadia/vircadia/actions/runs/858409119

**Comment by ArcadeFever** [comment]
Did someone upgrade the NDK?  The Quest 1 build should be using Gradle model version=4.10.1, NDK version=19.2.5345600

**Comment by ctrlaltdavid** [comment]
I can't' find any relevant changes in source code, though I could be missing something because I'm not familiar with this part of the codebase.

Looking at GHA output, the build environment for PR builds appears to change between the last successful build and the first unsuccessful build.

Last successful build:
- GHA output: https://github.com/vircadia/vircadia/runs/2572066337?check_suite_focus=true#step:1:2
- GHA build environment: https://github.com/actions/virtual-environments/blob/ubuntu18/20210504.1/images/linux/Ubuntu1804-README.md

Last successful build: 
- GHA output: https://github.com/vircadia/vircadia/runs/2580440020?check_suite_focus=true
- GHA build environment: https://github.com/actions/virtual-environments/blob/ubuntu18/20210510.0/images/linux/Ubuntu1804-README.md
