### ISSUE TITLE
Facial blendshapes failing

### ISSUE THREAD

**Issue by Colorfingers** [vircadia/vircadia#1224]
Facial morphs fail where blendshapes names are duplicated... example... EyeBlink_L and EyeBlink_R will blink eyelashes but not the eyes on the avatar.  Expected behavior is that when EyeBlink blendshapes are called then both the eyelashes and eyes will blink at the same time.

Example model:

https://hapticmonkey.s3-us-west-1.amazonaws.com/avatar_blendshapes.glb

**Comment by Colorfingers** [comment]
Sorry... wrong base model... my bad.

**Comment by digisomni** [comment]
I just love it when issues solve themselves. lol
