### ISSUE TITLE
Feature: Disable animations when in wearables menu

### ISSUE THREAD

**Issue by SilverfishVR** [vircadia/vircadia#123]
When placing wearables on the avatar in the avatar menu it is quite annoying that I won’t stand still.
Animations should be disabled and avatar in a neutral idle pose (or T-pose).

Reproduce: try to precisely add an item to your avatar in the Avatar→wearables menu ,aarrgh.

**Comment by kasenvr** [comment]
I think a checkbox should be there to pause, pretty much all character creators let you view yourself with animations so you have a live preview then a frozen state so you can analyze parts as desired.

**Comment by SilverfishVR** [comment]
sure, but if you stand idle, without moving, after a short while, the wearables "detach" and no longer follow animations, this is on purpose I believe.

**Comment by SilverfishVR** [comment]
closing, the wearables system and the menu in particular is rather borked so no point in trying to fix this one thing, a general overhaul is probably needed.
