### ISSUE TITLE
Can't download Vircadia for Mac. Page doesn't open.

### ISSUE THREAD

**Issue by zarp-dev** [vircadia/vircadia#1237]
![Screenshot 2021-05-31 at 21 16 38](https://user-images.githubusercontent.com/65812041/120229438-d1a21080-c255-11eb-918c-5fd55dbe7a0c.png)

**Comment by digisomni** [comment]
Sorry, I didn't drop it into the right folder, here it is: https://cdn.vircadia.com/dist/release-experimental/Vircadia-Interface-2021.1.2-Eos.dmg
