### ISSUE TITLE
Update Linux WebRTC for Web app

### ISSUE THREAD

**Issue by ctrlaltdavid** [vircadia/vircadia#1240]
Requirements:
- Update the WebRTC version used to M84, at the same commit as Windows.
- Add WebRTC data channel to the WebRTC VCPKG. 

Windows WebRTC is updated in PR: https://github.com/vircadia/vircadia/pull/1221

libraries/networking/CMakeLists.txt
- See the comment, `# WEBRTC TODO: Add UNIX.`

libaries/shared/src/shared/WebRTC.h, in `Q_OS_LINUX` section:
- Remove `#  define WEBRTC_LEGACY 1`
- Add `#  define WEBRTC_DATA_CHANNEL 1`

**Comment by digisomni** [comment]
Updating this is not required for existing functionality, however this will be necessary to get web communications working.
