### ISSUE TITLE
Possible Linux audio issue

### ISSUE THREAD

**Issue by daleglass** [vircadia/vircadia#1241]
Audio seems to have died after working for a short time, then this happened on exit:

```
[06/05 20:04:10] [DEBUG] [hifi.render] Scene::~Scene()
[06/05 20:04:10] [DEBUG] [hifi.shared] Settings thread stopped.
[06/05 20:04:11] [DEBUG] [hifi.interface] Normal exit.
Assertion 'pthread_mutex_destroy(&m->mutex) == 0' failed at pulsecore/mutex-posix.c:83, function pa_mutex_free(). Aborting.
```

This is a bit of a placeholder for any future details that might materialize.

**Comment by JulianGro** [comment]
An issue that looks *similar*: https://github.com/vircadia/vircadia/issues/1234

**Comment by daleglass** [comment]
I don't think I've seen his happen in a very long time. Might be already fixed? Closing for now.
