### ISSUE TITLE
Assignment client spams log when it cannot access a file from the domain-server in /tmp on Linux.

### ISSUE THREAD

**Issue by digisomni** [vircadia/vircadia#1250]
This is especially present when running multiple domains that were created from the .deb created from pkg-scripts.

```
Jun 21 05:50:58 localhost assignment-client[730]: [06/21 05:50:58] [WARNING] [hifi.assignment-client] [2055] [assignment-client] ALERT: Failed to read local assignment server port from shared memory ( "domain-server.local-port" )- will send assignment request to previous
Jun 21 05:50:59 localhost assignment-client[730]: [06/21 05:50:59] [WARNING] [hifi.networking] [2055] [assignment-client] Could not attach to shared memory at key "domain-server.local-port" : "QSharedMemory::handle:: UNIX key file doesn't exist"
```

**Comment by JulianGro** [comment]
Judging by your PR, you already figured out that the issue is something else?

It seems weird to me that a program doesn't have access to /tmp

**Comment by digisomni** [comment]
They're isolated because they are being managed already by a system of services. However we don't have a way to override this feature where it keeps looking. So I think I have fixed that but we shall see.

**Comment by odysseus654** [comment]
The problem isn't a lack of access to /tmp, it has access.  The problem is that it can't see a file written by the domain-server, since /tmp access has been isolated.

**Comment by ctrlaltdavid** [comment]
How does this relate to the automatic networking setting in the domain server?
![image](https://user-images.githubusercontent.com/7455448/126711039-b093cbc2-58b4-410d-8f3e-cce3b1ea2cca.png)
