### ISSUE TITLE
Deprecate GooglePoly API

### ISSUE THREAD

**Issue by SilverfishVR** [vircadia/vircadia#1256]
Google poly will close as of 2021-06-30 so actually it could safely be removed entirely.

**Comment by daleglass** [comment]
This seems worth exploring: https://poly.pizza/

https://www.reddit.com/r/gamedev/comments/o6e5tr/6000_free_models_google_poly_is_shutting_down_so/

**Comment by daleglass** [comment]
Left a comment there, there's no API yet, but I was referred to https://beta.icosa.gallery/

They have source at https://github.com/icosa-gallery and apparently are aiming at API compatibility.

**Comment by ctrlaltdavid** [comment]
Some info on Google Poly shutting down: https://vrscout.com/news/google-poly-is-shutting-down/
