### ISSUE TITLE
Rename 'HifiSockAddr' to 'SockAddr'.

### ISSUE THREAD

**Issue by digisomni** [vircadia/vircadia#1281]
- [x] Vircadia `master` branch. https://github.com/vircadia/vircadia/pull/1283
- [x] Vircadia `webapp` branch. https://github.com/vircadia/vircadia/pull/1296
- [x] Vircadia Web SDK.  https://github.com/vircadia/vircadia-web-sdk/pull/15

**Comment by ctrlaltdavid** [comment]
All HifiSockAddr PRs have been merged.
