### ISSUE TITLE
Building quazip fails on Ubuntu 21.04

### ISSUE THREAD

**Issue by JulianGro** [vircadia/vircadia#1284]
Building quazip fails on Ubuntu 21.04 with `Configuring incomplete, errors occurred!`

[config-x64-linux-dbg-out.log](https://github.com/vircadia/vircadia/files/6769938/config-x64-linux-dbg-out.log)
[CMakeOutput.log](https://github.com/vircadia/vircadia/files/6769939/CMakeOutput.log)

I haven't been able to get smart of this yet. At first I thought we might have broken the vircadia-builder <-> vircadia interaction with the CMake changes, but building the same thing on Ubuntu 18.04 works.

**Comment by daleglass** [comment]
Hm, this looks like there's some log output still missing. What do you get from the vcpkg stage of cmake?

**Comment by JulianGro** [comment]
Not sure what you mean. Just the main build log that would have been shown in terminal?

**Comment by daleglass** [comment]
Yeah, I'm wondering if something is missing? I'm not seeing whatever is going wrong in those logs, maybe there's more somewhere else?

**Comment by JulianGro** [comment]
This is all I have.
[quazip.zip](https://github.com/vircadia/vircadia/files/6773109/quazip.zip)
[vircadia-builder-log.zip](https://github.com/vircadia/vircadia/files/6773112/vircadia-builder-log.zip)

**Comment by daleglass** [comment]
I've just built the latest source with the latest vircadia-builder (just updated), and quazip doesn't seem to be an issue. Could you test again and see if it still happens?

**Comment by JulianGro** [comment]
I just retested and the issue resolved itself. I assume an update to Ubuntu 21.04 did the trick.
