### ISSUE TITLE
Cannot build interface on Ubuntu 21.04

### ISSUE THREAD

**Issue by JulianGro** [vircadia/vircadia#1294]
The build fails right at the end when trying to copy resources.rcc
If I remember correctly, shocktail had this same issue on Gentoo.

https://gist.github.com/JulianGro/1ffabdd9913e9067395147c867a79f80

**Comment by daleglass** [comment]
Please test #943, that may contain changes that fix the issue.

**Comment by daleglass** [comment]
I completed a test build of that PR on 21.04 with success

**Comment by JulianGro** [comment]
I can confirm that PR https://github.com/vircadia/vircadia/pull/943 fixes the issue
