### ISSUE TITLE
Interface hangs for 30+ seconds before closing

### ISSUE THREAD

**Issue by two-one-five** [vircadia/vircadia#130]
For K3 milestone probably if this has been the *same* longstanding bug!

**Comment by thoys** [comment]
Probably related to script engines closing down. Does this happen on every domain or just on domains like thepalace? Also are you just running the default scripts?

**Comment by daleglass** [comment]
Can we get a repro and more data on this? Like does it happen predictably on a particular OS, or with some particular script installed? Log dumps would help a lot.

Also, please include the system specs including RAM, disk type (SSD or HDD), CPU and GPU.

Here on Linux I would say shutdown goes at a very reasonable speed, but I got myself about as much machine as I could afford, and the possibility exists that with enough hardware it just isn't that big of a deal. Things like many cores or a SSD might be a noticeable influence.

**Comment by ctrlaltdavid** [comment]
Repro (on Windows) is to open and close an HTML app (e.g., GoTo, People, Avatar, or FloofChat. Opening and closing a QML dialog (e.g., Running Scripts, Asset Server) does not result in a hang.

**Comment by jug007** [comment]
My interface has often not been shutting down at all.
Here is a log from it freezing: https://gist.github.com/jug007/9247ca33733400ad8edd90b33123d1c8

**Comment by odysseus654** [comment]
I did manage to deadlock my interface a couple times and catch it in the VS debugger long enough to track down and make a PR that resolves at least one of the causes of this ( https://github.com/kasenvr/project-athena/pull/311 ), which would be an web request (likely an XHR from an app) hitting a permission filter that can only run on the main thread, while the main thread is being shut down and not accepting requests.

**Comment by daleglass** [comment]
Dev meeting: it would be good to have some logs here. The question is: is shutdown slow because something gets stuck, or because there's just a lot of things to do?

**Comment by JulianGro** [comment]
My understanding is that this issue was fixed. Multiple bugs which caused long shutdown times have been fixed. It might still be longer than it could be, but it's definitely not 30+ seconds anymore.

**Comment by daleglass** [comment]
Yes, I also had the impression that it's been fixed. Sure, shutdown takes time, but everything does.

**Comment by odysseus654** [comment]
This shouldn't have been the issue that was resolved last year with https://github.com/vircadia/vircadia/pull/311 I'm hoping (or again that there are multiple causes), so some additional info from the reporter would still be useful.

**Comment by Penguin-Guru** [comment]
I have noticed that shutdown of the AppImage is pretty slow; but, like Julian said, not 30+ seconds. 11 seconds seems about right. It feels much slower than any other program I use, but not slow enough to be alarming. I think it would be good to investigate ways of speeding this up at some point but that's probably out of scope for this issue.
