### ISSUE TITLE
Interface failing to run on master - Windows

### ISSUE THREAD

**Issue by digisomni** [vircadia/vircadia#1308]
![image](https://user-images.githubusercontent.com/69767640/129271489-190b8432-d35a-4663-be3e-c84c962643ba.png)

**Comment by ctrlaltdavid** [comment]
I built current master on Windows...
There is not a resources.rcc file in \build\interface\Release.
But there is a resources.rcc file in \build\interface.
If I copy that resources.rcc file into \build\interface\Release, Interface works both from the command line and under the debugger.
(Older builds of Interface have a resources.rcc file in \build\interface\Release, too.)
