### ISSUE TITLE
User docs links  in JSDoc need updating to new docs location

### ISSUE THREAD

**Issue by ctrlaltdavid** [vircadia/vircadia#1312]
User docs links should be to docs.vircadia.com instead of docs.virvadia.dev.

For example, the link to "Avatar Standards" in  https://apidocs.vircadia.dev/MyAvatar.html#.setBlendshape is broken.
The link currently points to: https://docs.vircadia.dev/create/avatars/avatar-standards.html#blendshapes
The link should point to:  https://docs.vircadia.com/create/avatars/avatar-standards.html#blendshapes

**Comment by daleglass** [comment]
Seems to work now.
