### ISSUE TITLE
I need help connecting to the server. Can someone help me a little?

### ISSUE THREAD

**Issue by jjsboss0** [vircadia/vircadia#1323]
hello
Can someone help me a little?

I have built a server through two manuals.

https://github.com/vircadia/Iamus/blob/master/docs/NotesOnDevelopment.md

https://github.com/vircadia/Iamus/blob/master/docs/RunningDockerImage.md

This is it.

Both servers are ubuntu
The interface is window .

------------------------------------------------------------ ------------------------------------------------------------ ----
The two known places that need modification are libraries/networking/src/NetworkingConstants.h and domain-server/resources/web/js/shared.js.
------------------------------------------------------------ ------------------------------------------------------------ ----

Read this and find the path
I've tried changing it to IP.
It doesn't work.
What do I need to modify to connect to our server?

If you have a document that you can refer to, please share.

**Comment by Misterblue** [comment]
Are you trying to run the metaverse server? Iamus is the metaverse-server that runs at metaverse.vircadia.com/live.

In Vircadia there is the metaverse-server which coordinates the domain-servers. If you're trying to run your own domain (virtual space), you should be reading the docs for hosting your own domain: https://docs.vircadia.com/host.html .

**Comment by jjsboss0** [comment]
> 메타버스 서버를 실행하려고 합니까? Iamus는 metaverse.vircadia.com/live에서 실행되는 메타버스 서버입니다.
> 
> Vircadia에는 ​​도메인 서버를 조정하는 메타버스 서버가 있습니다. 자신의 도메인(가상 공간)을 실행하려는 경우 자체 도메인 호스팅에 대한 문서를 읽어야 합니다. https://docs.vircadia.com/host.html .

-------------------------------------------------------------------------------------------------------------

thank you.
I set it up according to the document.
But I haven't been able to access it yet.
I will try again tomorrow.

**Comment by digisomni** [comment]
Were you successful?

**Comment by jjsboss0** [comment]
> Were you successful?

Haven't succeeded yet.
I'll look at the documentation a bit more and ask a question.
Thanks for your help.
