### ISSUE TITLE
Unneeded files in AppImages.

### ISSUE THREAD

**Issue by JulianGro** [vircadia/vircadia#1328]
I thought while I was in the releases I might as well list some files that I deem unneeded that could be removed in future releases. In my case, this list comes from the release AppImages. Other releases might have more or less trash in them.

- `/vircadia/interface/resources.qrc` very sure that that file is only used to generate `/vircadia/interface/resources.rcc`, so it is useless in a release.
- `/vircadia/interface/jsdoc/` as far as I know there is no way to actually view this documentation (except for extracting the AppImage and manually opening it), so there is no reason to ship 40 MiB and 141 files.
- `/vircadia/interface/plugins/libsteamClient.so` we don't have a Steam release and especially aren't releasing an AppImage on Steam.
- `/vircadia/ext/` as it currently only contains files needed for a Steam release.
- `/vircadia/plugins/steamClient/` same here.
- `/vircadia/server-console/` we don't have a server console on Linux yet, and even if we had one we probably shouldn't put it in the same AppImage.
- `/vircadia/tools/` currently there is only a part of Nitpick in there, but we wouldn't want to ship any standalone tools inside the release AppImage in the future as well.
- `/vircadia/libraries/auto-updater/` not in use, but I guess that could change in the future.
- `/vircadia/interface/scripts/simplifiedUI/` isn't used by standard, isn't easily accessible, and isn't really supported by us. 1038 files and 79 MiB that are wasted.

While this slight waste isn't really worth anything for the compressed AppImages, it is interesting for future packages (like for Debian/Ubuntu) or for Windows. Especially on Windows it always bothered me how long it takes to install Vircadia, and saving almost 1200 files would definitely knock the installation time down a bit, especially on harddrives.

**Comment by digisomni** [comment]
The nametag in simplifiedUI is used by default currently.

**Comment by daleglass** [comment]
This change would be made in vircadia-builder
