### ISSUE TITLE
hello can you help me??

### ISSUE THREAD

**Issue by jjsboss0** [vircadia/vircadia#1331]
domain server started.
Try to connect to the domin IP through explore.
The user's information is printed from the domin server.
But the interface shows "no connection".
What could be wrong??
Any help would be appreciated.

![131983698-53a392eb-23d5-4f27-842c-e6ee0f4c4fc9](https://user-images.githubusercontent.com/34049645/131984266-f9920d9b-ff48-4f55-8a68-8244e903f411.png)

**Comment by JulianGro** [comment]
Are you sure you are allowed to connect to the domain?
Maybe only "localhost" is allowed to connect?

**Comment by daleglass** [comment]
Hello! This may be better suited for our Discord:

https://discord.com/invite/Pvx2vke

But there are multiple possible issues there, from the server not actually running, to firewall issues

**Comment by jjsboss0** [comment]
https://dashboard.vircadia.com/domain
domain has been deleted from
Is there any way to bring it back to life?

![image](https://user-images.githubusercontent.com/34049645/132200072-938ebdb8-e460-4f01-bee0-e7fc3a3cd43d.png)

**Comment by jjsboss0** [comment]
With Kalila's advice
I solved it by moving the server.
Thanks to everyone for your interest.
