### ISSUE TITLE
Unable to find my own places in ‘EXPLORE’

### ISSUE THREAD

**Issue by Gyro-XR** [vircadia/vircadia#1334]

**Comment by JulianGro** [comment]
"places" are not integrated into the explore app yet as far as I know. You can type you place name in manually, or put down a Beacon via the plus button inside the explore app.

**Comment by digisomni** [comment]
Yep, in the current version you have to use the beacon. However, in master and therefore in the next release they will be integrated with Explore.

**Comment by Gyro-XR** [comment]
> Yep, in the current version you have to use the beacon. However, in master and therefore in the next release they will be integrated with Explore.

thanks~
