### ISSUE TITLE
Add “Copy – Cut - Paste” buttons on the VR keyboard

### ISSUE THREAD

**Issue by AleziaKurdis** [vircadia/vircadia#134]
We should be able to do copy-cut-paste using the tablet. Mainly important to be able to work in VR, or to paste text or URL in the chat window without having to exit VR.

Found in Release: **0.86 (Hifi)**
Type: **Enhancement**
Priority: **Medium**
Size: **M**

**Comment by AleziaKurdis** [comment]
Here a modified keyboard.json
and 3 new resources for the Copy, Cut and Paste

[keyboard_modifs.zip](https://github.com/kasenvr/project-athena/files/4120666/keyboard_modifs.zip)

I hope this could help.

**Comment by AleziaKurdis** [comment]
Here a modified keyboard with: 
- the Copy Cut Past (json and png files)
- a Numeric pad on the main layer (because it's annoying to have to switch each time we enter a numeric value)
- Some useful char added on the main layer. ( / : ,  for the URL and paths)

[keyboard_modifs_with_Num Pad.zip](https://github.com/kasenvr/project-athena/files/4120738/keyboard_modifs_with_Num.Pad.zip)

**Comment by daleglass** [comment]
what's in the .zip? Is this a PR?

**Comment by AleziaKurdis** [comment]
new Texture files for new keys and reorganize some existing ones
and new keyboard configuration.
But I never been able to compile Interface so I never been able to test this.
You can ignore that. (It wasn't to make a PR blindly)
