### ISSUE TITLE
Enabling rendering effects reduces resolution in VR on HP Reverb G2

### ISSUE THREAD

**Issue by ksuprynowicz** [vircadia/vircadia#1357]
I noticed that enabling any kind of rendering effects (local lights, bloom, shadows, etc.) significantly reduces resolution of rendered image when using VR headset (Resolution on Steam VR is fixed to 100% setting, not _auto_ so it isn't caused by Steam). GPU frame size in render statistics doesn't change though. I haven't noticed anything similar after enabling rendering effects in non-VR mode - image stays sharp there and is redered at full resolution.
Here's the comparison of image with and without rendering effects:

![sharpness_comparison](https://user-images.githubusercontent.com/11568651/134423771-569fae71-d335-4d4b-afcc-a35fa05df389.png)

**Comment by JulianGro** [comment]
I am pretty sure that this is just the extremely bad anti-aliasing. The same happens in Desktop mode, but obviously it is much more prominent on a high resolution HMD.
This should be fixed by: https://github.com/vircadia/vircadia/pull/576

**Comment by ksuprynowicz** [comment]
Is there any way of completely disabling antialiasing while keeping local lights enabled?

**Comment by Basinsky** [comment]
@ksuprynowicz maybe this could be useful https://bas-skyspace.ams3.digitaloceanspaces.com/Scripts/EncrispenCrispHiFi.js

**Comment by ksuprynowicz** [comment]
Thanks! I'll give it a try :)

**Comment by ksuprynowicz** [comment]
> @ksuprynowicz maybe this could be useful https://bas-skyspace.ams3.digitaloceanspaces.com/Scripts/EncrispenCrispHiFi.js

It works! With those lines antialiasing is disabled, image is very sharp and resolution is the same as without rendering effects:

```
        Render.getConfig("RenderMainView.Antialiasing")["constrainColor"] = false;
        Render.getConfig("RenderMainView.Antialiasing")["feedbackColor"] = false;
        Render.getConfig("RenderMainView.Antialiasing")["blend"] = 1;
        Render.getConfig("RenderMainView.Antialiasing")["sharpen"] = 0.2;
        Render.getConfig("RenderMainView.JitterCam").none();
```
I think such option should be the part of graphics menu. It looks incomparably better than antialiasing.

**Comment by ksuprynowicz** [comment]
I captured render buffers using RenderDoc and confirmed that it's just a broken antialiasing algorithm.

**Comment by JulianGro** [comment]
Okay so that will be fixed by the new TAA PR once that gets merged ;)
~~The PR we have only been waiting for for over a year~~
