### ISSUE TITLE
Name Change breaks servers upgrading from HiFi to Athena

### ISSUE THREAD

**Issue by kasenvr** [vircadia/vircadia#137]
https://github.com/kasenvr/project-athena/commit/879e5fdded3b137686ac5e8e87bb9ecd8a33b536

In this PR the name changes as appropriate. For new servers this is not an issue, but for a server upgrading, then the assets would not be found as the name is changed. They will all be in the old folder. Just a heads up or something for upgraders to take note of to transfer the files or be aware of the fresh start and any potential errors that can arise from this.

Thank you, Odysseus for the tip!

**Comment by daleglass** [comment]
Also possibly needs improvement for users running multiple interfaces at once (eg, testing multiple branches), and taking multiple user accounts into account

**Comment by digisomni** [comment]
This probably is no longer relevant as we've migrated entirely. Someone should open a new issue if this comes up again.
