### ISSUE TITLE
Extremely low game loop performance on Linux

### ISSUE THREAD

**Issue by ksuprynowicz** [vircadia/vircadia#1381]
Game Rate in developer statistics sometimes drops to 9 FPS dual Xeon machine with 20 cores and 3 GHz base clock running Debian Testing and most recent official Vircadia release. Avatar movement gets very choppy then, and terminal continously reports this warning:

`[10/02 14:15:45] [DEBUG] [hifi.interface.deadlock] DEADLOCK WATCHDOG WARNING: lastHeartbeatAge: 5458 elapsedMovingAverage: 4252 maxElapsed: 3184264 PREVIOUS maxElapsedAverage: 4251 NEW maxElapsedAverage: 4252 ** NEW MAX ELAPSED AVERAGE ** samples: 4524`

Render and present rate are at consistent 60 FPS all the time during test.

It seems that game rate depends on position and switches sharply between 30 and 9 FPS. Profiler reports coming soon.

**Comment by JulianGro** [comment]
What I assume you are running into is that you are using exact collisions on "big" model. Check the "Simulation" times in the `/` menu.
Partially duplicate of https://github.com/vircadia/vircadia/issues/898

**Comment by ksuprynowicz** [comment]
> What I assume you are running into is that you are using exact collisions on "big" model. Check the "Simulation" times in the `/` menu. Partially duplicate of #898

True, it's a mesh with large polygon count, but triangles are evenly sized, and just a few of them are close to avatar at the same time. Bullet physics uses BHV acceleration structure in such cases and it's authors advise to join several smaller static meshes into a larger one due to how fast it is. From my previous experience with Bullet such simulation should run order of magnitude faster than it does here, but I'm not sure what's causing it yet. Bullet seems to spend a lot of time processing triangles during each frame, while it should process just a few of them:

```
-   45.14%     0.00%  interface  interface                      [.] main
     main
     QCoreApplication::exec
     QEventLoop::exec
     QEventDispatcherGlib::processEvents
     g_main_context_iteration
   - g_main_context_iterate.constprop.0
      - 45.11% g_main_context_dispatch
         - 45.05% postEventSourceDispatch
              QCoreApplicationPrivate::sendPostedEvents
              QCoreApplication::notifyInternal2
              Application::notify
              QApplicationPrivate::notify_helper
              Application::event
            - Application::idle
               - 44.77% Application::update
                  - 35.32% ReadWriteLockable::withWriteLock<Application::update(float)::{lambda()#18}>
                       Application::update(float)::{lambda()#18}::operator()
                       PhysicsEngine::stepSimulation
                     - ThreadSafeDynamicsWorld::stepSimulationWithSubstepCallback
                        - 35.23% btDiscreteDynamicsWorld::internalSingleStepSimulation
                           - 34.93% btCollisionWorld::performDiscreteCollisionDetection
                              - 34.87% btCollisionDispatcher::dispatchAllCollisionPairs
                                   btHashedOverlappingPairCache::processAllOverlappingPairs
                                   btHashedOverlappingPairCache::processAllOverlappingPairs
                                   btCollisionPairCallback::processOverlap
                                 - btCollisionDispatcher::defaultNearCallback
                                    - 34.65% btConvexConcaveCollisionAlgorithm::processCollision
                                       - 34.62% btBvhTriangleMeshShape::processAllTriangles
                                          - btQuantizedBvh::reportAabbOverlappingNodex
                                             - 34.59% btQuantizedBvh::walkStacklessQuantizedTree
                                                - 33.59% btBvhTriangleMeshShape::processAllTriangles(btTriangleCallback*, btVector3 const&, btVector3 const&)
                                                   - 32.22% btConvexTriangleCallback::processTriangle
                                                      + 26.64% btConvexConvexAlgorithm::processCollision
                                                        1.52% TestTriangleAgainstAabb2
                                                      + 0.88% btCollisionDispatcher::findAlgorithm
                                                      + 0.61% btTriangleShape::btTriangleShape
                                                  0.61% testQuantizedAabbAgainstQuantizedAabb
                  + 3.51% AvatarManager::updateMyAvatar
                  + 1.86% controller::UserInputMapper::update
                  + 1.74% PickManager::update
                  + 0.88% EntityTreeRenderer::preUpdate
```
When everything works well, avatar update and IK seems to be taking a large part of simulation time (it's 1/3 of entire frame time). Large part of that time is spent on matrix operations:

```
-   23.20%     0.00%  interface        interface                      [.] main
     main 
     QCoreApplication::exec
     QEventLoop::exec
     QEventDispatcherGlib::processEvents
     g_main_context_iteration
   - g_main_context_iterate.constprop.0
      - 23.15% g_main_context_dispatch
         - 23.05% postEventSourceDispatch
            - QCoreApplicationPrivate::sendPostedEvents
               - 23.02% QCoreApplication::notifyInternal2
                    Application::notify
                  - QApplicationPrivate::notify_helper
                     - 22.92% Application::event
                        - Application::idle
                           - 22.35% Application::update
                              - 7.87% AvatarManager::updateMyAvatar
                                 - 7.59% MyAvatar::update
                                    - 7.53% MyAvatar::simulate
                                       - 7.20% SkeletonModel::simulate
                                          - 7.17% Model::simulate
                                             - MySkeletonModel::updateRig
                                                - 6.55% Model::updateRig
                                                   - Rig::updateAnimations
                                                      - 5.98% AnimStateMachine::evaluate
                                                         - 5.96% AnimPoleVectorConstraint::evaluate
                                                            - 5.93% AnimTwoBoneIK::evaluate
                                                                 AnimPoleVectorConstraint::evaluate
                                                               - AnimTwoBoneIK::evaluate
                                                                  - 5.88% AnimOverlay::evaluate
                                                                     - 5.13% AnimInverseKinematics::overlay
                                                                        - 5.00% AnimInverseKinematics::solve
                                                                           - 4.40% AnimPose::operator*
                                                                              - 2.12% AnimPose::AnimPose
                                                                                   0.65% glm::quat_cast<float, (glm::qualifier)0>
                                                                              - 1.63% AnimPose::operator glm::mat<4, 4, float, (glm::qualifier)0>
                                                                                   1.06% glm::operator*<float, (glm::qualifier)0> 
                                                                                0.54% glm_mat4u_mul
                                                                     + 0.70% AnimOverlay::evaluate
                              - 3.94% controller::UserInputMapper::update
                                 - 3.68% controller::UserInputMapper::runMappings
                                    - 3.55% controller::UserInputMapper::applyRoutes
                                       + 2.69% std::__cxx11::list<std::shared_ptr<controller::Route>, std::allocator<std::shared_ptr<controller::Route> > >::r
                                         0.67% controller::UserInputMapper::applyRoute
                              + 3.50% PickManager::update
                              + 2.12% EntityTreeRenderer::preUpdate
                              + 1.32% ReadWriteLockable::withWriteLock<Application::update(float)::{lambda()#18}>
                              + 0.67% std::function<void ()>::operator()
                              + 0.60% PointerManager::update
```
I suspect that there may be two separate issues here. One might be a bug related to Bullet physics, causing it to process more triangles than needed, and another may be wrong compiler flags on Linux for Interface, Bullet or both. Is Bullet being built in Release mode? I wonder if Linux version of interface and Bullet is compiled with vectorisation enabled?

**Comment by JulianGro** [comment]
I don't think any of us has ever dabbled with how Bullet is being built. I think Dale has "only" fixed a couple of crashes.
Also yes, we should assume that these are separate issues.

**Comment by ksuprynowicz** [comment]
I have a lot of previous experience with Bullet so I will take a look. If fixed this could make Vircadia run a lot smoother.

**Comment by ksuprynowicz** [comment]
I think there are several things worth checking out here. In my opinion the most important one is that avatar's AABB seems way too big. Here's one for default avatar:
![image](https://user-images.githubusercontent.com/11568651/136009156-78d96225-412d-493c-a15c-909b74fe90a5.png)
On other avatars they get even bigger:
![image](https://user-images.githubusercontent.com/11568651/136009339-fd31edb8-8b86-40fb-a276-dac19f9180a1.png)
Another thing is that avatar seems to consist of a lot of collision shapes. I think it would be worth checking out if collision groups are assigned properly, so the shapes are not colliding against eachother. Collisions between them and the terrain don't seem to do anything at the moment, so grouping them in such a way that collision between them and terrain in the broadphase would be omitted would greatly increase performance too.
With such number of collision objects building Bullet with multithreading enabled would also help, if it's not enabled already.

**Comment by ksuprynowicz** [comment]
Another thing that is worth checking is compiler flags in general, and Bullet flags in particular. I will be checking this today.

**Comment by ksuprynowicz** [comment]
It seems that the issue is caused by Vircadia being built without optimization flag by default and gcc assumes -O0.
Building with different compiler flags increases performance up to 9 times:
```
export CXXFLAGS="-march=native -mtune=native -O3 -fPIC"
export CFLAGS="-march=native -mtune=native -O3 -fPIC"
```
Of course -march=native -mtune=native is not suitable for release, but it's perfect for local build.
More aggresive optimization flags coming soon

**Comment by ksuprynowicz** [comment]
Merging PR 1424 fixed this.
