### ISSUE TITLE
WebRTC connection not being established on public domain server

### ISSUE THREAD

**Issue by ctrlaltdavid** [vircadia/vircadia#1396]
Messaging signals are exchanged but the WebRTC data channel isn't established.

It looks like the public network addresses aren't included in the signaling messages.
- Compare with using domain server on (a) localhost and (b) over a local network.
- Network configuration in the domain server?
- DTLS missing in the domain server?
- ...?

**Comment by digisomni** [comment]
This has been solved with the usage of SSL certificates.
