### ISSUE TITLE
LOD Problems in 0.86.0

### ISSUE THREAD

**Issue by zontreck** [vircadia/vircadia#14]
In version 0.86 if you tab out, LOD will slowly decrease over time. Tabbing back in often causes content to flicker in and back out. 

Simplified UI contains some fixes that apparently fix this issue.

**Comment by zontreck** [comment]
Here's the section of the SimplifiedUI code that changes the LOD. This might be the segment that fixes it. 

```js
::Line 700 [scripts/simplifiedUI/ui/simplifiedui.js]

var oldAutomaticLODAdjust;
var oldLODAngleDeg;
var SIMPLIFIED_UI_AUTO_LOD_ADJUST = false;
var SIMPLIFIED_UI_LOD_ANGLE_DEG = 0.248;
function modifyLODSettings() {
    oldAutomaticLODAdjust = LODManager.automaticLODAdjust;
    oldLODAngleDeg = LODManager.lodAngleDeg;

    LODManager.automaticLODAdjust = SIMPLIFIED_UI_AUTO_LOD_ADJUST;
    LODManager.lodAngleDeg = SIMPLIFIED_UI_LOD_ANGLE_DEG;
}
```

**Comment by zontreck** [comment]
It appears the call to `LODManager.automaticLODAdjust` might be what changes the flickering in and out. Although i'm not 100% sure what `LODManager.lodAngleDeg` does.

**Comment by kasenvr** [comment]
This appears to be the result of simply setting manual or auto LOD, so the wider question is if and how we should make the LOD setting more available (in the graphics settings perhaps?) until such a time that we can make the auto LOD system further improved? Also, should the LOD be auto set to auto or manual? Keeping in mind the wind variety of performance for various devices.

**Comment by digisomni** [comment]
#1129 at least ensures that the LOD target is "infinity" by default, essentially disabling it.

**Comment by digisomni** [comment]
This effectively solved the problem, further LOD improvements should probably go in an issue specific to that.
