### ISSUE TITLE
Graphics are horribly mangled on AMD GPUs

### ISSUE THREAD

**Issue by ksuprynowicz** [vircadia/vircadia#1409]
Vircadia doesn't seem to work correctly on AMD GPUs:
![vircadia_amd](https://user-images.githubusercontent.com/11568651/136947267-c2701da5-18bc-4bae-8b63-81bffd13c532.png)
![vircadia_amd2](https://user-images.githubusercontent.com/11568651/136947432-d90e11bc-85f9-4d46-8d54-79e39888ff5e.png)
Here are the logs from a system with Windows 10 and Radeon Rx 560 4 GB:
[vircadia-log_2021-10-12_04.30.51.txt](https://github.com/vircadia/vircadia/files/7329584/vircadia-log_2021-10-12_04.30.51.txt)

**Comment by JulianGro** [comment]
Literally created a label just for these guys

**Comment by JulianGro** [comment]
Rather an update would be worth trying. The log says that version `21.9.2 30.0.13017.5006` is used, and version ` 21.10.2  30.0.13025.5005` is available from AMD. https://www.amd.com/en/support/graphics/radeon-500-series/radeon-rx-500-series/radeon-rx-560

**Comment by JulianGro** [comment]
Since ksuprynowicz has concerns that this might be a longer standing issue, I will reinstall Windows and check it out.

**Comment by ksuprynowicz** [comment]
Thank you! A friend tried newer drivers but it didn't work either

**Comment by JulianGro** [comment]
Oh somehow I missed than when commenting.
It should be in `%AppData%/../Local/Vircadia/`. Just delete the shader folder. I cannot imagine the KTX cache causing that for two people simultaniously but not for me.

**Comment by JulianGro** [comment]
@makitsune I notice you guys have the same issue. Might be good to share any info we have. You can see all the driver versions that have this issue that we know here.

**Comment by CheesecakeCG** [comment]
I am also having this issue with driver version `30.0.13025.100` and Adrenalin version 21.10.1 on an RX460.

**Comment by JulianGro** [comment]
Thanks, that is a known broken driver version. Adrenalin 21.5.2 seems to be the newest working version.

**Comment by CheesecakeCG** [comment]
Is it all versions after 21.5.2 that are broken? I think I must've misread the wiki, sorry.

**Comment by mrkcdf** [comment]
Current AMD Adrenaline driver is 22.*.* - is this still an issue with the major update?

**Comment by donataskairys** [comment]
I can confirm it is still the issue with the latest 22... AMD driver.

**Comment by ksuprynowicz** [comment]
I believe that forcing OpenGL 4.1 could be worth trying as a stopgap fix for this issue until I get Vulkan version running.
