### ISSUE TITLE
Steamvr streaming content is dark

### ISSUE THREAD

**Issue by lymluck** [vircadia/vircadia#1413]
During HTC vive focus3 streaming, the content of vircadia screen is dark，but vrchat is normal.

1. vircadia is dark
<img width="1752" alt="1634395148(1)" src="https://user-images.githubusercontent.com/11848829/137591833-29837f9d-2cc2-42e7-a956-8e45910e43ba.png">

2. vrchat is normal
<img width="1727" alt="1634396858(1)" src="https://user-images.githubusercontent.com/11848829/137592479-0306c4fe-3500-407c-8f1e-3f592bc8f8c9.png">

**Comment by lymluck** [comment]
Oculus quest2，the screen content is also normal

**Comment by lymluck** [comment]
> I assume this might just "unfinished" in the OpenVR plugin. It just displays what is rendered for the head mounted display. To fill up the screen it would need to either crop the image (which VRChat seems to do), or render more (which VRChat also seems to do when looking at that screenshot).

> I think vircadia adapts to oculus Quest 2, but not vive focus3. How do you adapt?

> The Oculus plugin might have this implemented better. Could you provide a screenshot from the Oculus Quest 2 you are saying looks fine?

> Sorry, I can't provide the VR real-time content of oculus Quest 2, because during streaming, steamvr does not display the real-time VR view, but only the home page of steamvr, which is different from vive focus3.

> Also I think there is some settings in the display menu for this kind of stuff. At least you should be able to choose between displaying left or right eye.

Yes, there are some settings. I've tried them all, but they don't work.

**Comment by Wishdream** [comment]
Heya! I can confirm this is happening with SteamVR.
I'm using the Quest 2 through SteamVR using ALVR and it's immediately darker than normal.

I don't have access to the Oculus server but I am guessing this is an unfinished OpenVR plugin likely. Not terribly sure what else.
![image](https://user-images.githubusercontent.com/4660711/141693114-2e2ddbd8-2c7b-4cbf-b406-eda59b7786cc.png)

**Comment by JulianGro** [comment]
By the way, are you @Wishdream and @lymluck using Nvidia cards?
https://github.com/vircadia/vircadia/issues/643 Maybe this issue isn't specific to Linux anymore.

**Comment by Wishdream** [comment]
> 
> 
> By the way, are you @Wishdream and @lymluck using Nvidia cards? #643 Maybe this issue isn't specific to Linux anymore.

Yeah, a GTX 1660 Super. It's possible it's an NVIDIA thing.
