### ISSUE TITLE
SSL cert management should have automation (ACME) and ability to upload custom certs through web.

### ISSUE THREAD

**Issue by digisomni** [vircadia/vircadia#1432]

**Comment by ctrlaltdavid** [comment]
Perhaps also define root filename with an environment variable.

**Comment by ctrlaltdavid** [comment]
An environment variable may not be sufficient, e.g., for the case where there are multiple domains running on the server. It may be better to use domain server settings fields, instead.

**Comment by digisomni** [comment]
Updated the title to reflect this.

**Comment by digisomni** [comment]
Completed.
