### ISSUE TITLE
Can I create a new camera？

### ISSUE THREAD

**Issue by kill6810** [vircadia/vircadia#1455]
Can I create a new camera for live viewing

**Comment by ksuprynowicz** [comment]
Did you try spectator camera app available in community apps? (+More button in game will dosplay list of applications that can be installed)
It's VR only, but does exactly this and is perfect for streaming.

**Comment by kill6810** [comment]
> Did you try spectator camera app available in community apps? (+More button in game will dosplay list of applications that can be installed) It's VR only, but does exactly this and is perfect for streaming.

Are you talking about community apps in VR scene  or where?

**Comment by ksuprynowicz** [comment]
Community apps can be installed using "More..." button:
![more](https://user-images.githubusercontent.com/11568651/141846801-f7ffac90-1d35-4be0-bc71-54fc06940778.png)
In VR it's on your tablet.

**Comment by kill6810** [comment]
> Community apps can be installed using "More..." button: ![more](https://user-images.githubusercontent.com/11568651/141846801-f7ffac90-1d35-4be0-bc71-54fc06940778.png) In VR it's on your tablet.

Thank you. How can I output the picture to OBS?

**Comment by ksuprynowicz** [comment]
When you start Spectator Camera while in VR, you have to click it's icon on your tablet and switch VR preview to camera preview. Then camera view will display in Desktop window and you can capture it with OBS.

**Comment by kill6810** [comment]
> 当您在VR中启动观众摄像机时，您必须在平板电脑上点击它的图标将VR e月刊预览到摄像机预览。然后视图将显示在桌面窗口中，您可以使用OBS电视它。Please tell me how to switch camera preview in VR view

**Comment by kill6810** [comment]
> When you start Spectator Camera while in VR, you have to click it's icon on your tablet and switch VR preview to camera preview. Then camera view will display in Desktop window and you can capture it with OBS.

Please tell me how to switch camera preview in VR view？Thank you.
