### ISSUE TITLE
Interface's --scripts option doesn't seem to work

### ISSUE THREAD

**Issue by daleglass** [vircadia/vircadia#1460]
The option takes a path, but never seems to pass it down to the scripting engine, so it doesn't seem to actually have an useful effect.

**Comment by Penguin-Guru** [comment]
Related to https://github.com/vircadia/vircadia/issues/1461

I think it would be good to consider whether there is any functionality we want this to perform that is distinct from the other script parameters. If not, we could simply remove this. The name is nice and short but it is also very ambiguous.

**Comment by JulianGro** [comment]
Probably the same issue as https://github.com/vircadia/vircadia/issues/827 ?

**Comment by Penguin-Guru** [comment]
No, the code for `--scripts` literally doesn't seem to be fully implemented. My pull request should hopefully fix all the other issues, but nobody has confirmed that yet.

**Comment by JulianGro** [comment]
Issue #827 describes that most command line options don't work on Linux.
If `--scripts` isn't implemented then yeah that is a different issue.

**Comment by Penguin-Guru** [comment]
Here is an overview of what I changed (though a bit out of date now) from a user's perspective.

https://github.com/vircadia/vircadia-dev-docs/issues/5
