### ISSUE TITLE
Short freezes on Linux

### ISSUE THREAD

**Issue by ksuprynowicz** [vircadia/vircadia#1462]
When running Interface on Linux, I encounter short freezes about every 10 seconds. It's very visible in the Hub domain when walking. I'm not sure how to diagnose it. Is there a way to log timing/performacne statiscics for every frame? I've seen some timing loggin options in Developer tab, but I don't know where the data is saved. Freezes are about 500 ms long.

**Comment by JulianGro** [comment]
See comment https://github.com/vircadia/vircadia/issues/898#issuecomment-860302606
That benchmark should still be operational.
