### ISSUE TITLE
Oculus Control Issues - Needing to press the thumbstick to move where it shouldn't be

### ISSUE THREAD

**Issue by Wishdream** [vircadia/vircadia#1466]
When moving, in order to move and rotate, I needed to press down on the thumbstick. Is this intentional or a bug? Might be left over with movement from Vive wands.

**Device:** Oculus Quest 2
**Operating System:** Windows 10
**Connection Mode:** ALVR + SteamVR
- A note, ALVR is an open-source implementation of Desktop VR to Quest VR streaming and *skips Oculus software entirely*, I have no Oculus software installed on my PC

Not terribly sure if the same applies to Air Link and Virtual Desktop users that use SteamVR for Vircadia and not the Quest Link

**Comment by JulianGro** [comment]
Yeah we still use legacy OpenVR controls. So my guess would be that the legacy -> ALVR conversion isn't very good. You can change your keybindings in SteamVR.

**Comment by Aitolda** [comment]
>Not terribly sure if the same applies to Air Link and Virtual Desktop users that use SteamVR for Vircadia and not the Quest Link

I have no had this issue with link, but have not tried lately with Virtual Desktop.  I believe it was working fine last time I used it (VD) but it's been a while.

**Comment by Wishdream** [comment]
> > Not terribly sure if the same applies to Air Link and Virtual Desktop users that use SteamVR for Vircadia and not the Quest Link
> 
> I have no had this issue with link, but have not tried lately with Virtual Desktop. I believe it was working fine last time I used it (VD) but it's been a while.

If you happen to try it, can you try launching Vircadia through SteamVR than using Oculus? That'll help with determining if it's definitely legacy OpenVR input. I have a sneaking suspicion that it is and definitely linked to the issue above.
