### ISSUE TITLE
My avatar is strange after the neuron device is connected

### ISSUE THREAD

**Issue by Onparting** [vircadia/vircadia#1472]
![image](https://user-images.githubusercontent.com/48120877/143161615-b64812e3-712f-4975-aa43-e1e8eea0af97.png)

**Comment by Onparting** [comment]
This is the case in neuron applications
![image](https://user-images.githubusercontent.com/48120877/143162292-0946939a-d465-4f24-a3f5-78d76364aad6.png)

**Comment by Aitolda** [comment]
Just wanted to confirm that they have enabled the perception on the control tab as well as tried the calibration page, but no additional options were given after selecting it.
