### ISSUE TITLE
latest Appimage on linux fails with "undefined symbol: hb_ot_tags_from_script_and_language"

### ISSUE THREAD

**Issue by thearthur** [vircadia/vircadia#1483]
Running the latest Appimage on Archlinux like this:

./Vircadia-x86_64_v2021.1.3-Eos.AppImage   

gives this output

./Vircadia-x86_64_v2021.1.3-Eos.AppImage: symbol lookup error: /usr/lib/libfreetype.so.6: undefined symbol: hb_ot_tags_from_script_and_language

Is libfreetype included in the app image or does it depend on the one installed on the system?

**Comment by Penguin-Guru** [comment]
You can fix this by downgrading your system libfreetype. Julian said he fixed this for the last release but somehow missed it in the AppImage. My understanding is that it will be included in the AppImage next release, which is supposedly due in the next couple days.

**Comment by JulianGro** [comment]
https://appimage.moto9000.moe/release/Vircadia-x86_64_v2021.1.3-build2-Eos.AppImage

**Comment by JulianGro** [comment]
New release is out that should fix the problem.
