### ISSUE TITLE
Move bookmarks.json from local appdata to roaming appdata

### ISSUE THREAD

**Issue by thoys** [vircadia/vircadia#150]
Move the `bookmarks.json` file from local app data to roaming. It can be better found in local app data and would be easier to backup since local app data mainly contains cache and logs. Roaming app data should be transferrable between installs and is probably more commonly synced for network users.

Be sure to have a fall back mechanism, in case there is a bookmarks.json found in Local appdata but not in Roaming, then copy it over first. If one exists already in roaming, then ignore the one from local appdata.

**Comment by daleglass** [comment]
still a thing
