### ISSUE TITLE
Can vircadia achieve the same particle effect as in unity?

### ISSUE THREAD

**Issue by Joyous666** [vircadia/vircadia#1504]

**Comment by daleglass** [comment]
I don't know what particle effect you mean. Examples would help.

**Comment by Joyous666** [comment]
![unity](https://user-images.githubusercontent.com/95261439/144220071-2fa73363-2709-4161-8254-51c001500af1.png)
![vircadia](https://user-images.githubusercontent.com/95261439/144220089-4ad907f5-1cbd-41a5-8c08-df764a874e17.png)
Like the two pictures above, they respectively show the tailing properties of particles in unity and vircadia. Unity can set the mode, width, color and other properties of the tailing. Vircadia can only set whether the tailing is selected (whether it is selected or not, there is no difference. ).
So, can the particle tailing in vircadia achieve the same effect as unity? How can it be achieved?

**Comment by SilverfishVR** [comment]
looks like something like sub-emitters, we don't really have that but what you can do is have multiple emitters and than move those so they leave a trail, this example attaches emitters to animated bones on a (invisible) model but you could also move them by script or physics
![vircadia-snap-by-Silverfish-on-2021-12-01_21-56-54](https://user-images.githubusercontent.com/53531160/144313295-ab443b00-2e83-476a-9123-3e8300c0bd57.gif)

in a domain where you have create rights, load this: http://silverfish-freestuff.s3.amazonaws.com/NY_Particle_effect/newYearParticle.json
"Create->Import entities from a url" or just drag the url onto the interface window.
