### ISSUE TITLE
Interface hangs indefinitely when switching domain due to script engine not killing all scripts before leaving.

### ISSUE THREAD

**Issue by digisomni** [vircadia/vircadia#1512]
Interface will hang until it crashes with this message constantly being outputted:

`[12/04 17:50:25] [WARNING] [hifi.scriptengine] Script Engine has been running too long, aborting: "about:Entities 4"`

I expect there is a possible workaround by finding the offending script and removing or modifying it. However, we're not sure which script it is for now (or if that is the exact cause).

This can be reproduced by going to the domain "Christmas" by GeorgeDeac, letting it load, then trying to switch to another Domain.

**Comment by digisomni** [comment]
The accused script: https://transmissiongate.com/hifi/christmas/santaride.js?e1

**Comment by ctrlaltdavid** [comment]
It's possible that the following PR fixes this issue: https://github.com/vircadia/vircadia/pull/1200
(Needs testing.)
