### ISSUE TITLE
macOS DMG installer - lost improvements

### ISSUE THREAD

**Issue by Steve-Pruneau** [vircadia/vircadia#1515]
The improvements in the macOS installer for which CtrlAltDavid invested considerable effort, are no longer present in 2022.1.0-Selene.

These apps are presented for install and should not be there:
- nitpick
- Sandbox

The HiFi Screenshare app is embedded in the app archive, which makes the app 533mb fatter with useless data.

~ ~ ~
![macOS_2022-1-0-Selene_1](https://user-images.githubusercontent.com/74510038/144723740-59af467b-02d7-4f28-af42-4bf5ae71dbfc.jpg)
![macOS_2022-1-0-Selene_2](https://user-images.githubusercontent.com/74510038/144723742-7193b9fb-f37f-43b9-bd69-d9e7ec4616f4.jpg)
![macOS_2022-1-0-Selene_3](https://user-images.githubusercontent.com/74510038/144723743-2923df63-875c-41b7-b0b7-3187a349a5d3.jpg)

**Comment by digisomni** [comment]
Yeah, that's because the build was generated as a non-client_only build. This isn't a regression, we just have to get the build working again on our local Mac systems so we can generate a client_only build again.
