### ISSUE TITLE
2022.1.0-Selene will not launch on macOS 11.6 "Big Sur"

### ISSUE THREAD

**Issue by Steve-Pruneau** [vircadia/vircadia#1516]
The 2022.1.0-RC launches successfully on macOS 11.6. https://athena-public.s3-eu-west-3.amazonaws.com/master/393/Vircadia-393-aabcdea-.dmg

Production release of the Interface for macOS will not complete the launch process. This implies a difference in the build process. We should use the same build process for RC and Production.

**Comment by digisomni** [comment]
Yes, we should. I don't think I intended to do that, can't quite remember what the difference between the two was.

**Comment by JulianGro** [comment]
This is exactly the issue we have had on macOS for ages now and I am working on.
And also the issue which prompted me to suggest releasing two builds for this release.
