### ISSUE TITLE
Trying to duplicate a locked entity duplicates unlocked children.

### ISSUE THREAD

**Issue by glenalec** [vircadia/vircadia#1517]
In create, trying to duplicate  an entity that is locked results in a different entity being duplicated to the one selected.

**Comment by AleziaKurdis** [comment]
I will check this. I thought that we couldn't duplicate a locked entity.

**Comment by AleziaKurdis** [comment]
I have retested the duplicate functionality with the 3 ways: 
- Edit > Duplicate
- CTRL-D
- ALT + Move using the selection tool

It doesn't duplicate if the selection has a locked entity.
I get the rejection sound feedback, and the entity list didn't get increased (even after a refresh) as expected.

**Please, provide exact step to reproduce for that issue.**

**Comment by glenalec** [comment]
Replicated it. It turns out it is a parenting issue. I noticed it when manipulating a zone with a child light entity, but just also replecated it with two shape entities:

1) Create shape (I left it a cube)
2) Create another shape (I made it a sphere, so I could visually see what I was doing!)
3) Parent the sphere to the cube (ie: cube is parent, sphere is child)
4) Lock the cube (left the sphere unlocked).
5) Duplicate the cube>
Result: child sphere is duplicated.

Tried with the locked sphere, and no duplication occurred, so it appears that if you try to duplicate a locked object, it instead duplicates any unlocked entities that the object is parent of. Will update the name of the bug report to reflect this.

Thanks.

**Comment by AleziaKurdis** [comment]
Fixed with PR#1523
It's no more possible to duplicate anything that contain locked entities in the selection of in the children.
This was causing other issues too.

**Comment by glenalec** [comment]
Yup. Still an issue on latest compile of master on current Debian/testing.

On Dale's suggestion I tried shift-clicking, which worked, and also Ctrl-
clicking which also worked, so it is just raw-clicking that isn't getting 
through (mouseover detection also seems fine).
