### ISSUE TITLE
Feature Request: "Add children" message to json export.

### ISSUE THREAD

**Issue by Aitolda** [vircadia/vircadia#1520]
Sometimes it's easy to forget things like material entities (children) and sub meshes when exporting an object as json.  I propose that on export, interface will detect if that object(s) has any children attached, and if so a message will pop up "Add children to export?" and quickly select these (if you select yes) before spitting out the json.

Another possibility is a simple checkbox that includes additional options, although I see this as less useful.
Children
Parents
or more specifics
Attached Materials
References, etc.

Although I think children would be enough for general use.

**Comment by AleziaKurdis** [comment]
It can be possible to do it at the create app level. It would do a "add children to selection" before proceeding to the export.
but this will goes according the range in the entity list.
I suppose we can do this stronger by searching on a larger range (but some not loaded entities might stay missing)
