### ISSUE TITLE
GHA fails to extract MacOS SDK.

### ISSUE THREAD

**Issue by digisomni** [vircadia/vircadia#1522]

**Comment by JulianGro** [comment]
This is an issue with the server providing the package.
For my builds I now use https://data.moto9000.moe/vircadia_packages/macOS_SDK10.12.4.tar.xz which I intend to have in the next PR.

**Comment by digisomni** [comment]
This works fine on my local Mac and had originally worked on GHA when I made the change to fix it. I expect something changed with the VM. https://github.com/actions/virtual-environments/commit/4638404b13b4dbd3d9f37614973acf32f7368ba1#diff-7a1606bd717fc0cf55f9419157117d9ca306f91bd2fdfc294720687d7be1b2c7
![image](https://user-images.githubusercontent.com/69767640/145335588-dd18b12a-d2f9-46d3-815f-4e574b69bf00.png)
