### ISSUE TITLE
metallicFactor in GLB materials is ignored

### ISSUE THREAD

**Issue by ksuprynowicz** [vircadia/vircadia#1529]
When GLB model with metallicFactor set to 1 is added to world, it renders incorrectly:

![vircadia-snap-by-X74hc595-on-2021-12-10_18-23-50](https://user-images.githubusercontent.com/11568651/145616853-a475dfc8-ce37-4d52-b8b0-f27e83b5b0be.jpg)

This is how it is rendered by Babylon JS in comparison:

![sphere](https://user-images.githubusercontent.com/11568651/145617217-6116541f-4c2a-4053-9922-3263d6a4b883.jpg)

Upon closer inspection the darker part of the sphere in Vircadia renderer does reflect environment slightly, so the problem is probably assosciated with metallicFactor, and not roughnessFactor.

**Comment by ctrlaltdavid** [comment]
See also: https://github.com/vircadia/vircadia/issues/909
