### ISSUE TITLE
How can javaScript become "API"?

### ISSUE THREAD

**Issue by Onparting** [vircadia/vircadia#1534]
How can I make the script global and can use the methods in the script at any time 

Maybe it can be said to be JS writing API

**Comment by JulianGro** [comment]
You are mixing up terminology a bit here, so I am not sure what exactly you are asking.

If you are asking about a running script interacting with a running script (API):
Someone correct me if I am wrong, but I don't think there is a proper way to have running scripts interact with each other. You could have one script wait for a trigger and have the other script create that trigger (For example have a script waiting for a cube to be created and have a different script create that cube).

If you are asking about using a method in multiple scripts without having to add the whole method to every one of them:
This is Javascript specific. You can write a library of methods, load that library into a script, and then call the methods when you need them.

**Comment by ctrlaltdavid** [comment]
Scripts can communicate with each other via the `Messages` API: https://apidocs.vircadia.dev/Messages.html
There are also `Script.callEntityScriptMethod()`: .https://apidocs.vircadia.dev/Script.html#.callEntityScriptMethod
And `Entities.callEntityClientMethod()`, `.callEntityMethod()`, and `.callEntityServerMethod()`: https://apidocs.vircadia.dev/Entities.html#.callEntityClientMethod

**Comment by Onparting** [comment]
Thank you for your answer, my problem has indeed been solved
