### ISSUE TITLE
Revisit replacing QHash.insertMulti() calls by QHash.insert() made in PR1468

### ISSUE THREAD

**Issue by ctrlaltdavid** [vircadia/vircadia#1535]
For example, packing of models' blendshapes is probably broken because `insert()` overwrites any existing item with the same key, but blendshape mappings can have entries with duplicate keys. Similar issue for other changes, also.

PR1468: https://github.com/vircadia/vircadia/pull/1468

QHash.insertMulti(): https://doc.qt.io/qt-5/qhash-obsolete.html
Instead of replacing `QHash.insertMulti()` with `QHash.insert()`, `QHash` should probably be replaced with `QMultiHash` for affected occurrences.

**Comment by ctrlaltdavid** [comment]
In particular...

ModelPackager.cpp and FST.cpp:
```
        QVariantHash blendshapes;
        blendshapes.insertMulti("BrowsD_L", QVariantList() << "BrowsDown_Left" << 1.0);
        blendshapes.insertMulti("BrowsD_R", QVariantList() << "BrowsDown_Right" << 1.0);
        ...
```
has been replaced with
```
        QVariantHash blendshapes;
        blendshapes.insert("BrowsD_L", QVariantList() << "BrowsDown_Left" << 1.0);
        blendshapes.insert("BrowsD_R", QVariantList() << "BrowsDown_Right" << 1.0);
        ...
```

FSTReader.cpp:
- Lines 37 - 48 have 3 x `insertMulti()` replaced by `insert()` on `QVariantHash` values.
- `static void fixUpLegacyBlendshapes(QVariantHash & properties)` should probably have the parameter type changed to `hifi::VariantMultiHash`.

FSTReader.h:
- `static ModelType predictModelType(const QVariantHash& mapping);` probalby needs the parameter type changed to `hifi::VariantMultiHash`.

**Comment by shocktail39** [comment]
[steve_hocktail.tar.gz](https://github.com/vircadia/vircadia/files/7770367/steve_hocktail.tar.gz)

hello, ctrlaltdavid asked me in the discord to post some relevant findings.  attached to this comment is an archive of my model and fst file.  if you equip it and go into third person on the main branch, you'll see that only the right tail bone is having its flow settings loaded, while the middle and left ones are instead being given the default "floppy" flow settings.

by switching around the lines in the fst file, i have discovered that if there are multiple lines with the same key, only the last one will be properly loaded.  for example, if you cut-paste the "TailLeft" line to be at the bottom, then the left tail bone will work properly while the middle and right ones go floppy.

multiple equivalent keys used to all load, and after checking out a few old commits, i have narrowed down which commit changed this behavior: it is the one in question in this issue.

**Comment by daleglass** [comment]
Okay, I'm working on a PR to fix it.
