### ISSUE TITLE
Address Settings > General > Privacy setting

### ISSUE THREAD

**Issue by ctrlaltdavid** [vircadia/vircadia#155]
No longer send to High  Fidelity … send somewhere else?
Should be disabled by default?

**Comment by kasenvr** [comment]
I believe it is already disabled.

**Comment by daleglass** [comment]
Discussion at dev meeting: unclear if this is on or off by default, needs looking at

**Comment by kasenvr** [comment]
Confirmed this is off.

**Comment by kasenvr** [comment]
This is off, it just says High Fidelity still, we can change the words to Vircadia and maybe disable the checkbox so that people understand that this will not be activated under any circumstances without prior knowledge.

**Comment by daleglass** [comment]
This was fixed by #1071, closing.
