### ISSUE TITLE
Server host set-up guide unclear

### ISSUE THREAD

**Issue by light42** [vircadia/vircadia#1550]
Hello, could I get the straight-forward guide on how to setup domainserver, metaverseserver, and metaverseserver dashboard on my server?

I tried, and I still don't know which should be connected to which, and what config should I modify. The guide is hard to understand, and spread all over the place.

**Comment by daleglass** [comment]
Well, that's a bit overly general and it's hard for a developer to get into the new user mindset properly. Perhaps you could help though. Could you try to start reading the documentation from the beginning and tell us exactly where you get stuck, or where you run into trouble?



But, my best guess so far: what you want is a domain server. You don't need the metaverse server or anything related to it, that's effectively an user account database. You don't need to host your own to run a server in most circumstances.

**Comment by light42** [comment]
> Well, that's a bit overly general and it's hard for a developer to get into the new user mindset properly. Perhaps you could help though. Could you try to start reading the documentation from the beginning and tell us exactly where you get stuck, or where you run into trouble?
> 
> But, my best guess so far: what you want is a domain server. You don't need the metaverse server or anything related to it, that's effectively an user account database. You don't need to host your own to run a server in most circumstances.

I actually need everything to be hosted on my own server.

What I currently understand from the documentation is, I need to tweak the metaverse url in dashboard so that it would pointed at my own metaverse server, and then I need to change the url in header file of domain server source to point it to my own dashboard.

The part I am truly struggling with is with metaverseserver deployment(localhost:9400), it doesn't show that much of information in Logs, and there's no info of which api I could use to test the server(I must dig deep into routers to find some api).

When I tried to change metaverse url on my dashboard from https://metaverse.vircadia.com/live to localhost:9400, the dashboard can't detect it.

**Comment by light42** [comment]
> > Well, that's a bit overly general and it's hard for a developer to get into the new user mindset properly. Perhaps you could help though. Could you try to start reading the documentation from the beginning and tell us exactly where you get stuck, or where you run into trouble?
> > But, my best guess so far: what you want is a domain server. You don't need the metaverse server or anything related to it, that's effectively an user account database. You don't need to host your own to run a server in most circumstances.
> 
> I actually need everything to be hosted on my own server. And I'm quite confident my server could handle the workload.
> 
> What I currently understand from the documentation is, I need to tweak the metaverse url in dashboard so that it would pointed at my own metaverse server, and then I need to change the url in header file of domain server source to point it to my own dashboard.
> 
> The part I am truly struggling with is with metaverseserver deployment(localhost:9400), it doesn't show that much of information in Logs, and there's no info of which api I could use to test the server(I must dig deep into routers to find some api).
> 
> When I tried to change metaverse url on my dashboard from https://metaverse.vircadia.com/live to localhost:9400, the dashboard can't detect it.

Update: Metaverse dashboard deployed on my server could finally detect the metaverserver, after some tweaking. But I still can't login and register(the dashboard doesn't show any response at all)
