### ISSUE TITLE
Colors between pure RGB appear different when using diffuse texture vs color picker

### ISSUE THREAD

**Issue by Aitolda** [vircadia/vircadia#1563]
Importing models (from blender) using the built-in color picker rather than a diffuse texture are incorrect when using anything other than a pure RGB value (255,0,0)(0,255,0)(0,0,255). That is to say, pure red, pure blue, and pure green will show correctly, however in between colors like Turquoise, Gold, and Purple will not. This problem exists for both FBX and GLB however the FBX diffuse textures appear slightly less accurate (darker) with a diffuse texture.

[Example Json](https://aitolda.s3.amazonaws.com/Vircadia/test/ColorProblem/ColorProblem.json)

https://aitolda.s3.amazonaws.com/Vircadia/test/ColorProblem/ColorProblem.jpg

**Comment by AleziaKurdis** [comment]
Observation: 
If the albedo is set on the model (fbx or gftl) we have this color degradation. 
if we set it through a material definition (.fst or material entity), the color is ok.
