### ISSUE TITLE
Clipboard.importEntities() can interfere with the main event loop

### ISSUE THREAD

**Issue by ctrlaltdavid** [vircadia/vircadia#159]
It uses Octree::readFromURL() which uses a QEventLoop, running on the main thread.

When fixed, also update the JSDoc to say the first parameter may be a URL or filename and path. URLs are already supported but probably shouldn't be encouraged until this bug is fixed.

**Comment by daleglass** [comment]
David: it locks up the UI until the import is completed

**Comment by daleglass** [comment]
still needs improving
