### ISSUE TITLE
Vircadia Domain Server "Visit in VR" button uses hifi.place with an internal server error.

### ISSUE THREAD

**Issue by IceTheCoyote** [vircadia/vircadia#1591]
A PR may be needed to fix this issue. But when using the domain-server's web panel you see a button that should let you visit your world in VR but it uses hifi.place which might of not been carried over. I actually showed this in the today's developers meeting.

**Comment by digisomni** [comment]
A possible alternative might be to have this button go to the web interface when we have v1.0 of that live. :)

**Comment by vijay-prema** [comment]
This is mentioned in https://docs.vircadia.com/host/invite-users.html?highlight=link#invite-your-friends
But yeah it doesnt work.  I was hoping to have a some kind of "meeting link" that new people can use to join me

**Comment by digisomni** [comment]
@namark can we just hide the button for now?

**Comment by namark** [comment]
@digisomni I didn't test, but pretty sure this should do it https://github.com/vircadia/vircadia/pull/1595
