### ISSUE TITLE
Graphics settings/rendering effects -> Local lights, fog, bloom can't be selected

### ISSUE THREAD

**Issue by daleglass** [vircadia/vircadia#1594]
If graphics is set to custom, and rendering effects to "enabled", the last 3 options can't be clicked.

**Comment by ctrlaltdavid** [comment]
I'm getting the same problem running PR1200 which was built against master 21 days ago.

**Comment by digisomni** [comment]
![image](https://user-images.githubusercontent.com/69767640/155855897-a078a9e0-782d-4e6f-8b86-01e270999b0e.png)

I do not believe this is an issue as you are not able to turn that on or off separately. It's either they're all on or they're all off.

**Comment by digisomni** [comment]
Feedback from meeting: while this behavior is correct, it's probably bad UX to show users these buttons if they are unable to check / uncheck them, it might confuse them as to why it's always greyed out. We should instead have "Local Lights, Fog, and Bloom" in parentheses next to the rendering mode switch.
