### ISSUE TITLE
Need documentation for server-side scripting

### ISSUE THREAD

**Issue by kasenvr** [vircadia/vircadia#163]
We need server-side scripting specific documentation.

**Comment by ctrlaltdavid** [comment]
Current documentation:
- https://docs.projectathena.dev/script/assignment-client-scripts.html
- https://docs.projectathena.dev/script/server-entity-scripts.html
- Each namespace and class in the API docs lists which script types they're available in.

**Comment by kasenvr** [comment]
Since the documentation exists, there should be an easy way to filter the apidocs to show what is available to the specified scripting context.
