### ISSUE TITLE
There should be a way to disable positional audio per zone, and perhaps normalize it

### ISSUE THREAD

**Issue by daleglass** [vircadia/vircadia#164]
Positional audio is a great feature for VR interaction, but it can be a hindrance during meetings. During a meeting I end up having to adjust people's volume sliders because I want to hear everybody the same, and asking people to "please increase your volume" interferes with the flow of the meeting.

So here's my provisional idea for how this could work:
* Zones get an "Audio" category. Within that category there should be:
* A "constant volume" setting. If enabled, within this zone, distance doesn't change volume.
* A "constant direction" setting. If enabled, everything sounds as coming from the front.
* A "normalize audio" setting. Quiet speakers get their volume boosted. (this should probably be left for later because this likely involves extra complications)

Possible additional settings that could make sense to have, though not necessary for this particular bug:
* A "mute audio" setting that suppresses audio within the zone.
* A "restrict audio to zone" setting that stops audio from being heard by people who are not within the zone.

Users should also get the ability to apply these settings to other users by hand (the way they can control volume). This could be helpful if people want to simulate the effect of such a zone for themselves in any arbitrary location. For instance in an improvised meeting not happening in such a zone, or where multiple people in a domain want to maintain a conversation despite moving far from each other.

A possible side benefit could be performance optimization, which could make sense on domains with few resources. "Constant volume" and "Constant direction" being set should save some processing power, though I don't know if it is going to amount to anything significant.

**Comment by HifiExperiments** [comment]
I think there are already some audio zone settings in the domain server settings page.  those should also be moved into zone entities
