### ISSUE TITLE
The default graphics setting of 'Low' is awful -- it throttles framerate and causes weird motion

### ISSUE THREAD

**Issue by daleglass** [vircadia/vircadia#18]
Setting graphics to 'Low' has two very undesirable effects:

* It caps the framerate
* Flexible objects like Fennec ears start to oscillate when the interface window is not focused

I think the way this setting works is extremely undesirable and causes a very bad first impression. Capping the framerate might make sense in some situations, but I think it should never be done by default -- it creates the impression the interface is much slower than it truly is.

I suggest the following fixes:

* The current 'Low' should be either removed entirely or renamed to something like 'Throttled', or 'Battery saver', and be only chosen by intentional user action.
* The interface should try to select the highest functional graphics setting by default.
* Perhaps there should be some sort of "(safe mode)" flag in some prominent place like the title to indicate that things are set to low as a troubleshooting measure.

**Comment by Aitolda** [comment]
Suggestion from meeting 12-23-2019:

Change "Refresh Rate" to "Target FPS"

-20 fps
-30 fps
-match monitor refresh
-uncapped (experimental)

**Comment by digisomni** [comment]
This will be addressed with further graphics settings reworks, for now at least the tutorial allows one to bypass this issue.
