### ISSUE TITLE
Tutorial in sandbox says to go to welcome

### ISSUE THREAD

**Issue by kasenvr** [vircadia/vircadia#180]
Welcome no longer exists, let's be sure to point new users towards our new hub. :)

**Comment by ctrlaltdavid** [comment]
Wipe all tutorial content and just have links to the following?
- Serverless tutorial.
- The Hub.

**Comment by ctrlaltdavid** [comment]
See https://github.com/kasenvr/project-athena/issues/611

**Comment by HifiExperiments** [comment]
is this still a problem?

**Comment by SilverfishVR** [comment]
The sandbox no longer has any tutorial stuff in it so I guess no
