### ISSUE TITLE
Simplified UI has links to HiFi pages

### ISSUE THREAD

**Issue by ctrlaltdavid** [vircadia/vircadia#181]
For example, the "Contact Support" button opens https://www.highfidelity.com/knowledge/kb-tickets/new

**Comment by kasenvr** [comment]
The emote app is the only thing of note in use there, we have all of the emojis available in the vircadia-content repo.

**Comment by daleglass** [comment]
Dev meeting: simplified UI is still useful, links to hifi should be eliminated
