### ISSUE TITLE
TAA makes things blurry

### ISSUE THREAD

**Issue by ctrlaltdavid** [vircadia/vircadia#185]
"things are blurry because the TAA implementation was never finished but you can turn it off in Developer -> Render I think
"it is on by default in deferred mode because if it worked it would be super helpful.  there was a PR at one point that did most of the work to fix it if someone wants to find it and has access to old PRs...something like “TAA Improvements”

**Comment by kasenvr** [comment]
This was somewhat addressed in the unmerged and closed PR 13246.

**Comment by daleglass** [comment]
I'm told there have been hifi PRs that were trying to address this. We should have those PRs backed up. If anybody needs it, please ask.

**Comment by ctrlaltdavid** [comment]
I had a look the merge-ability of the HiFi PR 3246 that tried to improve./fix TAA into current master.
- Code: github.com/zvork/hifi branch `velgbuf`.
- Initial PR was on 28 May 2018 (i.e., over 2 years ago)
- Last commit was on 1 Dec 2018 (i.e., a year and a half ago)
- There are 123 merge conflicts with current master: camera, overlays, entity renderers, GPU utils, shaders, ...

Not really feasible to merge. Instead, it would probably be better to develop new code on a new branch, perhaps using the old HiFi PR's code for ideas / guidance.

**Comment by daleglass** [comment]
PR still active

**Comment by ksuprynowicz** [comment]
Yes, I think PR has not been merged yet
