### ISSUE TITLE
Create prototype UI framework

### ISSUE THREAD

**Issue by kasenvr** [vircadia/vircadia#191]
Due to the ongoing bug of not having audio devices load with VR (possibly SteamVR specifically?), amongst other audio issues, it would be best to have the first page of the prototype UI that is attached to the tablet to be an audio settings page or a way to make the audio settings come to the forefront (perhaps some basic info + a button that opens the page on the tablet)

Also, generally for when people are not present to guide new users, amongst other things... we should have a discord link (not clickable but rather spelled out) for new users to be able to enter into their browser and reach out.

Furthermore, a chat app should be put into one of these browser based UIs that can be attached and detached to the tablet. This will allow for at the very least the ability to read the chat, see images, and videos.

**Comment by daleglass** [comment]
linked PR
