### ISSUE TITLE
Bottom row of tablet keyboard sometimes hidden

### ISSUE THREAD

**Issue by SilverfishVR** [vircadia/vircadia#194]
Testing the new create tools layout (PR193) I discovered a hint as to why the bottom row of the tablet keyboard is sometimes hidden below the bottom edge of the tablet.
it seems that grabbing the tablet causes the content (or the tablet itself) to rescale a bit, indicated by a slight change in size of the scrollbar.

Reproduce:

1. make sure you are using the tablet keyboard, in settings->general disable: 

 [ ] use virtual keyboard

2. without grabbing the tablet, open create->properties, laser an entity.
3. now grab the tablet and click on a text or number field, only the top few pixels of the bottom row should be visible.

[gif of the bug](https://silverfish-freestuff.s3.eu-north-1.amazonaws.com/TabletKeyboardBug.gif)

**Comment by daleglass** [comment]
dev meeting: needs retesting

**Comment by SilverfishVR** [comment]
yep, still a thing, also tested on the QT update PR (#938) just in case but no dice, when grabbing the tablet causes some slight rescaling that puts the bottom row out of bounds.

**Comment by SilverfishVR** [comment]
I would consider this re-tested no?
