### ISSUE TITLE
Decentralized goto doesn't work correctly with IPv6

### ISSUE THREAD

**Issue by daleglass** [vircadia/vircadia#203]
When decentralized goto is being used on a domain capable of IPv6, the API receives an IPv6 address. However, the domain code itself doesn't actually support IPv6 and only listens on IPv4, so a connection isn't possible.

Here's how I understand it goes:

1. Scripting engine requests https://metaverse.projectathena.io/interim/d-goto/app/ip.json
2. Scripting engine resolves metaverse.projectathena.io. It has both an IPv4 and IPv6 address.
3. Since the scripting engine runs on a host capable of IPv6, it makes an IPv6 connection.
4. The metaverse.projectathena.io server looks at what the other end of the connection is -- and it's an IPv6 address.
5. This address can't be connected to, because domain-server doesn't listen on IPv6.

Possible fixes:

1. Remove the IPv6 address from metaverse.projectathena.io. This is a hack, but will work.
2. Implement IPv6 support in the domain server.

However, people with IPv4 exclusive connections won't be able to reach an IPv6 address anyway, so the decentralized goto really needs to handle both types of addresses at once and choose the right one depending on what the user is capable of connecting to.

So I think the following changes will be needed:

1. Implement an API in the domain-server that allows it to report its canonical address to a script (probably both in IPv4 and IPv6 varieties)
2. Get that data with a script
3. Have the decentralized goto use the most appropriate one for the user

**Comment by kasenvr** [comment]
This has been solved (for now) by removing IPV6 support from the Cloudflare front-end to the metaverse API route.

**Comment by digisomni** [comment]
The metaverse API will be in charge of this fairly soon, as such IPV6 support can be addressed there as well as on the domain-server side as a separate issue.
