### ISSUE TITLE
Allow relative paths in JSON

### ISSUE THREAD

**Issue by SilverfishVR** [vircadia/vircadia#204]
It would be nice to able to use relative paths in JSON's (for loading assets)? If I want to move my assets or even rename a S3 bucket I have to edit the JSON of all the stuff that is comprised of more than just a model.

If I make something cool like a sippy bird or some nice materials, anyone who wants to move it to their own hosting will have to update the JSON to reflect the new paths.

In scripts I can get the path and go from there, in FST's I can just use a relative path, but from JSON it seems to require absolute path. I guess that is why, even though all of the assets for the serverless tutorial is in my install folder, it still loads from content.highfidelity.com, A new JSON would have to be generated that has all of my local file paths in it.

**Comment by digisomni** [comment]
This has been implemented in PR #586, #672, and #694. If there are further missing properties or issues then we should open a new issue regarding that. :)
