### ISSUE TITLE
Ctrl-drag duplicate entity tree can leave child entities parented to original entity

### ISSUE THREAD

**Issue by ctrlaltdavid** [vircadia/vircadia#207]
Occurred in TheHub when duplicating teleporter content: Box entity as parent (for image) with Zone and Text entities as children. When Ctrl-drag Box entity, children are duplicated but one or both are left parented to the original entity and at their original locations.

It seemed like they started to move but then snapped back to their original locations (and, presumably, parenting).

Note: Couldn't repro on localhost Sandbox.

**Comment by digisomni** [comment]
Clarification: Child entities of the new duplicated entity can end up parented to the original parent entity instead of the new duplicated one.
