### ISSUE TITLE
textEffectThickness property: outlineFill is not working.

### ISSUE THREAD

**Issue by AleziaKurdis** [vircadia/vircadia#221]
For the textEffectThickness property of the "Text" entity,
The value "outlineFill" does't work (but "none" "outline" "shadow" work fine.)

It seems to be incorrect in the c++ side
while the doc refer to "outlineFill", the code seems to refer to "outline fill".

**Comment by HifiExperiments** [comment]
I think the docs are wrong; I originally intended it to be space separated (I imagined that in the future we’d support more options, and they’d be space separated and order wouldn’t matter)

**Comment by AleziaKurdis** [comment]
Here's the suspected file that might cause the issue:

project-athena/libraries/shared/src/TextEffect.cpp

Line 14 I would expect "outlineFill"

**Comment by AleziaKurdis** [comment]
How could I plug a space separate value in this json ?

...
            {
                label: "Font",
                type: "string",
                propertyID: "font",
            },
            {
                label: "Effect",
                type: "dropdown",
                options: {
                    none: "None",
                    outline: "Outline",
                    **outlineFill:** "Outline with fill",
                    shadow: "Shadow"
                },
                propertyID: "textEffect",
            },
            {
                label: "Effect Color",
                type: "color",
                propertyID: "textEffectColor",
            },
...

**Comment by AleziaKurdis** [comment]
> I think the docs are wrong; I originally intended it to be space separated (I imagined that in the future we’d support more options, and they’d be space separated and order wouldn’t matter)

You mean as a string like: "outline shadow fill" ?

**Comment by AleziaKurdis** [comment]
I simply did that and it works.

 {
                label: "Effect",
                type: "dropdown",
                options: {
                    none: "None",
                    outline: "Outline",
                    **"outline fill": "Outline with fill",**
                    shadow: "Shadow"
                },
                propertyID: "textEffect",
            },

I suggest we keep this like this and **fixe the JSdoc**.
If we decide to support a list (space separated) of effects. This value will be fully compatible.
and all the scripts using this will continue to works.

**Comment by AleziaKurdis** [comment]
Note: This last commit don't solve the JSdoc. (only the editor)

**Comment by AleziaKurdis** [comment]
Still a problem to address (in jsdoc)
