### ISSUE TITLE
MyAvatar.setAvatarEntityData({}) Does not update Entity Mixer

### ISSUE THREAD

**Issue by 1st-BrainStormer** [vircadia/vircadia#223]
When clearing your avatar entity data, the entity mixer isn't updated as to what local entities were deleted by this action , So other clients still see them until you logout and back in.
It should notify the Entity mixer to prune your branch of the octree when its cleared.

Also ,when its set, it should prune then add back what is set to not leave any ghosts.

**Comment by daleglass** [comment]
Dev meeting: maybe it's stored in the avatar mixer?
