### ISSUE TITLE
Some shape type get occulted when alpha is applied. 

### ISSUE THREAD

**Issue by AleziaKurdis** [vircadia/vircadia#224]
Some specific shape types like "Sphere", "tetrahedron" and a few others
are occulted completely if they have transparency when they're behind a transparent cube. But it works for other shape types like "cube", "cylinder" and a few others.

![image](https://user-images.githubusercontent.com/60075796/77219170-7df04f00-6b09-11ea-8372-c9fa8b9c9ebd.png)

![image](https://user-images.githubusercontent.com/60075796/77219172-847ec680-6b09-11ea-8e9a-f3a3dd430037.png)

**Comment by SilverfishVR** [comment]
I can confirm this is still an issue (running PR442), and is related to the kind of shape, there seem to be some weird kind of rendering order between them:

![shapes_2020-06-14 23 53 07](https://user-images.githubusercontent.com/53531160/84605333-ca46f300-ae9c-11ea-9a99-e75d4f33a907.png)
all shapes (40% alpha) in front of all shapes (98% alpha)

get it here to confirm: https://silverfish-freestuff.s3.eu-north-1.amazonaws.com/ShapeOclutionTest.json
