### ISSUE TITLE
Fake Audio Device? Hook onto an app and pipe its audio?

### ISSUE THREAD

**Issue by two-one-five** [vircadia/vircadia#226]
Somehow have interface generate an output device that can then have the audio piped through to the mixer. Or perhaps hook onto the application like Discord does to stream audio.

**Comment by daleglass** [comment]
Some things in the code seem to suggest it might already exist. Needs testing and documentation to see if it's good enough.

**Comment by Basinsky** [comment]
is this related to page 197 on the documentation
https://bas-skyspace.ams3.digitaloceanspaces.com/docs-highfidelity-com-en-rc80.pdf

**Comment by daleglass** [comment]
Keeping this around for the link, docs may need improving.

**Comment by ctrlaltdavid** [comment]
Could add to wiki in interim.
