### ISSUE TITLE
Explore app:  Change domain to "Place"

### ISSUE THREAD

**Issue by Aitolda** [vircadia/vircadia#238]
Not only is "domain name" not accurate, using the term "place" preserves some continuity with the terminology users were already familiar with from High Fidelity, further emphasizing that you won't need to buy a placename as you did before.

If continuity weren't an issues, "location" would be an acceptable alternative.

**Comment by kasenvr** [comment]
I suppppoooossseeee I could squeeze that in.

**Comment by Aitolda** [comment]
This I'm less certain on this, but should owner be something like "added by" or "placed by?"

Owner seems a bit misleading.

**Comment by Aitolda** [comment]
This has simply be changed to "Location Name" in more recent builds.
