### ISSUE TITLE
Feature Request: Billboarding of mesh objects

### ISSUE THREAD

**Issue by Aitolda** [vircadia/vircadia#243]
This would be similar to the two billboarding offered by image entities.   However, as a 3d object we'd need to choose a default angle to follow you (likely the Z axis) but this could be changed by altering the rotation of the object in the usual way.

Uses:
-3d false light effects (fake light glares
-2d cutout distant trees with alpha clip.
-imagination

**Comment by kasenvr** [comment]
Potentially K3 material, but we would want to know how hard it would be to apply the same billboarding from another type of entity (e.g. web, images) to this.

**Comment by HifiExperiments** [comment]
the above PR adds the billboardMode property to entities, but doesn't implement the second part of what you mention (modifying the angle that is following you).  currently, when billboardMode is yaw or full, models always face "forward" towards you.

one potential solution would be to use the entities actual rotation (currently ignored when `billboardMode != none`) to let you rotate the entity first, before it is oriented towards you.  the only downside is that this change could potentially break existing billboarded text/image/web entities.  thoughts?

**Comment by Aitolda** [comment]
You know, I think what you've done covers it well enough, as long as your choose your orientation in your 3d application before exporting.

**Comment by HifiExperiments** [comment]
👍 it would also be easy to change in the future (with the caveat that it could cause similar breakage then)

**Comment by Aitolda** [comment]
> 👍 it would also be easy to change in the future (with the caveat that it could cause similar breakage then)

Sure.  Might be worth revisiting should you feel inspired, but this is great already.

**Comment by Aitolda** [comment]
Addressed in [#961](https://github.com/vircadia/vircadia/pull/961)
