### ISSUE TITLE
Housekeeping: "Plugin hifiKinect.dll failed to load"

### ISSUE THREAD

**Issue by Aitolda** [vircadia/vircadia#26]
" Cannot load library C:\Program Files\High Fidelity\plugins\hifiKinect.dll: The specified module could not be found."

Not a big one, but more of a housekeeping bug.  If this is no longer in use perhaps we should stop looking for it?

**Comment by SilverfishVR** [comment]
Are these the kind of things that could be added back in with modkit?

**Comment by thoys** [comment]
or the plugins could simply be updated

**Comment by daleglass** [comment]
Needs retesting to see if it still happens

**Comment by Aitolda** [comment]
This is no longer an issue.
