### ISSUE TITLE
Rendering Effects make things unsharp

### ISSUE THREAD

**Issue by JulianGro** [vircadia/vircadia#260]
When setting the Rendering Effects to anything other than "No Rendering Effects", the image becomes unsharp. This is especially true for me in VR.
Disabling TAA via the development menu does not fix this, so this is unrelated to #185

**Comment by Aitolda** [comment]
When disabling TAA it defaults to FXAA.  Perhaps we need an option to disable this as well.

**Comment by Aitolda** [comment]
Recommend we make this setting separate for VR and Desktop modes.  It actually looks quite good on a desktop at 1080p, however the current settings in VR aren't optimal.  Once we separate these, we should reconsider the defaults, and also make sure it's easy to turn off for those that don't want this (add this to the graphics screen perhaps).

**Comment by JulianGro** [comment]
https://github.com/vircadia/vircadia/issues/1357

**Comment by Penguin-Guru** [comment]
If [this PR](https://github.com/vircadia/vircadia/pull/1427) doesn't help, [this one](https://github.com/vircadia/vircadia/pull/1423) should be easily extensible to support other effects.

**Comment by ksuprynowicz** [comment]
#1427 does work by disabling antialiasing. I will check it on Windows and high resolution VR headset tomorrow.
