### ISSUE TITLE
Valve Index Rendering effects do not extend all the way 

### ISSUE THREAD

**Issue by JulianGro** [vircadia/vircadia#263]
When Rendering Effects is set to anything other than "No Rendering Effects", the rightmost side of the screen on the Valve Index does not use any of those effects. There is effectively a low detail bar on the right.
Personally I can only see this when the lenses are as close to my eyes as possible (like always) and I am looking forward.

**Comment by Aitolda** [comment]
Valve index is not yet supported but hopefully someone with the hardware and desire can take this on at some point.

**Comment by daleglass** [comment]
Could we have a screenshot of this?

**Comment by JulianGro** [comment]
![Unbenannt](https://user-images.githubusercontent.com/11144627/86531152-23fc7500-bebf-11ea-94e4-a4963e531b84.PNG)
Apparently it is not only much more visible than I thought, but also only happens to the right eye.

**Comment by JulianGro** [comment]
yes :angry:

**Comment by ksuprynowicz** [comment]
It's similar on HP Reverb G2. What's interesting is that the cutoff line is not straight:
![effects](https://user-images.githubusercontent.com/11568651/145886309-05389584-4408-4636-8449-095b4cc4beac.jpg)
I tried debugging it with RenderDoc and everything is rendered properly up to this point in pipeline:
```
    // DeferredBuffer is complete, now let's shade it into the LightingBuffer
    const auto extraDeferredBuffer = RenderDeferred::ExtraDeferredBuffer(surfaceGeometryFramebuffer, ambientOcclusionFramebuffer, scatteringResource).asVarying();
    const auto deferredLightingInputs = RenderDeferred::Inputs(deferredFrameTransform, deferredFramebuffer, extraDeferredBuffer, lightingModel, lightClusters, lightFrame, shadowFrame, hazeFrame).asVarying();
    task.addJob<RenderDeferred>("RenderDeferred", deferredLightingInputs);
```
After this It's broken exactly like in the screenshot.
