### ISSUE TITLE
arms spazing out in certain locations with non-T-pose resting position

### ISSUE THREAD

**Issue by JulianGro** [vircadia/vircadia#264]
When moving your arms to certain locations relative to you on the Valve Index, your arms start to flicker between two positions. This flicker is so fast that it almost appears as if you had more arms.

**Comment by Aitolda** [comment]
Valve index is not yet officially supported.

**Comment by kasenvr** [comment]
It might be possible that this is an IK problem that happens for all VR devices, if you can tell us specifically the range that you've tried and with which avatars (or if it works with all avatars?) then we can confirm that.

**Comment by jug007** [comment]
It seems to only happen with my own avatar. Or rather it doesn't happen on woody.
http://motofckr9k.ddns.net/m/Effole9.fbx if anyone want to try.
I did do some changes to the armature on http://motofckr9k.ddns.net/m/vircadia/Effole_normal_3d_mouth_new_flow.fbx which I haven't tested.
As a linux user it is always a pain for me to do any vr testing on windows, so I tend to not do it.

**Comment by JulianGro** [comment]
Forgot to update this:
This issue is reproduceable and is caused by avatars whose resting pose is not close enough to a T-pose. Adjusting the resting pose fixes the problem. Thanks to Piper for helping troubleshoot this.

This behavior should be changed, or the interface should show a warning when you try to use an avatar that doesn't use a T-pose, as newbies will definitely come across avatars in A-pose which they might want to use in Vircadia.

**Comment by daleglass** [comment]
Menithal's plugin will force the avatar into a T-Pose, so perhaps this is something that needs to be addressed externally.

We definitely should document this requirement

**Comment by JulianGro** [comment]
yes :angry:
