### ISSUE TITLE
Moving up stairs is slow

### ISSUE THREAD

**Issue by JulianGro** [vircadia/vircadia#265]
When moving up 3 dimensional stairs, the movement speed is very low. It might make sense to not be able to sprint up stairs really fast, but the extend of this just makes you feel immobile.

**Comment by Aitolda** [comment]
Have you tried out the alternate controller scheme selections under settings/controls?

Options include
-default
-analog
-analog++

analog controls give you direct throttle of movement speeds, and analog ++ has a slider to control this further.

**Comment by daleglass** [comment]
How could this be addressed? Faster speed? Physics changes?

**Comment by daleglass** [comment]
Perhaps suggest using ramps in the documentation

**Comment by JulianGro** [comment]
This was partially fixed my Phil when he fixed friction being applied twice in VR
