### ISSUE TITLE
Eyes can be selected as a viewpoint even if there are none

### ISSUE THREAD

**Issue by JulianGro** [vircadia/vircadia#267]
Even if your avatar does not have any eyebones, you can select the eyes as your viewpoint. This made my viewpoint move to the far back of my head in my case.

**Comment by ctrlaltdavid** [comment]
How to repro? ... Which avatar? Which setting?

**Comment by JulianGro** [comment]
You could try http://94.130.177.235/Effole22.fbx
This should only happen in VR.

**Comment by JulianGro** [comment]
yes :rage:
