### ISSUE TITLE
Weird camera movement when flying

### ISSUE THREAD

**Issue by JulianGro** [vircadia/vircadia#269]
When taking of and when landing in first person your camera moves back and forth weirdly which makes it hard to land, especially when flying on for a little bit, like when flying onto a table.

**Comment by Aitolda** [comment]
If you are talking about the quick dip forward before rising up, That seems to match what the avatar is doing when I pull out to 3rd person and jump.  Your camera can be attached either to the eyes of the avatar or it's headbone (switching able in the avatar app).

The immediate options that come to mind are
-change the jumping animation
-change the eway the camera works in first person mode

There are some problems with both, but it couldn't hurt to bounce around ideas.  It's worth noting that this is not an issue while in VR as animations are overrided by the ik.

**Comment by ctrlaltdavid** [comment]
If you set `Camera.mode = "first person look at";` there is no backwards movement when you jump up.
