### ISSUE TITLE
Make avatar able to sit anywhere

### ISSUE THREAD

**Issue by ctrlaltdavid** [vircadia/vircadia#272]

**Comment by Aitolda** [comment]
No idea why, but this feature would bring me comfort.

**Comment by kasenvr** [comment]
https://apidocs.vircadia.dev/MyAvatar.html#.beginSit is a thing, maybe we can expand on this and confirm its implementation?

**Comment by digisomni** [comment]
This will be a feature when the Nyx UI system is released. :)
