### ISSUE TITLE
Frameless Overlay WebWindows

### ISSUE THREAD

**Issue by two-one-five** [vircadia/vircadia#291]
Even after we move that back under the Overlays API as it should be, the web window itself needs to be able to have an option to be made frameless.

**Comment by thoys** [comment]
InteractiveWindow is the new api for window creation, which allows windows to detach from the interface. The plan was to have InteractiveWindow also work as a web window. It would probably make more sense adding the frameless feature to InteractiveWindow.

**Comment by kasenvr** [comment]
https://apidocs.vircadia.dev/InteractiveWindow.html
