### ISSUE TITLE
Avatar wearables scale incorrect on save/reload

### ISSUE THREAD

**Issue by Aitolda** [vircadia/vircadia#299]
If you try to resize a wearable, then save to your favorites, wearable scale will be incorrect, and generally much smaller than the intended size.  Sometimes selecting said item in the create menu (while wearing) causes the size to shift suddenly as well. This occurs both when saving an "outfit" to favorites in the avatar menu, as well as exporting entities. 

1. Load a custom wearable in the avatar menu.
2. Change the scale of the wearable.
3. Save outfit to favorites.
4. Swap to a different favorite.
5. Swap back to the recently saved outfit.

**Comment by kasenvr** [comment]
It would be necessary to determine if the "Avatar" app itself is the primary culprit for this or if it is the MyAvatar API.

**Comment by ctrlaltdavid** [comment]
Couldn't repro on master or 2020.2.1 with wearable from Marketplace nor with FBX loaded from Web site. Need URL of example wearable that's failing.

**Comment by Aitolda** [comment]
Testing with [This Hat](http://mpassets.highfidelity.com/d1c52172-f168-4cc3-a807-79171c6cde15-v1/PioneerHat.fbx)

Oddly enough, I can't repro on Woody or some of the usual height avatars, however it happens every time with my personal avatar, as well as the Robimo from the marketplace.  It's worth noting that BOTH are shorter avatars, but I've confirmed both are set to scale = 1 in the FST.

**Comment by Aitolda** [comment]
It's also worth mentioning that saving a wearable as a json has issues on the same avatars, but sets to an entirely different scale.

**Comment by Aitolda** [comment]
Revisted. This is still an issue as of Vircadia 2021.1.0 Eos.

**Comment by daleglass** [comment]
Dev meeting: maybe related to avatar rotation and scale. Doesn't happen for the Woody.
