### ISSUE TITLE
Interface crash if start up without HMD after crash with HMD

### ISSUE THREAD

**Issue by ctrlaltdavid** [vircadia/vircadia#305]
User report along the lines of if you crash with HMD connected (or is it while in HMD mode?) and then try to start Interface again without the HMD connected, Interface crashes. 

This could warrant some investigation to see if this repos, and then if it does then fix the problem.

**Comment by Aitolda** [comment]
I'm curious, is steamVR loading when this happens?  I have an Oculus Quest/Rift and I do experience issues if it's not plugged in.  As far as I can tell, when I leave my HMD plugged in, regardless of whether I am launching in VR mode,  Everything loads up fine.   If I unplug my HMD, it will launch steamVR and various issues occur.  Sometimes it will crash entirely, although more often than not audio will fail to load.  It's worth noting this issue do not occur for me if I have steamVR open before I load interface, or disable steamVR entirely.

**Comment by daleglass** [comment]
This could really use a backtrace
