### ISSUE TITLE
No animation on baked assets on ATP

### ISSUE THREAD

**Issue by SilverfishVR** [vircadia/vircadia#313]
Baked *.fbx's on the ATP do not animate, the framecounter is running but the animation do not show, deselecting _"Use baked version"_ (and caschebusting) shows the animation corresctly.

*.fbx's baked with the standalone oven do animate correctly (using the _filename.bake.fbx_ file)

I tried uploading the same file twice (with different names) to the ATP, to use one for model(baked) and one for the animation(unbaked) but through some kind of witchcraft it knows they are the same model an changing _use baked version_ on one, changes both.

It is really a minor issue since the ATP is used so little, but maybe there should be a warning about it on the asset browser window?

**Comment by Aitolda** [comment]
I question if this is a bug or simply an incomplete feature.  But we don't have a label for that so I will mark as a bug for now.

**Comment by daleglass** [comment]
Can we have a sample asset to test with?

**Comment by SilverfishVR** [comment]
yes, this is a model baked with the standalone oven:
https://silverfish-freestuff.s3.eu-north-1.amazonaws.com/Misc/Gyroscope/bakedTest/hifigyro/OvenBakedGyro.json
it should animate just fine.

to test ATP baked model load this on to the ATP:
https://silverfish-freestuff.s3.eu-north-1.amazonaws.com/Misc/Gyroscope/bakedTest/hifigyro/original/hifigyro.fbx
it should bake automatically, add to world and then put in the same url in the "animation" property and enable "play automatically", it should not animate.

open the asset browser (ctrl+shift+a) and uncheck "use baked", you need to click it twice 😕  and then reload content to update. it should now animate.

**Comment by Aitolda** [comment]
I believe we have yet to address this so I am removing the "stale" tag.
