### ISSUE TITLE
crackling audio on Linux

### ISSUE THREAD

**Issue by JulianGro** [vircadia/vircadia#315]
Sometimes the audio of people speaking is crackling.
This seems to happen mostly when there is a lot of people speaking at the same time or when Dale Glass is speaking.
The interface actually created multiple log files and didn't stop logging when it wasn't able to exit, so I guess I will just leave a zip file here in case it is of any use.
[crackling.zip](https://github.com/kasenvr/project-athena/files/4533915/crackling.zip)

**Comment by daleglass** [comment]
Since you mentioned me, it seems I might be having a local issue. I've got a microphone plugged into an USB hub that might be doing something weird. I'm looking into it.

**Comment by daleglass** [comment]
Since I changed where I plug in my microphone the crackling seems to have went away. Do you notice this with anyone else?

**Comment by jug007** [comment]
I haven't heard it on the makers meeting, so I guess it might actually just have been your microphone. I will close this for now and open it back up again if it happens again.

**Comment by jug007** [comment]
It actually doesn't happen every time, but it also happens to the audio input, not just the output.

**Comment by jug007** [comment]
So when I disable the dynamic jitter buffer, there is really bad jitter. This makes me think that the audio high latency that I sometimes get might just be the buffer getting really big, because of the high jitter.

Also in the audio stars in the developer menu, all the "Jitter" values are red, which feels like a bad thing.

**Comment by jug007** [comment]
After reading up on it, it wouldn't make any sense for it to be the jitter buffer.
Switching audio input device sometimes makes vircadia get quiet.
The input crackling also shows up in PulseAudio, but only happens in Vircadia and not always.
So it feels like Vircadia is maybe somehow lagging the audio driver or something.

**Comment by jug007** [comment]
It seems like the crackling on the audio input is influenced by the audio output.
The crackling does stop after a while though, which I couldn't explain.

When having PulseAudio write a log file, there is hundreds or messages popping up when Vircadia is running:
```
( 226.824|   0.016) I: [pulseaudio] client.c: Created 4194 "Native client (UNIX socket client)"
( 226.824|   0.000) I: [pulseaudio] client.c: Freed 4194 "Native client (UNIX socket client)"
( 226.824|   0.000) I: [pulseaudio] protocol-native.c: Connection died.
```
Here is the full log: [pulseverbose.log](https://github.com/kasenvr/project-athena/files/4561644/pulseverbose.log)

**Comment by jug007** [comment]
So the old issue that is the crackling is still happening, but I got the audio card working (at least for now).
The settings that got it working:
/etc/pulse/daemon.conf:
avoid-resampling = yes
default-fragments = 5
default-fragment-size-msec = 2

/etc/pulse/default.pa:
load-module module-udev-detect ignore_dB=1 tsched=0

**Comment by daleglass** [comment]
Hmm. Still happening?

**Comment by JulianGro** [comment]
I had jankily workee around the problem (by using two sound cards).
I will close this for now since I am sure it is the audio systems fault and not Vircadia.
