### ISSUE TITLE
Feature: "Renderless Mode" for reduced graphic footprint

### ISSUE THREAD

**Issue by Aitolda** [vircadia/vircadia#316]
This could be a checkbox under developer/renderer.  With the exception of menus/overlays/apps Nothing else would render in the main window

Very often I'm multitasking and working in Blender and other 3D untilities while signed into HF, listening or using chat while working.  This would give me the option to ease the burden on my videocard and put my resources towards the other 3D apps. Toggling this on and off as needed would be extremely useful to me.  Another use case would be running multiple instances of the interface for streaming audio purposes (second avatar as DJ, etc).

**Comment by thoys** [comment]
Wouldn't you call this headless mode (or you do startup with graphics don't you)? Also, might this have side-effects on the physics engine?

**Comment by Aitolda** [comment]
> Wouldn't you call this headless mode (or you do startup with graphics don't you)? Also, might this have side-effects on the physics engine?

I don't really care what it's called, so sure!  As far as physics go I'm not sure.  Maybe it would be ideal to check for physics objects within a few meters so your avatar can still land properly.  Otherwise it may just float.  Although that wouldn't be a dealbreaker for me if it did.
