### ISSUE TITLE
objects snapping into place

### ISSUE THREAD

**Issue by JulianGro** [vircadia/vircadia#322]
It would be really useful, especially for desktop users, to be able to habe objects snap into place when moving them. Like a vase onto the top of a table, or the table onto the floor.
This could make placing objects a lot easier and faster.
I know that there is snap to grid, but that doesn't seem nearly as helpful.

**Comment by Aitolda** [comment]
I think in blender something like this is called "snap to surface" although this deals more with individual vertices. "Snap to collision" or something like that maybe.

**Comment by Aitolda** [comment]
I think we can probably close this out now that this is incorporated.

**Comment by daleglass** [comment]
Fixed in #932
