### ISSUE TITLE
"Try again" option in the avatar packager does not register updates to the source model.

### ISSUE THREAD

**Issue by Aitolda** [vircadia/vircadia#327]
"Try again" option in the avatar packager does not actually register updates to the source model.

For example, if I use the avatar packager and I get a warning about a missing texture, quickly update the model and resave (same name), then press try again on the packager, these changes will not be registered and I will get the same error.

**Comment by daleglass** [comment]
The "try again" option should be reloading the data

**Comment by Aitolda** [comment]
To my knowledge this is still an issue.

**Comment by Aitolda** [comment]
> Hello! Is this still an issue?

Yes.
