### ISSUE TITLE
Fix High Fidelity logos in image files

### ISSUE THREAD

**Issue by ctrlaltdavid** [vircadia/vircadia#332]
At least one of the image files in \interface\resources\images still includes the High Fidelity logo: steam-min-spec-failed.png. Fix this and check for other occurrences.

**Comment by mrkcdf** [comment]
Is the end-goal here to remove the HiFi logos entirely? There's also about-highfidelity.png high-fidelity-banner.svg AvatarTheftBanner.png

**Comment by digisomni** [comment]
Solved with 1588.
