### ISSUE TITLE
There should be a way to synchronize a web surface to multiple users

### ISSUE THREAD

**Issue by daleglass** [vircadia/vircadia#341]
The obvious use is things like presentations. I click somewhere, everyone sees it.

We discussed a bit forwarding things like click events, but this is probably not reliable long term due to timing issues.

A more practical way would be capturing the texture of the controlling user, and having the rest of the user display that image. This would be less bandwidth efficient but a lot more reliable. The image could perhaps be forwarded through the messaging mixer.

**Comment by HifiExperiments** [comment]
Shouldn’t the screenshare feature allow this?

**Comment by daleglass** [comment]
Maybe, but I don't want to share my screen (even if restricted to the interface window).

Here's what I basically want to happen:

1. Create a web entity
2. Set a checkbox in the properties that makes everyone else receive an image of what I see when I interact with it.

**Comment by kasenvr** [comment]
It may be simplest to do a low FPS (maybe 5 FPS?) share of the images of your webview captured and shipped through the messaging mixer. This can be done by script if we can get a scripting API component to capture the image and encode it.

**Comment by ksuprynowicz** [comment]
Yes
