### ISSUE TITLE
MacOS Interface crashes when go full screen

### ISSUE THREAD

**Issue by ctrlaltdavid** [vircadia/vircadia#358]
From @languagelovr …
"
Small note specifically for build (macOS-latest, full):
I have a 2018 MacBook Pro running macOS Catalina v10.15.4. I have noticed that when clicking the green expand icon in the upper left-hand corner to go full screen the interface crashes. Please note that this happened on builds PR72, PR300 and PR352 as well. I've tested it in all 3 PR builds two times each and got the same result. I went back and tried the old HiFi interface as well and have confirmed that it does not crash when trying to go full screen. Thanks :)
"

**Comment by kasenvr** [comment]
One one iMac with the following specs, it did not crash when entering full screen:

> iMac (Retina 4K, 21.5-inch, 2019)
> Processor 3 Ghz Intel Core i5
> Memory 8GB 2667MHz DDR4
> Graphics Radeon Pro 560X 4GB
> OS Version 10.14.5 (Mojave)

**Comment by JulianGro** [comment]
On my macOS virtual machine with Catalina, the interface crashes when resizing the window or going fullscreen.
This is with PR482.

**Comment by daleglass** [comment]
It would be great to get a backtrace of this

**Comment by kasenvr** [comment]
![image](https://user-images.githubusercontent.com/52365539/88463651-39dbd500-ce82-11ea-9f88-d79a3f8cac19.png)

**Comment by JulianGro** [comment]
So according to Dave K. this crash does not happen on his machine. They are running Mojave.

**Comment by JulianGro** [comment]
This issue is resolved now and can be closed, right?

**Comment by daleglass** [comment]
As far as I know this is resolved and hasn't come up again. Closing.
