### ISSUE TITLE
Support explicit declaration of script to be whitlisted for serveless and domain.

### ISSUE THREAD

**Issue by AleziaKurdis** [vircadia/vircadia#368]
If someone has activated the Client Script Whitelist, this is blocking systematically the normal usage of domains running on their own source of scripts. It might also block the normal use of the serverless domains in the same way. This ruins all the efforts done by the creator to provide a decent experience to their visitors. For what I understand of the Whitelist feature, it has for main objective to prevent malicious people to disturb by running script, and not to block the scripts from a domain creator to run when people come to visit.

It would make sense that the source of scripts used by the domain or the serverless domain gets automatically whitelisted for the current session on that domain or serverless domain. (Otherwise, I don't see the point to keep building something)

To address that, 
Maybe we could simply support an explicit declaration of the trusted Client Script sources directly on the domain/serverless domain data:

![image](https://user-images.githubusercontent.com/60075796/82277944-1151cf00-9957-11ea-9314-518f6f9323e7.png)

(here how it would look on a serverless domain) 

For Serverless it's relatively simple, just make sure to collect that info if it is existing and add those sources to the current whitelist (in runtime for the session only)

For Domain, I suppose it can be supported in a similar way. (But it would need a second part to this implementation to have a whitelist declared and kept on the server data. And injected this when the content is requested. Could that be saved directly in the model.json? )

**Comment by kasenvr** [comment]
PR #465 lays the groundwork for handling this for domain-servers, however serverless domains will need to have some sort of way to specify in their export *or* maybe just better options for the user to say "yes" to whitelisting a serverless before going...

**Comment by AleziaKurdis** [comment]
I don't think we want to have to answer "Yes" when we go to a domain.
Imagine you would have to do this on every single webpage you go over the web. (most of the web page don't even work without their own script... ) Not sure that would make any sense.
So this is the same for domain and serverless.  PPersonnaly, I build "client side" everything I can. (because the server has already enough to deal with and it' easy to port to a serverless to store the content. after. If you come on my domain and "refuse" the script, then you won't see a major part of the content (since it's generated by script "locally" just for you.) The scripts are the content, it's not optional.

Again: the objective of a whitelist is to prevent a 3rd user to run "non desired" scripts on our domain. Not to fight against what we build, or the domain content it-self.

**Comment by AleziaKurdis** [comment]
Still a possible issue with the whitelist implementation.

**Comment by AleziaKurdis** [comment]
Still a possible issue with the whitelist implementation.
