### ISSUE TITLE
HMD.preferredAudioInput() and Output() don't work with OpenVR HMD plugin

### ISSUE THREAD

**Issue by ctrlaltdavid** [vircadia/vircadia#374]
They work with Oculus per: https://apidocs.vircadia.dev/HMD.html#.preferredAudioInput

However when using the OpenVR plugin (including with Oculus via SteamVR) these methods always return "". This was the case in the 0.86.0-based K2 release and is still the case in current master.

**Comment by daleglass** [comment]
This needs testing by somebody with the hardware to see if it still happens after the OpenVR updates

**Comment by JulianGro** [comment]
For VR apps it is pretty normal to just use the systems default devices. SteamVR normally changes those automatically when starting.
