### ISSUE TITLE
Show invisible entities when in create menu

### ISSUE THREAD

**Issue by SilverfishVR** [vircadia/vircadia#390]
to make parented materials and entities with "render with zones" easier to find.

Just how it already works with Lights, Zones and particle effects where an icon representing the entity type shows in-world whenever the create menu is open.

one extra option I would like to see is the option to render the bounding box of all zones, not just the one currently selected, perhaps as a developer menu option.

**Comment by Aitolda** [comment]
Perhaps this should be a toggle within the entity list.  Sometimes, just to make it easier to focus in a complicated scene, you may wish to keep some things invisible.

**Comment by SilverfishVR** [comment]
Lights+particles and zones already have toggles for that so yes, that would on par with current functionality.

**Comment by AleziaKurdis** [comment]
I would display the overlay icon on material only when they are linked to a parent. Is this makes sense?

**Comment by AleziaKurdis** [comment]
I think this can be closed. 
Since we have now a icon displayed for Material entities when they are parented. So you can always see where your material entities are, and this can let you select it as you need.
