### ISSUE TITLE
wrist rotation is weird and unrealistic

### ISSUE THREAD

**Issue by JulianGro** [vircadia/vircadia#452]
When rotating your hand in VR, all the rotation get done on the wrist. In reality, a wrist cannot rotate much or at all. In reality, the two lower arm bones would move somewhat independent of each other to rotate the hand, and the shoulder might add a little to that, if the rotation goes too far.
This makes people wrists look really weird, since the lower arms and wrists are not round on most avatars.

I would suggest making the wrist not able to rotate, or only able to rotate one or two degrees; And make the lower arm do 2/3 of the rotation, while the other 1/3 rotation gets done by the shoulder.
We should probably take a look how other platforms, like VRChat, handle this, and/or try out what looks best, by making animations in Blender.

**Comment by kasenvr** [comment]
I think it's easy to just look at your own anatomy and see how you can push this into the system. I would hope that we can simply alter the IK system's values but I've not looked at that part of the code yet.

**Comment by Colorfingers** [comment]
The wrist (and any other bones) will not bend more than the weights allow I would think.  It could be that the weights need to be examined in Blender...

**Comment by kasenvr** [comment]
https://github.com/kasenvr/project-athena/blob/master/libraries/animation/src/AnimInverseKinematics.cpp#L1273 This may be relevant, I was in that part of the codebase recently and spotted that.

**Comment by JulianGro** [comment]
https://github.com/kasenvr/project-athena/commit/3fa3cd8cfdb9be2ec3f4d1c160e000a35c9cceb8
"I've verified that there are no ill effects in removing it." :thinking:

**Comment by JulianGro** [comment]
Here is an old PR which apparently addressed this issue and never got merged: 
[HiFi_PR_15341.zip](https://github.com/kasenvr/project-athena/files/4976404/HiFi_PR_15341.zip)
