### ISSUE TITLE
Windows installer isn't signed

### ISSUE THREAD

**Issue by ctrlaltdavid** [vircadia/vircadia#456]
2020.2.1-Asteria Windows installer causes dialog with "Publisher: unknown" to be displayed.

![publisher-unknown](https://user-images.githubusercontent.com/7455448/84632404-f61cb400-af42-11ea-8478-2c751408ae5e.png)

![publisher-unknown-also](https://user-images.githubusercontent.com/7455448/84633135-0d0fd600-af44-11ea-825d-6f01f8ca5410.png)

**Comment by daleglass** [comment]
We do have a certificate now, but so far attempts to sign the installer haven't succeeded.

**Comment by digisomni** [comment]
The Windows installer is signed now. :)
