### ISSUE TITLE
Icons from the More+ App can be dragged and dropped into the worldspace and asset server.

### ISSUE THREAD

**Issue by Aitolda** [vircadia/vircadia#461]
Open the More+ App.  Click on an icon (I accidentally selected the page arrow) and drag it into 3d space of a domain you have permissions in.  It will indicate it's being added and will be visible.

**Comment by AleziaKurdis** [comment]
Not sure it's a bug.
You can drag any picture from an in-world web browser to import it as an image entity. 
it was a feature I think.
Maybe it could prompt a warning to ask if we really want to import it.

**Comment by kasenvr** [comment]
Agreed, a prompt first would help until we can get a setting for it maybe.

**Comment by Aitolda** [comment]
This is not technically a bug.
