### ISSUE TITLE
Clipboard.exportEntities( filename, x, y, z, scale ) should select entities inside box, not touching box..

### ISSUE THREAD

**Issue by 1st-BrainStormer** [vircadia/vircadia#501]
Clipboard.exportEntities( filename, x, y, z, scale )  seems to also select entities touching box.
This should not happen by default.  It could be added as an option though.

**Comment by daleglass** [comment]
Discussed in meeting: this is a problem if you want to select some small objects inside a larger environment, it would select the room and not just the chairs inside it.

**Comment by 1st-BrainStormer** [comment]
Interesting,  if you pull down the edit menu , you have 2 choices: "select
all entities inside box" and "select all entities touching box" This works
for the user.  This is for scripting, the computer has perfect vision so
size doesn't matter. The problem I had was I tried selecting only the stuff
in the box and instead I got that and  the zone it was in etc. when all I
targeted  was a single entity to be exported.
