### ISSUE TITLE
Feature Request: Finish implementing the hinge action. 

### ISSUE THREAD

**Issue by 1st-BrainStormer** [vircadia/vircadia#503]
It would be nice to have the Hinge action fully functional so we can make doors that actually work. As is, you have to make them fight with the other entity to close. Which is too fast. These are the hinge arguments that were never completed:

Property|Type|Default Value|Description
---------|----|-------------|-----------
softness|float|0.9|rusty vs well-oiled, 0 to 1
biasFactor|float|0.3|related to the relaxed position of the hinge
relaxationFactor|float|1.0|related to force applied near limits of hinge rotation
motorVelocity|float|0.0|target angular velocity of hinge
motorTarget|float|0.0|angle toward which the motor should drive the hinge
motorTargetTimeScale|float|0.0|how quickly to drive the hinge toward motorTarget
maxImpulse|float|1.0|maximum impulse for hinge motor

**Comment by daleglass** [comment]
Question in meeting: where did those properties come from?

**Comment by ctrlaltdavid** [comment]
Probably: http://ctrlaltstudio.tst/vircadia-d-jsdoc/Entities.html#.ActionArguments-Hinge
