### ISSUE TITLE
"Render with zones" dropdown not working in VR

### ISSUE THREAD

**Issue by SilverfishVR** [vircadia/vircadia#522]
the "Render with zones" dropdown box in create menu does not work in VR, clicking it does nothing.

I tested in openVR (Valve index) and Basinsky confirmed on Oculus CV1.

**Comment by AleziaKurdis** [comment]
This is the standard <select> that is not working well on the web component.
You can create a basic app, and have a <select>in your HTML page... the list of items will be displayed outside the window.
I hit that a few times in the past and have to change the design to not used a select.
I have 3 monitors, I've already seen the list of item display outside the interface window!
This a quite a bad issue. Select is kinda important.

**Comment by daleglass** [comment]
ctrlaltdavid: Dropdowns are tricky .. HTML ones are replaced at runtime with customer divs etc.

**Comment by AleziaKurdis** [comment]
Still an issue to be addressed.

**Comment by AleziaKurdis** [comment]
Addressed by PR#1252
