### ISSUE TITLE
Avatar Packager needs a new video

### ISSUE THREAD

**Issue by ctrlaltdavid** [vircadia/vircadia#59]
The Avatar Packager originally had a "Video" button that linked to the following HiFi video: https://youtu.be/zrkEowu_yps The video button is disabled in code because the video includes uploading to HiFi's server and is in the "High Fidelity" channel.

**Comment by daleglass** [comment]
#327 needs fixing first

**Comment by daleglass** [comment]
And #60

**Comment by daleglass** [comment]
yes
