### ISSUE TITLE
Add API support for backgroundColor attribute on tablet buttons

### ISSUE THREAD

**Issue by Madders** [vircadia/vircadia#614]
For script compatibility between Tivoli and Vircadia, add support for the backgroundColor attribute to the tablet.addButton method in the script API. Ideally the background colour also being applied to the button would be great, but for compatibility purposes just needs to not error if supplied.

**Comment by daleglass** [comment]
Not everyone here uses Tivoli, so it'd be very helpful to have a sample script, and an explanation of what behavior is wanted
