### ISSUE TITLE
There are still many reference to https://hifi-public.s3.amazonaws.com/ in the code.

### ISSUE THREAD

**Issue by AleziaKurdis** [vircadia/vircadia#625]
At least 8 c++ file still have URL pointing on file stored publically on 
https://hifi-public.s3.amazonaws.com/*
Many javascript too (probably not all critical)

Maybe we can move this from there before this get close, and replace the URLs.

**Comment by ctrlaltdavid** [comment]
There are also some URLs for other HiFi S3 URLs, e.g., https://hifi-metaverse.s3-us-west-1.amazonaws.com/marketplace/contents/e76946cc-c272-4adf-9bb6-02cde0a4b57d/8fd984ea6fe1495147a3303f87fa6e23.fst?1460131758

**Comment by daleglass** [comment]
Related: #198

**Comment by AleziaKurdis** [comment]
To verified if this is solved.

**Comment by AleziaKurdis** [comment]
No more present in the code. I close this bug.
