### ISSUE TITLE
It seems the avatar you are wearing is registered to another user.

### ISSUE THREAD

**Issue by ArcadeFever** [vircadia/vircadia#635]
Got this message when I was wearing a VirtualYou avatar I had created, but I was not logged into the metaverse server.  I'm unsure if we just need the graphic to be updated to remove "please contact support@highfidelity.com" or replace with something else.  Will vircadia continue to support ownership/verification of avatar models?

![Screen Shot 2020-08-21 at 2 36 24 PM](https://user-images.githubusercontent.com/6512223/90941481-1c3d5500-e3c7-11ea-893f-1375b3c59ac7.png)

**Comment by daleglass** [comment]
I think we're probably nuking this one, since hifi's infrastructure will go away at the end of September

**Comment by daleglass** [comment]
Being removed in PR #666
