### ISSUE TITLE
Sign MacOS installer

### ISSUE THREAD

**Issue by JulianGro** [vircadia/vircadia#638]
The MacOS installer is currently pretty hard to use, as MacOS is making users open their control panel to allow running the software.
Getting rid of that hurdle doesn't *look* very hard. At least if Apple is as easygoing as they make themselves look on their website: https://developer.apple.com/developer-id/
The page doesn't really say it the app only has to be signed or if it also needs to be notarized by Apple. But it sounds like the notarization might also just be an automatic check.

**Comment by digisomni** [comment]
There is a new issue outlining this and the steps to correct it. #1045
