### ISSUE TITLE
MacOS remove sandbox from install

### ISSUE THREAD

**Issue by JulianGro** [vircadia/vircadia#646]
The sandbox currently doesn't work on MacOS (#557) and confuses most (if not all) new MacOS users.
I would suggest removing it completely and putting it into a seperate package once we get it running again.

**Comment by kasenvr** [comment]
For Windows as well, it would be good to ship them separately perhaps.

**Comment by JulianGro** [comment]
> For Windows as well, it would be good to ship them separately perhaps.

#649
