### ISSUE TITLE
Rename sandbox

### ISSUE THREAD

**Issue by JulianGro** [vircadia/vircadia#648]
The name "sandbox" is very indescriptive, or rather feels like it is describing it wrong even.
Sandbox sounds like "easy to set up" "easy to use" "nothing can go wrong". While our sandbox has a good amount of stuff that can go wrong and is definitely not something that any child can configure and use.
I would suggest sticking with "domain server" or just calling it server so the end user just sees "Vircadia Server" and has a much better chance of understanding what it is.

**Comment by ctrlaltdavid** [comment]
I think "server" / "Vircadia Server" would be good. (The "server" / "Vircadia Server" comprises the domain server, assignment clients, etc.)

**Comment by ctrlaltdavid** [comment]
Note: In the Windows system tray widget, instead of "Visit Sandbox" it should say "Visit Server". (The word "server" is used for other server-related items in the widget's menu.

**Comment by digisomni** [comment]
As an interim step, it is now called "Vircadia Sandbox", next step will be to call it "Vircadia Server".
