### ISSUE TITLE
Windows separate Interface and Sandbox?

### ISSUE THREAD

**Issue by JulianGro** [vircadia/vircadia#649]
When installing Vircadia, you get asked if you want to install the sandbox. New users will have absolutely no idea what that is. I would suggest removing the sandbox from the interface installer and give it its own package. This way we can more easily make sure that people installing the sandbox understand what it is and how to use it. For example we could have the website link to a documentation page about the sandbox, rather than directly to an installer.

**Comment by kasenvr** [comment]
It looks like this is already possible, I'll generate some builds to confirm. Making a build using the flag `CLIENT_ONLY=1` appears to be what will do the trick.

**Comment by daleglass** [comment]
Possibly do like high fidelity and have installers with and without the sandbox?

Or hide it away in the installer, behind an "advanced install" option?

**Comment by JulianGro** [comment]
Maybe we should add a link to a documentation page inside the installer.
I think there would still be the need to advertise the sandbox a lot. Maybe putting information about the sandbox right on the download page?

**Comment by ctrlaltdavid** [comment]
It's currently possible to do Interface-only and Interface + Sandbox builds. So both could be provided each release. High Fidelity provided both but with the emphasis (default) download being Interface-only build, with a secondary link on their downloads page to Interface + Sandbox, described as "for developers". https://www.highfidelity.com/download

The following PR removes the confusing and not-properly-working "console" options from the Interface-only installer: https://github.com/kasenvr/project-athena/pull/682
