### ISSUE TITLE
Feature Request: add "created" date as sortable column in create's Entity List

### ISSUE THREAD

**Issue by ArcadeFever** [vircadia/vircadia#673]
In large build I find it difficult to find new entities that may have been recently added.  Since EntityProperties object has a "created" property, it would be great to have this added to the Create->Entity List user interface as a sort-able column.

**Comment by AleziaKurdis** [comment]
Maybe we could see to have one of the current columns that we could select which property to expose for it. Then it would be possible to sort on that column. This would be more flexible than only add this specific "created date" column. 

The current UI being not very wide, we can't easily add new columns, so I suggest that the current "File" column could be used for that purpose, and make it personalizable (for the session, and by default "File")
![image](https://user-images.githubusercontent.com/60075796/92272015-c7193d00-eeb6-11ea-8f05-c7a1ab8e90d8.png)

Not sure all the properties would make sense to be exposed in this column, we would need to figure the exhaustive list.

**Comment by AleziaKurdis** [comment]
Delivered in PR #833
