### ISSUE TITLE
Blendshapes fall behind even by seconds on avatars and models on busy domains

### ISSUE THREAD

**Issue by kasenvr** [vircadia/vircadia#680]
Unsure why this happens, but it happens for glTF & FBX models.

**Comment by HifiExperiments** [comment]
blend shapes are really expensive to calculate, so we do all the processing in separate threads.  in busy domains, this processing can lag behind.  is this a regression or just a general problem?  there might not be much we can do about it right now

**Comment by kasenvr** [comment]
According to Silverfish this is not a regression, just an ongoing issue. :)

**Comment by JulianGro** [comment]
I am not sure if it actually has that much to do with busy domains. I pretty much never have that issue. And when I do, it is exclusive to a specific person.

**Comment by ctrlaltdavid** [comment]
Is the processing that's getting bogged down in Interface or on the server?

Can blendshape data be dropped if it's behind?

**Comment by daleglass** [comment]
Is there a single thread dedicated to this? Could there be more than one?

**Comment by HifiExperiments** [comment]
there’s lots going on here.  if a client is updating slowly or has a poor connection, it’ll send updates to the server more slowly.  that leads to the situation Julian describes, where one client appears to be updating more slowly.

client side blend shape computation (where it actually calculates the per vertex offsets) is one of the most expensive things we do.  if I remember correctly, it uses a threadpool and kicks off one Blender per model per change (but then drops older frames if there are new updates by the time it actually starts computing).  it also tries to parallelize some of the work, but this might not work well in all cases
