### ISSUE TITLE
Collision hull does not update when a model is replaced.

### ISSUE THREAD

**Issue by Aitolda** [vircadia/vircadia#681]
I notice this one when I'm building out a space, constantly adding to a model which changes it's scale and shape.  This is not an urgent fix, as it only affects users in the domain at the time of model replacement, but it's a bit annoying for builders.  It's worth noting that a simple "reload content" does not work. You have to physically restart the interface.

1. Using the create menu, add a model, preferably one with a clear "floor." Set to exact collisions.
2. Select the model, and within it's properties, replace the model with another model url, different enough to notice collisions discrepancies.
3. Using avatar attempt to colide with model.
4. Close and reopen the interface.  Collisions will now be correct.

**Comment by JulianGro** [comment]
I have also had this problem on multiple occasions.

**Comment by ctrlaltdavid** [comment]
There are three problems here:
1) The collision hull is not updated.
2) The model is not displayed the correct size - though its dimensions don't change from the original, the rendered model isn't sized to fit.
3) Mouse clicks potentially do not work per the new model's geometry.

Example models that have distinct shapes and sizes that can be used for testing:
- http://ctrlaltstudio.com/downloads/vircadia-dev/gltf/VertexColors.glb
- http://ctrlaltstudio.com/downloads/vircadia-dev/fbx/textured-cube/external-textures.fbx

**Comment by ctrlaltdavid** [comment]
Interim work-around: change the entity position or registration point (and change it back again) to fix.
