### ISSUE TITLE
Fix or permanently remove the "console" options from Interface-only installer

### ISSUE THREAD

**Issue by ctrlaltdavid** [vircadia/vircadia#683]
Originally, the Interface-only Windows installer's advanced options included three "console" options:
![Interface-Only Options](https://user-images.githubusercontent.com/7455448/92291581-80d2e500-ef6d-11ea-893f-6950cca5da33.png)

These have been temporarily removed and annotated with FIXMEs in the following PR: https://github.com/kasenvr/project-athena/pull/682

The Windows Interface "console" is a cut-down version of the Sandbox system tray icon, with just the non-server menu items present. These menu items currently don't work properly.

Two options:
A) Remove the Interface "console" options from the installer permanently.
B) Fix the "console" operation and perhaps rename it. "Console" is not a very apt description.

**Comment by ctrlaltdavid** [comment]
Raised at a recent dev/community meeting: how to notify people if they have a message or something while Interface is minimized. The Console app has this sort of functionality. Perhaps the Console app should be fixed / improved (and perhaps renamed to something more fitting).

**Comment by kasenvr** [comment]
All depends on the platform it runs on, the launcher is slowly going to take its place in this case instead of managing two apps I'd reckon. They're both electron apps after all. :) My todo list does consist of adding metaverse functionality now to the launcher alongside server-console style functionality after.

**Comment by ctrlaltdavid** [comment]
Personally, I find many apps' Windows system tray icons useful. Additionally, I don't use the launcher.
