### ISSUE TITLE
Explore app does not always finish loading

### ISSUE THREAD

**Issue by JulianGro** [vircadia/vircadia#684]
Some users have had problems loading the explore app. It will show the top of the explore app (previous, home, next, visit), but not the actual list at the bottom. One of my friends has had that problem today. Even restarting the interface did not help.
Are we doing anything weird when loading the list? (I have not heard of similar problems with any other apps)
Is there some sort of retry mechanism in case something fails?

**Comment by ctrlaltdavid** [comment]
A program log from Interface start-up to opening the Explore app could be useful.
Does doing "reload scripts" fix the problem?

**Comment by vegaslon** [comment]
Might be better for the server to compute the Json every 30 seconds or something rather then on every request for locations. Imagine that would speed up wait time for location table
