### ISSUE TITLE
Black Visual Artifacting with Zone Haze

### ISSUE THREAD

**Issue by kasenvr** [vircadia/vircadia#702]
This was initially reported by Silverfish https://cdn.discordapp.com/attachments/632678644665548821/752655841454325890/vircadia-snap-by-Silverfish-on-2020-09-08_00-10-50.gif but I also confirmed seeing similar weird behavior when testing PR #576 

These are the values that were set for Zone Haze at the time...

https://user-images.githubusercontent.com/52365539/92419167-b3c9d400-f139-11ea-8132-e24dcf250450.png

**Comment by JulianGro** [comment]
This does not happen on Linux for me. Not on AMD with Mesa or Nvidia with proprietary drivers.
