### ISSUE TITLE
Make default "home" location the serverless tutorial rather than localhost.

### ISSUE THREAD

**Issue by Aitolda** [vircadia/vircadia#710]
Not everyone has a sandbox, but everyone has and starts initially in the serverless tutorial.  Currently with my fresh install, pressing "home" on the explorer app tries to send me to localhost, except I haven't even installed a sandbox on this machine.

**Comment by JulianGro** [comment]
Related #628

**Comment by Aitolda** [comment]
Duplicate of #628
