### ISSUE TITLE
Add error dialogue if an unsupported filetype is added as a model URL in the create app.

### ISSUE THREAD

**Issue by Aitolda** [vircadia/vircadia#711]
Sometimes I'm a space cadet and try to open a json with create (as if it were a model URL).  I get no errors other than the "green cube" outline which is the default for an invalid URL.  While I've been around long enough to figure out my own mistake, new users will have no indication.  

The other option is a general dialogue expressing a couple possibilities

"Error:  Filetype not supported or invalid URL"

**Comment by Aitolda** [comment]
I'd be tempted to have it refuse to even drop the item as well, as long as this doesn't interfere with existing entities who's URL has changed after adding (they'd keep the green box).  However, this might warrent some discussion before changing that behavior.

**Comment by AleziaKurdis** [comment]
I wonder how could we trap an error that happens on the system side? 
I think we can only figure the presence of an error by the "null" value returned by Entities.EditEntity or Entities.AddEntity. It can be anything else than the URL that causes that response.
Can we really do that based on a filename? You can have, for example, a .php file that would return a valid model. Apply a restriction will come with a lost in possibilities.

The green box is probably the best indicator we have to figure that it's specifically the model URL that is wrong.

**Comment by Aitolda** [comment]
Hmm.  Is there a way for a green boxed entity to automatically add in it's description ""Filetype not supported or invalid URL" or would have have the same problem?

**Comment by AleziaKurdis** [comment]
The API doesn't return that information, so Create App. can't figure this.
The only way I can see is maybe to get the file header. But would this be enough? (I wonder if we can get the header without download the file? I will check.)
Keep in mind that the URL can be right, the header too and the model still can be invalid.

**Comment by Aitolda** [comment]
Check Engine.

**Comment by kasenvr** [comment]
This might be a bit complex of a challenge, but seems possible... you'd have to try and *add* a lot of callbacks potentially to say if something failed when processing. It all depends on where it ran the checks and then where it failed.

But for the original issue asking simply if it has the right file extension when downloaded is probably much easier.

**Comment by AleziaKurdis** [comment]
Could become easily more a nuisance than a real help. Maybe try it a good amount of time before releasing a fix in that direction.

**Comment by ctrlaltdavid** [comment]
It would be possible to validate the file extension (.gbx, .glb, .gltf, .obj, .gz) in the New Model Entity dialog. For example, only enable the "Create" button if the URL entered ends with one of these extensions - no error dialog required.)

![new-model-entity](https://user-images.githubusercontent.com/7455448/95053101-706c8080-074c-11eb-81cb-d9a95489281d.png)

Dialog is implemented in \scripts\system\create\qml\NewModelDialog.qml.

**Comment by JulianGro** [comment]
> It would be possible to validate the file extension (.gbx, .glb, .gltf, .obj, .gz) in the New Model Entity dialog. For example, only enable the "Create" button if the URL entered ends with one of these extensions - no error dialog required.)
> 
> ![new-model-entity](https://user-images.githubusercontent.com/7455448/95053101-706c8080-074c-11eb-81cb-d9a95489281d.png)
> 
> Dialog is implemented in \scripts\system\create\qml\NewModelDialog.qml.

There seems to be people who name their files weirdly. Like mmm.fbx?1
Not sure if this kind of thing is for cache busting or they just use mega weird programs.

**Comment by Aitolda** [comment]
> There seems to be people who name their files weirdly. Like mmm.fbx?1
> Not sure if this kind of thing is for cache busting or they just use mega weird programs.

It's almost always Cache busting.  However, that's usually at a later stage in the properties tab of the create menu.  Not sure if that would impact this.

**Comment by AleziaKurdis** [comment]
If you want absolutely to do this, then it should be only a **warning**. It should not prevent people to use files with any other extensions than those described. I would like to continue to be able to put a .php  
Or even a .txt if I decide to store my fbx with a txt extension for any reason of my own. (which is working by the way)

The point here is not to be restrictive, but to make this easier for people to figure out how it works.

**Comment by AleziaKurdis** [comment]
Listing the type of expected files directly on the UI would be enough IMO.

Model URL (.gbx, .glb, .gltf, .obj, .gz)

Same in the tooltip for the Property tab.

**Comment by ctrlaltdavid** [comment]
> If you want absolutely to do this, then it should be only a **warning**. It should not prevent people to use files with any other extensions than those described. I would like to continue to be able to put a .php
> Or even a .txt if I decide to store my fbx with a txt extension for any reason of my own. (which is working by the way)
Interesting! I confirmed in the code that it detects the file type by reading the start of the file data rather than going by file extension.

**Comment by AleziaKurdis** [comment]
That's how URL are working. It's like that all over the web.
It's not the url that makes the file type.
and the green box is already your error message (as the broken image icon is for the web)
We only have to be informative about the file types that are supported. (this would be helpful)

**Comment by Aitolda** [comment]
I guess I hadn't anticipated someone using it this way.  If this is the case, then I guess we should just list file types and call it a day.  Doesn't necesssary do what I'd hoped, but it's at least one more clue as to what might be wrong.

**Comment by Aitolda** [comment]
This issue was addressed in [PR#833](https://github.com/vircadia/vircadia/pull/833)
