### ISSUE TITLE
Fix VR HUD to correctly follow user's orientation.

### ISSUE THREAD

**Issue by kasenvr** [vircadia/vircadia#732]
This will help make it usable for VR users so that it's not always out of the way.

**Comment by JulianGro** [comment]
"out of the way"
Every time the keyboard opens up, it spawns inside my armrest..

**Comment by SilverfishVR** [comment]
The idea of the HUD is fine, the current implementation in VR is just not great.

ctrlaltdavid asked in discord: 
>Is the problem just that the "field of view" of the HUD is just too wide (goes from <-90deg through >90 deg). Or does it sometimes get confused (i.e.., centre of the HUD is significantly off axis)?

1. It actually seems to be more than 180deg, but that is really not a problem unless the app using it does not account for that, an example of that is the chat app "quick input" aka  press enter to type, that is full width so in VR it wraps around you like a tutu you never really wanted, and can only be dismissed by finding your keyboard.
2. off axis? yes, sort of. the way it works is that is follows rotation and movement you do with the controllers, but not irl movements like physically turning around or walking, so I can walk out of the HUD center and when I get far enough away, it tries to recenter it, and sometimes it works, and sometimes it ends up somewhere else, where I can't see it.

One common quirk is that it seems to set "forward" to whatever way the HMD was pointing when VR mode is activated (putting the HMD on), I think maybe that should always be the playspace forward.

here is a cringy video of me trying to use the HUD: https://silverfish-freestuff.s3.eu-north-1.amazonaws.com/TestStuff/HUD0001-4513.mp4

**Comment by ctrlaltdavid** [comment]
Problems include:
- HUD overlay not recentering on your avatar while you move in the real world until you reach the HUD surface.
- HUD overlay not reorienting per your avatar while you rotate in the real world.

Additionally:
- The HUD overlay may be considered too close at only 1m away.
- The horizontal angle of the HUD overlay surface is coinsiderably too large. (The vertical angle may also be considered to large.)
