### ISSUE TITLE
Rebuild a new default windows build for Qt

### ISSUE THREAD

**Issue by odysseus654** [vircadia/vircadia#734]
Currently when building on windows the system downloads Qt libraries rather than building them (especially since building Qt takes so much time to do).  However this hasn't been done for quite some time and some issues are emerging:
- Some signs during debugging that Qt is built against such an old version of Visual Studio that it is using its own CRT (and its own heap, and its own exception handlers), and doesn't really talk with the rest of the system
- We're missing .PDB files which would permit us to debug *into* Qt during development.

Please create a new Qt under an updated version of Visual Studio, likely "registering" it as the new version of Windows Qt.

**Comment by daleglass** [comment]
I'm currently working on getting the code to work with the latest Qt, maybe it would make sense to wait until that's done?

But yes, this needs doing anyway.
