### ISSUE TITLE
Some avatars sink into ground

### ISSUE THREAD

**Issue by SilverfishVR** [vircadia/vircadia#735]
the keyword here is "some" and I can't seem to figure out what the difference is.

So far I have found out that it mostly applies to these animation roles:
* altIdle1 (idle_LFF_all.fbx)
* alt1ToMasterIdle (idle_LFF_all.fbx)
* altIdle2 (idle_RFF_all.fbx)
* alt2ToMasterIdle (idle_RFF_all.fbx)
* walkFwdRun_c (run_fast_fwd.fbx)
* walkFwdJog_c (jog_fwd.fbx)

I think the idle animations is the most glaring issue is the sinking in when idle, it can be solved by assigning altIdle 1+2 states to one of the other idle animations (idle.fbx) but it really is a hack, I still have no real answer as to why those are different from the other animations. Animation JSON that has idle 1+2 reassigned:
https://silverfish-freestuff.s3.eu-north-1.amazonaws.com/TestStuff/avatar-animation_idleTest.json

For the forward running animation I tried poking at it and move bones around and I maybe make it a bit better, but I'm a bit over my head here I think, so nothing I would propose as a solution.

**Comment by JulianGro** [comment]
I see every avatar sink into the ground on some animations.
On that new island world we had the Meeting in yesterday, my avatar was actually in the ground to its upper legs, but I think that is an unrelated issue.

**Comment by SilverfishVR** [comment]
Still sinking. I think the issue arose when a bunch of animations was changed/added shortly before hifi gave up, so maybe reverting to the old animation json could solve it for now?
