### ISSUE TITLE
Add tab/right arrow autocomplete to Explore

### ISSUE THREAD

**Issue by kasenvr** [vircadia/vircadia#750]

**Comment by JulianGro** [comment]
How would it autocomplete? Is it supposed to remember all addresses you have been to and make a suggestion like an internet browser does?

**Comment by kasenvr** [comment]
I'm thinking more like as it filters through the list of places... pressing tab will auto-fill to the first domain in that list.

**Comment by JulianGro** [comment]
Why would you want to do that though? It is already the first domain in the list, so autocompleting it does not get you a better result.

**Comment by kasenvr** [comment]
It lets you indicate to the app that you want to go to that world without having to move your hand from the keyboard, it's a quickness sort of thing. :)

**Comment by JulianGro** [comment]
So you don't want to just autocomplete, you want it to go to the world when you press enter and there is only one result as well?
