### ISSUE TITLE
Users sometimes stuck underground

### ISSUE THREAD

**Issue by JulianGro** [vircadia/vircadia#757]
When a user loads into a domain for the first time, it can happen that they sink under the floor, spawn in the floor, etc.
This happened quite often on the Santa Fe event, which makes me think that the frequency of it happening might be connected to bandwidth or machine performance.

I am not sure what exactly causes this. Maybe avatars falling before the collision has been fully loaded?

**Comment by SilverfishVR** [comment]
With no technical insight, I would agree it seems like the collision not being loaded when the avatar drops seems to be the problem, for some cases it helps to have a shape entity under the default spawn point helps, but, when people spawn in where they were when they closed interface (default setting) they could spawn anywhere.
currently, when spawning in people seem to be in a paused "falling" state, what determines when they actually drop?

**Comment by JulianGro** [comment]
For me putting a box under the spawn point actually never helped. I would just spawn under the box as well.

**Comment by daleglass** [comment]
This needs a bit more investigation about what exactly is involved. Does this happen more in some domains? Is it affected by issues of bandwidth/performance? Does it depend whether the spawn point makes the avatar collide with anything?

**Comment by JulianGro** [comment]
I actually just had this on my test machine.
When joining the hub for the first time, I feel under the sea floor.
Maybe physics were calculated before the entity list was fully loaded? Normally when the close entities (and their collisions) aren't loaded you just freeze.
There seem to be two issues now though. One is immediately spawning underground and one is falling before the floor is loaded.
