### ISSUE TITLE
MP3 audio needs to have the first frame of audio be silence in order to avoid static

### ISSUE THREAD

**Issue by kasenvr** [vircadia/vircadia#758]
We're not sure why it happens yet.

**Comment by JulianGro** [comment]
Are we sure this actually is a thing?
It happens pretty often on those freeware mp3 converters for windows that the fuck up the conversion and add stuff like that.

**Comment by kasenvr** [comment]
Would be good to have reproductions that don't cause this to compare? I know people have talked about it for a while here and there.

**Comment by daleglass** [comment]
Also, is this OS dependent?
