### ISSUE TITLE
Can't delete place from server settings page

### ISSUE THREAD

**Issue by ctrlaltdavid** [vircadia/vircadia#759]
Started RC1 server after clearing out AppData..
It got assigned a temporary place name.
Created a "real" placename in the Metaverse dashboard.
Added it as a place under "Places"  in the server settings page.
Tried deleting temporary place name in the server settings page. ... Couldn't. :frowning: ... Error dialog displayed.
But I could delete it in the Metaverse dashboard, whereupon it disappeared from the server settings page list of Places.

**Comment by ctrlaltdavid** [comment]
I note that in HiFi's implementation, there was no "x" button to delete a place name nor a "+" button to add a place name. Presumably adding/deleting was all done from the link above the table, point to the Metaverse dashboard.

**Comment by digisomni** [comment]
These controls have now been hidden.
