### ISSUE TITLE
Stutter/slowdown during avatar scaling.

### ISSUE THREAD

**Issue by Aitolda** [vircadia/vircadia#77]
When a user rescales their avatar, they will notice a dramatic reduction in gamerate until the finished.  This was not always an issue and may have appeared when more advanced avatar collisions were implemented.

1. Open avatar app and click the settings icon on the top right.
2. Drag the avatar scale slider and observe.

Thoughts:
This may be due to physics calcutions on detailed avatar collisions. If so, it might be able to default to pill collision only while in the process of scaling, waiting to calculate detailed collision until scaling is finished.

**Comment by ctrlaltdavid** [comment]
See also: https://github.com/kasenvr/project-athena/issues/48

**Comment by SilverfishVR** [comment]
In VR, it is currently outright useless. Trying to scale yourself with a slider, on a tablet that scales at a different rate than you is like trying paint the mona lisa with a angry ferret, very frustrating and the result is not at all what you wanted

**Comment by Aitolda** [comment]
Revisiting as of Vircadia Eos 2021.1.0.  This is still an issue.

Thought: Perhaps physics could be disabled temporarily while resizing?

**Comment by daleglass** [comment]
Dev meeting: seems to have gotten better
