### ISSUE TITLE
Feature Request: If zone is parent, then children use "Render with Zone" applied to parent zone.

### ISSUE THREAD

**Issue by Aitolda** [vircadia/vircadia#774]
History:  I'm sitting here working on a project where I have 50 identical objects each within a zone, and each needs to be visible ONLY when in their own independent zone.  Currently, the only way to do this is to manually add a zone occlusion for all 50 items one by one.  VERY tedious copy and pasting. It occured to me that if the to be occluded item was automatically using "render with zone" if a child of said zone, a simple ctrl drag and copy would make this a million itmes easier,  But then it also occuried to be that this feature woulld be VERY usefull when creating pseudo LOD environments. Lets say you have a chunk of land, and all items within are meant to show only when in this zone (perhaps you have a low poly doppleganger for each item in the same position it could easily swap out.

The other low poly versions would still need to have all other zones added to their list, but I have another solution for this which will be my next feature request.  (a one click option to "add all zones" in the render with zones section).

Pairs with [775](https://github.com/kasenvr/project-athena/issues/775)

**Comment by JulianGro** [comment]
I think you can already just select all of them and use set render within zone for all of them.
At the very least it *should* be that way.

**Comment by Aitolda** [comment]
> I think you can already just select all of them and use set render within zone for all of them.
> At the very least it _should_ be that way.

Can you show me? I don't seem to have that option.

Revisiting and updating tag.

**Comment by Aitolda** [comment]
This is no longer a concern.
