### ISSUE TITLE
Feature Request: Add "Add all zones" section to render with zones.

### ISSUE THREAD

**Issue by Aitolda** [vircadia/vircadia#775]
While it may seem like this is the case by default, sometimes you might want to occlude from one or a few select zones.  If you have a ton of zones, it's much easier to add all, then remove a few, then to manually add every single one you want.

Pairs with [774](https://github.com/kasenvr/project-athena/issues/774)

**Comment by AleziaKurdis** [comment]
I wonder what would be best:
- A “**Select All**” on the UI
or
- A way to indicate to the system: “**All but these...**”. So it would inverse the behavior base on the provided list of zones.

if we address it by the UI using a "Select All", the property might have a possibly huge list of zones.
I can be wrong, but the smaller is that list, the faster it can be processed. 
(Maybe Sam can tell us)

**Comment by Aitolda** [comment]
As of 2021.1.0 Eos this has not yet been addressed.
@HifiExperiments do you have any thoughts on this?

Revisiting and updating tag.

**Comment by HifiExperiments** [comment]
I do think that we need to add some additional features to augment renderWithZones to make it easier to do things like this...I don’t know if that’s dontRenderWithZones/renderWithoutZones or something else...some other ideas were presented here but I haven’t had time to process all of it: https://github.com/vircadia/vircadia/issues/351

performance-wise renderWithZones is super fast, so adding more to the list isn’t a huge issue.  the one issue is eventually you’d hit the packet size limit, but *eventually* we should be able to fix that too.

maybe for now, I might suggest doing this in create just for ease of use, but long term, we can think about additional properties?

**Comment by AleziaKurdis** [comment]
This is now a bit more achievable with the recent change to the zone selector.

**Comment by Aitolda** [comment]
> This is now a bit more achievable with the recent change to the zone selector.

Very cool.

**Comment by AleziaKurdis** [comment]
Addressed by this PR: https://github.com/vircadia/vircadia/pull/1519
I'm closing this issue.
