### ISSUE TITLE
Trying to make Production Build on Windows w/out code signing certs fails

### ISSUE THREAD

**Issue by kasenvr** [vircadia/vircadia#783]
The if statements don't appear to be working correctly, however PR builds still build fine... so maybe the code there can offer hints.

Reported by: Darling (not confirmed by me)

**Comment by daleglass** [comment]
Needs more info about what exactly fails. What's the error message?

**Comment by ctrlaltdavid** [comment]
I have seen this while working on removing the "Console" option from Interface-only installer builds. And I have a fix for it.
