### ISSUE TITLE
DPI fractional scaling is handled poorly

### ISSUE THREAD

**Issue by Kezii** [vircadia/vircadia#794]
OS: Linux, X11
When using the game with fracional scaling configured (for example: 125% instead of 100%), the game graphics is wrongly draw

![immagine](https://user-images.githubusercontent.com/3357750/95641898-5eb90f00-0aa5-11eb-9a05-d221b37afdaf.png)

**Comment by JulianGro** [comment]
For clarity, this works fine on 200% dpi.
It is also unclear if this happens on Windows or not. Most people on Windows wouldn't use fractional dpi scaling because it doesn't work that well.

**Comment by daleglass** [comment]
A bit more info would be nice to see if this only happens on Linux or also on other operating system

**Comment by daleglass** [comment]
Dev meeting report: 125 works on Windows. Might be Linux specific then

**Comment by JulianGro** [comment]
They have an AMD card with Mesa 20.2.0-2

**Comment by Kezii** [comment]
```
                   -`                    kezi@desktop 
                  .o+`                   ------------ 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Kernel: 5.8.14-arch1-1 
               `+oooooo:                 Uptime: 2 hours, 30 mins 
               -+oooooo+:                Packages: 2294 (pacman) 
             `/:-:++oooo+:               Shell: fish 3.1.2 
            `/++++/+++++++:              Resolution: 3840x2160, 3840x2160, 3840x2160 
           `/++++++++++++++:             DE: Plasma 5.19.5 
          `/+++ooooooooooooo/`           WM: KWin 
         ./ooosssso++osssssso+`          WM Theme: Brezza 
        .oossssso-````/ossssss+`         Theme: Breeze [Plasma], Breeze [GTK2/3] 
       -osssssso.      :ssssssso.        Icons: breeze [Plasma], breeze [GTK2/3] 
      :osssssss/        osssso+++.       Terminal: yakuake 
     /ossssssss/        +ssssooo/-       CPU: AMD Ryzen 5 1600X (12) @ 3.600GHz 
   `/ossssso+/:-        -:/+osssso+-     GPU: AMD ATI Radeon RX 470/480/570/570X/580/580X/590 
  `+sso+:-`                 `.-/+oso:    Memory: 16676MiB / 32102MiB 
 `++:.                           `-/+/
 .`                                 `/                           ```

```

```
pacman -Qi mesa
Name            : mesa
Version         : 20.2.0-2
```

**Comment by asdf512** [comment]
I had a quick read of the QT documentation on High DPI scaling [https://doc.qt.io/qt-5/highdpi.html](url). 

I notice that launchers/qt/src/main.cpp:33 is using the AA_EnableHighDpiScaling automatic scaling based on pixel density. It seems for window based system coordinate, AA_DisableHighDpiScaling should be used

We know DPI scaling is working for 200%. I'd be interested in seeing if highDpiScaleFactorRoundingPolicy, a rounding fractional scaling method, solves this issue.

**Comment by JulianGro** [comment]
> I notice that launchers/qt/src/main.cpp:33 is using the AA_EnableHighDpiScaling automatic scaling based on pixel density. It seems for window based system coordinate, AA_DisableHighDpiScaling should be used

The launchers folder actually only contains unused launcher code.
I would assume that the only places were code that would affect this would be /interface and /libraries
Personally I would take a look at /libraries/display-plugins. In there is some code which looks interesting like getRecommendedUiSize() and getRecommendedRenderSize() in OpenGLDisplayPlugin.h

**Comment by JulianGro** [comment]
Since there is a devicePixelRatio() in the OpenGLDisplayPlugin, I would assume that is is supposed to be DPI aware. Maybe getting the DPI is window system specific? If so it would make sense that it doesn't work on Linux.

![Bildschirmfoto vom 2020-12-24 08-54-30](https://user-images.githubusercontent.com/11144627/103072642-4053b180-45c6-11eb-9514-665fa5fa216c.png)

**Comment by JulianGro** [comment]
There is actually some interesting behaviour to see here. As shown above on Linux Mint 19.3 the Vircadia clients UI doesn't actually scale with the scale set by the system.
On Kubuntu 20.10 on the other hand it does scale. The 3d rendered stuff has the right resolution, but all the Qt UI stuff is upscaled an blurry, even the inside of the webengine like on ctrl + b. So it *seems* that KDE has a more forceful way of upscaling.

**Comment by daleglass** [comment]
We have a report of the scaling issue in the first screenshot also happening under Windows with fractional scaling.

**Comment by Victor239** [comment]
Just had this issue myself when trying to test the application.  I was quite confused why the display sizing was off and I was unable to click "Continue". Kubuntu 20.10, KDE Plasma 5.19.5, 1920x1080.

 ![](https://i.imgur.com/I8NB2mA.png)

**Comment by JulianGro** [comment]
yes :angry:

**Comment by mrkcdf** [comment]
This is still an issue, on top of that, cursor X/Y is off big time when the scaling issue is present.  I've forked the repo and will aim to raise a pull request later this evening with a proposed fix

**Comment by mrkcdf** [comment]
That being said - it might not be a bad idea to perhaps introduce a feature where the user can override the scaling via config, falling back to `QApplication::desktop()->devicePixelRatioF()` if not present

**Comment by mrkcdf** [comment]
https://github.com/vircadia/vircadia/pull/1575
