### ISSUE TITLE
Flying speed reduces when releasing the 'W' button

### ISSUE THREAD

**Issue by Akira-Kuru** [vircadia/vircadia#80]
When flying, pressing forward and clicking shift speeds you up slowly and builds up momentum.
When releasing the 'W' button the speed drops down to zero and it slowly needs to be built back up.

Is it possible to have a consistent speed without building up momentum? When flying the speed should always be the same and would remove the use of shift.

**Comment by kasenvr** [comment]
A toggle for that feature might be good. Would go under settings somewhere.
