### ISSUE TITLE
Disable QML if run inside apitrace

### ISSUE THREAD

**Issue by JulianGro** [vircadia/vircadia#809]
The Interface crashes when being run in apitrace with QML enabled.
There is already code to disable QML when the Interface notices being run in Nvidia Nsight.
Nvidia Nsight is pretty complicated software, especially on Linux, so an easy alternative like apitrace is important.
(We also haven't been able to run the Interface in Nvidia Nsight without crashing on Linux yet)

**Comment by daleglass** [comment]
Maybe a commandline parameter for this?
