### ISSUE TITLE
Feature: Portal dropper default script

### ISSUE THREAD

**Issue by two-one-five** [vircadia/vircadia#81]
What it would look like...
* Open Explore app.
* Hover over a place and you'll get buttons, but amongst those will be a portal button.
* Clicking the portal button will send a message over the mixer for everyone to see a portal at the coordinate, which would be a local entity.
* Walk into the local entity and you'll get sent to wherever the destination was of that portal (since it'll be in the userData of the entity.)

**Comment by daleglass** [comment]
See if anybody has an already usable script

**Comment by daleglass** [comment]
Seems worth asking around and seeing if anybody can contribute something

**Comment by daleglass** [comment]
Still an issue
