### ISSUE TITLE
Update Explore app to work with metaverse places

### ISSUE THREAD

**Issue by ctrlaltdavid** [vircadia/vircadia#815]

**Comment by daleglass** [comment]
Dev meeting: are we planning to keep the beacons?

**Comment by JulianGro** [comment]
Maybe set the spawnpoint of a place with a beacon? (Updating it when moved?)

**Comment by digisomni** [comment]
This will happen with a "Places" component imported from the Web Interface.

**Comment by digisomni** [comment]
Completed.
