### ISSUE TITLE
When creating a domainID, if there are any errors the dialog does not exit

### ISSUE THREAD

**Issue by Misterblue** [vircadia/vircadia#820]
When setting up a domain and creating a new domainID (domain-server settings page under "Advanced Settings"), if there are any errors with the API request, the dialog just keeps going around and it does not terminate or report the error. The most common error would be having illegal characters in the domain name (like spaces or most special characters).

The API request reports the error:
procAllDebug: POST /api/v1/domains
procAllDebug: body: {"domain":{"label":"Next door"}}
setupMetaverseAPI: created new session for 172.17.0.3:41582
finishMetaverseAPI: response: {"status":"failure","error":"name contains not allowed characters"}

**Comment by kasenvr** [comment]
This has been fixed with the wizard but not with the button in the main server settings.

**Comment by digisomni** [comment]
It's fixed now! :)
