### ISSUE TITLE
VR head position constantly being "corrected"

### ISSUE THREAD

**Issue by JulianGro** [vircadia/vircadia#825]
When you move you head in VR vertically, Interface will move it back into the position it would have if you were standing.
Not only is this extremely disorienting even for veteran VR users, but you cannot move your head down to pick stuff up, look at a small person, sit down, etc.
Interestingly this also happens when trackers are enabled, so even if you are laying on the floor, Interface will move your laying avatar into the air.

Oculus should have a way to give Interface the height of the user. (At least this was part of the calibration process when I still had an Oculus)
SteamVR does not have data on the user height, so we would need to have people either set their real life height or have them calibrate their height. We could add a wizard that asks this when we are missing the info in VR. Recalibration or changing the height could be done in the controls menu.

**Comment by ctrlaltdavid** [comment]
This behaviour happens with Oculus, too.

**Comment by HifiExperiments** [comment]
I might be wrong but isn’t there a setting for sitting vs room scale VR or something like that?

**Comment by JulianGro** [comment]
> I might be wrong but isn’t there a setting for sitting vs room scale VR or something like that?

There is a setting that makes your head position absolute, but that leaves your body anchored to the middle of the playspace.
So if you use that setting and move in real life, your avatar will just bend unrealistically.

**Comment by ctrlaltdavid** [comment]
Settings ? Controls... has some options that should already be able to control this as required by user for different situations: Auto / Seated / Standing. C.f. behaviour with documentation and what is wanted.
