### ISSUE TITLE
Press "T" to push to talk cancels out emotes

### ISSUE THREAD

**Issue by Akira-Kuru** [vircadia/vircadia#83]
When enabling push to talk while emoting "sit" for example, cancels out the emote whenever you press "T" to talk. 

- Keybinding the push to talk button would resolve the issue.
- Having sit as a general movement then an emote would also resolve the issue.

**Comment by daleglass** [comment]
Dev Meeting: Madders is working on a new emote app, may solve this issue

**Comment by digisomni** [comment]
Madders is still working on this. :)
