### ISSUE TITLE
Feature: enhanced avatar *.fst file

### ISSUE THREAD

**Issue by SilverfishVR** [vircadia/vircadia#84]
Triggered by the demise of the marketplace, but really I always found it weird that, for example, the thumbnail images was handled as a separate thing so only marketplace avatar bookmarks has thumbnails (I know, the wolf3d avatars have no nails at all :-).

For a future with multiple marketplaces and better avatar apps I think it makes sense to put as much 'avatar specific' data as possible into the *.fst file.

For now, I suggest just deciding on what fields we want in there and extending the FST reader to support them, and maybe extend the avatar packager to write them, it won't break anything now since they are optional but they will be ready for future apps to leverage.

As far as I can tell, currently supprted fields are:

```
FST_VERSION = 1;
FST_VERSION_FIELD = "version";
NAME_FIELD = "name";
TYPE_FIELD = "type";
FILENAME_FIELD = "filename";
MARKETPLACE_ID_FIELD = "marketplaceID";
TEXDIR_FIELD = "texdir";
LOD_FIELD = "lod";
JOINT_INDEX_FIELD = "jointIndex";
SCALE_FIELD = "scale";
TRANSLATION_X_FIELD = "tx";
TRANSLATION_Y_FIELD = "ty";
TRANSLATION_Z_FIELD = "tz";
JOINT_FIELD = "joint";
BLENDSHAPE_FIELD = "bs";
SCRIPT_FIELD = "script";
JOINT_NAME_MAPPING_FIELD = "jointMap";
MATERIAL_MAPPING_FIELD = "materialMap";
COMMENT_FIELD = "comment";
```
All of which are optional, except for "filename".

I propose adding:

- "image" or "thumbnail" maybe both?: relative or absolute image url. could also be useful in people/friends apps since the current user thumbnails are hifi dependent.

- "description": there is already a (unused) comment field but I see this more like the stuff you would put in the marketplace description, could it support some kind of markup?

- "licence" or "attribution": would this be sufficient for avatars that require attribution?

- "viewpoint": currently users can select between "Head" and "Eyes" in the avatar app, but it really depends on the avatar which works best so it really should be an 'avatar' option rather than an 'user' option. And maybe... just maybe, it could be also be a vec3 to give avatar creators full control.

- "animationLoop": I can elaborate if needed but basically a way to add non-overriding & non-rolebased looping animations to wings/tails/tentacles/antennae/lewd appendages etc. It is up to the avatar creator to ensure that it does not clash with the role animations or IK controlled joints.
- ideas?

**Comment by MarcusLlewellyn** [comment]
This PR builds and runs correctly on the following platforms:
```
Visual Studio 2019 Community Edition 16.4.1
CMake 3.16.0
Windows 10 Pro 1909 Build 18363.535
AMD Ryzen 7 1800x Eight-Core 3.6GHz
Nvidia GeForce GTX 1080 Driver Version 441.08 Standard

gcc/g++ 7.4.0
CMake 3.10.2
Ubuntu 18.04 bionic Kernel x86_64 Linux 5.0.0-37-generic
Intel Core i7-4700MQ Four-Core 3.4GHz
Nvidia GeForce GT 750M Driver Version 390.116
```

**Comment by digisomni** [comment]
This still seems like a good idea.

**Comment by daleglass** [comment]
If we're going to make significant changes here, it'd probably be good to convert to JSON as well

**Comment by SilverfishVR** [comment]
> If we're going to make significant changes here, it'd probably be good to convert to JSON as well

sure but only if it somehow makes it better or adds needed functionality, otherwise it is just unnecessarily complicating things. It is already quite un-intuitive that everything is JSON files, you sort of have to open (and understand) a file in order to know how to use it.

**Comment by AleziaKurdis** [comment]
Is it going to be backward compatible ?

**Comment by daleglass** [comment]
My personal idea would be to replace the fst with a new json format, and leave the old code around for backwards compatibility.

JSON just seems like a far better and more flexible format for this purpose:

* We don't need our own parsing code
* Can have tree shaped structures and lists (which already hackily exist in flow data)
* Can have multi-line descriptions
* Can classify things better. Eg, by redoing things with a tree structure we can categorize things, so the code can react differently to unknown data depending on where it is.
* Can better support user data. You just put all of that into "user_data", and know that there won't ever be a conflict with C++ code.

**Comment by AleziaKurdis** [comment]
What about a .fst file extension with a json object structure?
Cause I think having a .json file extension might be confusing at some point... and a lot of work to change.
(I can be wrong)
For sure, an object structure will be way better... minimally for material... cause, currently, it has to be all in one line and it's a mess.
