### ISSUE TITLE
Shape Entity: Broken display when alpha is set.

### ISSUE THREAD

**Issue by AleziaKurdis** [vircadia/vircadia#850]
If you go at this location: 
http://metaverse.bashora.com/explore/limbo.php
and do a "Reload Content", the shape entities that are using material entity with alpha
become badly rendered.

Normally:
![image](https://user-images.githubusercontent.com/60075796/97793639-00bfa900-1bc5-11eb-892d-637e61aa7a68.png)

If the Content has been reloaded:
![image](https://user-images.githubusercontent.com/60075796/97793642-146b0f80-1bc5-11eb-94d2-dbf34c90024a.png)

**Comment by HifiExperiments** [comment]
@AleziaKurdis I think this is fixed by the linked PR!

**Comment by digisomni** [comment]
Looks good to me in PR #830!
