### ISSUE TITLE
nvtt (nvidia-texture-tools) fails to compile on Fedora 33: fatal error: sys/sysctl.h: No such file or directory

### ISSUE THREAD

**Issue by daleglass** [vircadia/vircadia#862]
This is a bit of an odd one. It compiled on Fedora 31 and 32, on 33 it fails with this:

```
/usr/lib64/ccache/c++  -I/home/dale/Vircadia/vcpkg/bd824a32/buildtrees/nvtt/src/70a4ed56c2-ae979c4acf/src -Isrc -I/home/dale/Vircadia/vcpkg/bd824a32/buildtrees/nvtt/src    /70a4ed56c2-ae979c4acf/extern/poshlib -I/home/dale/Vircadia/vcpkg/bd824a32/buildtrees/nvtt/src/70a4ed56c2-ae979c4acf/extern/stb -I/home/dale/Vircadia/vcpkg/bd824a32/bui    ldtrees/nvtt/src/70a4ed56c2-ae979c4acf/src/nvthread -fPIC -march=athlon64 -fPIC -g -fPIC -std=gnu++11 -MD -MT src/nvthread/CMakeFiles/nvthread.dir/nvthread.cpp.o -MF src/    nvthread/CMakeFiles/nvthread.dir/nvthread.cpp.o.d -o src/nvthread/CMakeFiles/nvthread.dir/nvthread.cpp.o -c /home/dale/Vircadia/vcpkg/bd824a32/buildtrees/nvtt/src/70a4ed    56c2-ae979c4acf/src/nvthread/nvthread.cpp
 16 /home/dale/Vircadia/vcpkg/bd824a32/buildtrees/nvtt/src/70a4ed56c2-ae979c4acf/src/nvthread/nvthread.cpp:14:10: fatal error: sys/sysctl.h: No such file or directory
 17    14 | #include <sys/sysctl.h>
 18       |          ^~~~~~~~~~~~~~
```

Indeed there's no such file, the correct one would be:

    #include <linux/sysctl.h>

 Looking at the latest nvtt code shows a change has been made to address this:

https://github.com/castano/nvidia-texture-tools/blob/248f84ca465ab15a5d5c23d97cb90c74633b38cb/src/nvthread/nvthread.cpp#L12

It could be time to upgrade our NVTT source to a more recent version.

**Comment by daleglass** [comment]
still an issue I think. Though NVTT is deprecated and should be replaced with something else, perhaps as per #1087

**Comment by JulianGro** [comment]
I had fixed it on aarch64 with a patch, but left it for amd64 since I didn't have any problems and either forgot about this issue or worked on it before this issue.
https://github.com/vircadia/vircadia/blob/master/cmake/ports/nvtt/portfile.cmake
