### ISSUE TITLE
Domain-Server does not send IP address and port with heartbeat

### ISSUE THREAD

**Issue by kasenvr** [vircadia/vircadia#865]
Why is this? Why can't we just send the IP address and various networking information in each heartbeat?

**Comment by ctrlaltdavid** [comment]
Send the currently known IP address and port (i.e., the address and port sent at start-up / domain change)? Or re-verify IP address and port each heartbeat?

**Comment by kasenvr** [comment]
I imagine the danger in re-verifying is that you would have to spam outside servers to confirm what your public IP and ports are?

**Comment by thoys** [comment]
Wouldn't a webrequest include the ip of its sender already?

**Comment by Misterblue** [comment]
There can be proxies, reverse-proxies, firewalls, Tor networks, and other translations between the domain-server and the metaverse-server so the originating IP address is not always available. Even then, the inbound port number isn't reported.
