### ISSUE TITLE
Security: Domain-Server WebUI is unsecure by default

### ISSUE THREAD

**Issue by JulianGro** [vircadia/vircadia#867]
The Domain-Servers WebUI does not ask you to set a password and gives you no indication that it is open to everyone on the internet. It should not allow you to continue without a password unless you really know what you are doing. (closed the port to the outside) In theory we could also check to see that the port is closed to the Internet.

**Comment by kasenvr** [comment]
The proper place to handle this would be in the wizard, however we should also add to the docs a short tutorial on how to force a password reset (even if that means deleting your server settings/content) in the event that you forgot your password or set the wrong one by mistake.

**Comment by daleglass** [comment]
My suggestion is that on the first startup, the server should generate a random password, store it somewhere (like a file) and require the user to get it from there. This way there's never a moment where the access is open to all.

**Comment by digisomni** [comment]
This does not get solved by #1429 but it's a start.

**Comment by digisomni** [comment]
Whoops, I misread (thinking SSL vs password.)

**Comment by digisomni** [comment]
This has been solved by the wizard somewhat where the password is asked to be set during the wizard. If it's still desired to have a random password set by default (might be tricky regarding a user forgetting to copy down the password) then we should open a new issue with that exact request.
