### ISSUE TITLE
Low game and render rates on Linux

### ISSUE THREAD

**Issue by JulianGro** [vircadia/vircadia#898]
The game and render rates are much lower than on Windows.
On Windows 10 the game and render rates are essentially always hitting the target rate, hovering between 60 and 65.
On Linux Mint 19.3 the game rate hovers around 33 and the render rate around 21.
This is in the same domain (The Hub) and on the same machine. The cpu power saving on my Linux installation is even less aggressive than on Windows 10.

Even though the game rate and the render rate are for different engines, them both showing such a significantly lower performance leads me to think that they might both suffer from the same problem.

Since this is happening on an i7-7800x clocked to 4,7GHz it should be measurable on any other system as well.

Here is some more specific timings:
![vircadia-snap-by-motofckr9k-on-2020-12-03_04-04-55](https://user-images.githubusercontent.com/11144627/100958740-2cfc7b80-351d-11eb-8e59-afdeff07f580.jpg)
![vircadia-snap-by-motofckr9k-on-2020-12-03_04-13-20](https://user-images.githubusercontent.com/11144627/100959159-fb37e480-351d-11eb-8233-1137b5f8251b.jpg)

Shadows disabled:
![vircadia-snap-by-motofckr9k-on-2020-12-03_04-19-31](https://user-images.githubusercontent.com/11144627/100959556-ddb74a80-351e-11eb-83d8-77816ce72d6e.jpg)

**Comment by kasenvr** [comment]
Can confirm that I tested this on PopOS 20.10 just today and it was quite laggy, the FPS was hanging around 30 the whole time even though I had the graphics preset on "high".

**Comment by JulianGro** [comment]
Since it always keeps at 31 FPS and doesn't seem to dip down even when I deliberately slow it down, I assume it might be some sort of artificial limit. The performance does still seem lower than on Windows, but maybe that is also just because it is aiming for a lower value.

**Comment by JulianGro** [comment]
A little comparison:
i7-7800x 4,8GHz Linux Mint 19.3:
![1Auswahl_809](https://user-images.githubusercontent.com/11144627/103341957-873f1c80-4a88-11eb-9889-12667528df31.png)

i7-2600 ~3,5GHz Windows 10:
![vircadia-snap-by--on-2020-12-30_05-09-16](https://user-images.githubusercontent.com/11144627/103342020-b81f5180-4a88-11eb-9263-06a4768ece9d.jpg)

Both are in similar locations and looking into similar directions.

**Comment by JulianGro** [comment]
Someone suggested this might be some sort of Kernel scheduling issue. I tried a xanmod Kernel with the same results.

**Comment by shocktail39** [comment]
[trace_measureTimingHQ_20210613_2017.json.gz](https://github.com/vircadia/vircadia/files/6644912/trace_measureTimingHQ_20210613_2017.json.gz)
i was asked to run the script too.  a bit about my machine:
-cpu: AMD Ryzen 7 3700x (3.6GHz, 8 cores, 16 threads)
-gpu: AMD RX 580
-os: Gentoo Linux with OpenRC, Xorg, Pipewire, and Vulkan support

**Comment by JulianGro** [comment]
For comparison here: 
[trace_measureTimingHQ_20210614_0207.json.gz](https://github.com/vircadia/vircadia/files/6644947/trace_measureTimingHQ_20210614_0207.json.gz)
CPU: Intel i7-7800x clocked to 4,7GHz
GPU: Nvidia GTX 1080
OS: Linux Mint 19.3

(Keep in mind that these can not be compared too close, since some things like resolution, network speed, cache, etc. will not match up.)

**Comment by shocktail39** [comment]
[trace_measureTimingHQ_20210613_2041.json.gz](https://github.com/vircadia/vircadia/files/6644954/trace_measureTimingHQ_20210613_2041.json.gz)
wait my graphics settings weren't all the way up before.

**Comment by JulianGro** [comment]
Looking at the traces makes this even more confusing.
It looks like the main thread is waiting for something outside for a considerable amount of time. Something that doesn't show up in the traces.
Especially shocktails second trace is weird, since it appears to be waiting for longer than it is actually doing anything.

If anyone else wants to give the benchmark a go, I will leave the server up for probably ages.
[hqBenchmark.zip](https://github.com/vircadia/vircadia/files/6644975/hqBenchmark.zip)
Example command:
```
~/Applications/Vircadia-x86_64-release-latest_d3628349d50a4194f93b4dc0641d449f.AppImage --testScript measureTimingHQ.js
```
Interface will close automatically after the benchmark is finished. Output should be in `~/Documents/traces/`

**Comment by ksuprynowicz** [comment]
I think that PR 1424 fixed this. Should we close it?

**Comment by digisomni** [comment]
I believe it's the same thing, can reopen if it's still an issue afterwards.
