### ISSUE TITLE
Web entities use MOBILE_USER_AGENT instead of WEB_ENGINE_USER_AGENT

### ISSUE THREAD

**Issue by JulianGro** [vircadia/vircadia#913]
Web entities use MOBILE_USER_AGENT instead of WEB_ENGINE_USER_AGENT.
I would think the best thing would be to default to the MOBILE_USER_AGENT and give a entity property to switch to WEB_ENGINE_USER_AGENT.
You can check your user agent here: https://duckduckgo.com/?q=what+is+my+user+agent&ia=answer
It generally seems like a good idea to use a mobile user agent by standard, so that websites hopefully keep some of the heavier elements out, but you will regularly need a desktop user agent to get websites to work.

**Comment by daleglass** [comment]
Dev meeting: it would be good to have a choice over which agent to use on the web entity.

Having a per-entity flag would be a protocol change

**Comment by daleglass** [comment]
It would be useful to think of other things that could be useful to send, like headers specifying the language, or other data web browsers send.

**Comment by digisomni** [comment]
A good way to allow us to specify random headers would be to put this all into one field that's an array or JSON then ship that off.

The Create App can abstract that into multiple fields to the user... but it allows for adding more header control without breaking protocol in the future. It also allows for adding custom headers on a per web entity basis.
