### ISSUE TITLE
Cache busting for scripts (and other assets) needs to be revisited.

### ISSUE THREAD

**Issue by MarcusLlewellyn** [vircadia/vircadia#92]
One of the things we've gotten used to but is really a pain for both experienced and new user alike is that scripts and other objects are aggressively cached, and not updated when new version are present.

**Comment by daleglass** [comment]
Can we have a reproduction for testing and experimenting with this?

**Comment by daleglass** [comment]
Suggestion by Odysseus: have an internal timeout so that if something is requested multiple times really quickly the asset is only requested once

**Comment by daleglass** [comment]
#1012 may address part of this

**Comment by daleglass** [comment]
yes
