### ISSUE TITLE
Create App:  copy/paste coordinates and rotation from one mesh to another.

### ISSUE THREAD

**Issue by Aitolda** [vircadia/vircadia#955]
At the moment the only way to send coordinates and rotation is to manually copy paste every field one by one, which is tedious (I did this more than 100 times today while working on a project).  I recommend we piggyback off the style of other alignment features recently added by Alezia.  Sending the info from the most recent selection to the others.  For example,  1st select the mesh you wish to move.  Hold shift (or control) and select the mesh whose coordinates you wish to copy.  I can imagine 3 different options

1. copy world position from active (last selected)
2. copy world rotation from active (last selected)
3. copy both world position and rotation from active (last selected)

This could be worded differently possibly but you get the idea.

**Comment by ctrlaltdavid** [comment]
Could perhaps have "copy" and "paste" buttons besides field groups (perhaps "C" and "P" to save space). E.g., click on entity, press "C" beside position fields to copy x,y,z position from of that entity, then select target entity and press "P" besides  position fields to paste x,y,z values.

**Comment by Aitolda** [comment]
I'd still like to see this implemented at some point. Very handy.

**Comment by digisomni** [comment]
It would be nice to be able to copy properties. Page builders for web design allow me to do this and I love it. Though, one of the main issues the Create app has is its singular nature. So, when wanting to copy and compare attributes between items, you can't save state or have things take up less space. You can only access and manipulate one item at a time, which is troublesome. So that might be another consideration to have to improve workflow.

**Comment by ctrlaltdavid** [comment]
Could, perhaps, add small "C" and "P" buttons beside the label or input boxes for copy/paste-able fields and/or groups of fields.
If I recall correctly, Second Life editor has/had this which was pretty handy.

**Comment by Aitolda** [comment]
> Could, perhaps, add small "C" and "P" buttons beside the label or input boxes for copy/paste-able fields and/or groups of fields.
> If I recall correctly, Second Life editor has/had this which was pretty handy.

https://ryuutei.files.wordpress.com/2012/10/1-predator.png

**Comment by Aitolda** [comment]
Personally I'm only really interested in location/rotation, individually if possible.  If I want to duplicate all other properties i would likely just make a copy of the entity.

**Comment by AleziaKurdis** [comment]
Would you expect that it copied "position" / "rotation" even in the case where the entity is parented and the localPosition / localRotation are displayed in the UI?

**Comment by Aitolda** [comment]
Truthfully I hadn't really thought about it when it's parented.  I was only thinking about global location.  I'm not sure how much use it would get when parented.

**Comment by AleziaKurdis** [comment]
Location and rotation also exist for parented entities. I can simply ignore the local values. 
So we would need:
Copy location (only available in single selection)
Copy rotation (only available in single selection)
Paste location (enabled only if there is something in memory)
Paste rotation (enabled only if there is something in memory)
