### ISSUE TITLE
GLTF vertex colors from Blender 2.91 broken

### ISSUE THREAD

**Issue by SilverfishVR** [vircadia/vircadia#957]
![glb vertex colors](https://user-images.githubusercontent.com/53531160/103981694-9f96f180-5182-11eb-9716-848d1c18c5fc.png)

In blender 2.91 the GLTF exporter was updated from `"Khronos glTF Blender I/O v1.0.5"` to `"Khronos glTF Blender I/O v1.4.40" `wich changes how vertex colors are defined.
The models look right and validate with [babylonjs.com](https://sandbox.babylonjs.com/)

The specifics of the problem eludes me but it seems, the fine folks over at Godot had the same issue, and fixed it 😄 so that may be a good reference:

The issue: https://github.com/godotengine/godot/issues/44744
The PR: https://github.com/godotengine/godot/pull/44746
The "normalized" property: [GLTF spec](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#accessornormalized)
The models for testing: [vertexColorPanels](https://silverfish-freestuff.s3.eu-north-1.amazonaws.com/index.html?prefix=TestStuff/vertexColorPanel/)  Or load the json for all of them as in picture [panels json](https://silverfish-freestuff.s3.eu-north-1.amazonaws.com/TestStuff/vertexColorPanel/vertexColorPanels.json)

**Comment by Aitolda** [comment]
Ah... Thanks for digging into that.  All I knew was I couldn't combine diffuse with vertex color in this version,, and have reverted to 2.83 as needed.

**Comment by SilverfishVR** [comment]
Also not that, assuming fbx is correct, then the colors on GLTF (pre 2.91) where wrong, dark colors are darker than expected. It could be related to the "normalized" property but I always thought the colorspace was wrong, as in interpreting it as sRGB instead of linear and thus expanding the dark colors, I believe GLTF is always linear for vertex colors.

**Comment by ctrlaltdavid** [comment]
See also: https://github.com/vircadia/vircadia/issues/302
