### ISSUE TITLE
Snapshot no longer creates gif

### ISSUE THREAD

**Issue by Basinsky** [vircadia/vircadia#959]
We used to get a gif when we create a snapshot (shortcut P). Now not anymore. Is it broken or removed?

**Comment by Aitolda** [comment]
I was able to get this working a few days ago, but I had to define a save location first.

**Comment by daleglass** [comment]
Dev meeting: seems shortcut only takes a still, a gif needs using the snap app.
May not be a bug.

**Comment by daleglass** [comment]
On further discussion, doesn't seem to be a bug.
