### ISSUE TITLE
Controls Reference dialog's "Need More Assistance" should open e-mail

### ISSUE THREAD

**Issue by ctrlaltdavid** [vircadia/vircadia#96]
Help > Controls Reference "Need More Assistance" at the bottom of the dialog: clicking this should open an e-mail, same as how clicking "Report Problem" at the top right of the dialog does.

Additionally:
- "Report Problem" should change when hovered.
- "goto this link" should change when hovered.
- "support@projectathena.io" should change when hovered.

**Comment by daleglass** [comment]
Discussion: should link to Discord

We should probably have a separate window for this, rather than having it under "controls reference"
