### ISSUE TITLE
Interface crashes after loading into domain with latest AMD drivers

### ISSUE THREAD

**Issue by nleve** [vircadia/vircadia#964]
Running into a consistent issue where the Interface crashes soon after a domain's world starts showing up on the screen. I previously was able to go to The Hub and NDN World, but now the furthest I can get is taking a step or two before a crash. Interestingly, these worlds consistently crash, but I seem to be able to load into Community Village and Ken's Gallery without crashing.

More troubleshooting detail:
- This occurs in both Desktop and VR modes.
- The tutorial area works fine, no issues.
- This occurs when using the default avatar.
- I've deleted the Vircadia files inside of AppData/Local and AppData/Roaming, with no change.
- Rebooted the PC, no change.

Environment:
- Win10
- CPU: i7 4770k
- GPU: AMD 5700XT
- 16GB RAM

Log file up until a crash when loading into The Hub:
[vircadia-log.txt](https://github.com/vircadia/vircadia/files/5825118/vircadia-log.txt)

Any help appreciated, and happy to collect more data on reproducing this if needed.

**Comment by liberza** [comment]
Here is another log from another attempt. I noticed in this one the final message is the same (`Starve detected, 1 new unfulfilled reads`), but there is a more ominous deadlock message preceding it...
```
[01/16 15:37:34] [DEBUG] [hifi.interface.deadlock] DEADLOCK DETECTED --  lastHeartbeatAge: 120625581 [ lastHeartbeat : 1610829333553402 now: 1610829454178983  ] elapsedMovingAverage: 843 maxElapsed: 120625581 maxElapsedAverage: 843 samples: 372
[01/16 15:37:36] [DEBUG] [hifi.audioclient] Starve detected, 1 new unfulfilled reads
```
[vircadia-log-2.txt](https://github.com/vircadia/vircadia/files/5825133/vircadia-log-2.txt)

**Comment by vegaslon** [comment]
I suggest you try downgrading your AMD graphics driver to previous stable and see if that helps.

**Comment by liberza** [comment]
I'll give that a try. Here are my current driver specs.

Software Version - 2020.1113.1501.27036
Driver Version - 20.45.01.18-201113a-361132C-RadeonSoftwareAdrenalin2020
Provider - Advanced Micro Devices, Inc.
2D Driver Version - 8.1.1.1634
Direct3D® Version - 9.14.10.01471
OpenGL® Version - 26.20.11000.14757
AMD Audio Driver Version - 10.0.1.16
Vulkan™ Driver Version - 2.0.159
Vulkan™ API Version - 1.2.152
Windows Version - Windows 10 (64 bit)

**Comment by JulianGro** [comment]
Deadlocks are pretty normal. I do see a couple of messages I haven't seen before, but the worst looking is:
```
[01/16 15:24:42] [WARNING] [default] An OpenGL Core Profile was requested, but it is not supported on the current platform. Falling back to a non-Core profile. Note that this might cause rendering issues.
```
For one, I find it interesting that Interface even has a non-core profile to fall back to. But your shaders have most likely been generated by OpenGL Core, and a non-core wouldn't be able to deal with those. If downgrading or upgrading your AMD drivers doesn't help, you could also try deleting Vircadias shader cache in %AppData%

**Comment by liberza** [comment]
I tried upgrading to the latest AMD driver, and I was able to load in to The Hub once and walk around. I switched between a few domains and then started having the same issue on The Hub again.

Then I tried downgrading to Radeon 20.9.1. Now I've been able to switch between 5 or 6 domains multiple times back and forth without any issues. Seems like this issue is not present on the older driver.

**Comment by JulianGro** [comment]
Are you still getting the warning?
```
[WARNING] [default] An OpenGL Core Profile was requested, but it is not supported on the current platform. Falling back to a non-Core profile. Note that this might cause rendering issues.
```
According to HifiExperiments, it might not actually be an issue.

**Comment by liberza** [comment]
> Are you still getting the warning?
Yes, I just confirmed that even when I load in successfully this warning occurs.

**Comment by liberza** [comment]
I just confirmed that 20.11.1 also works, while the subsequent driver [20.11.2](https://www.amd.com/en/support/kb/release-notes/rn-rad-win-20-11-2) does not, so it appears that release is where this issue was introduced. 20.11.2 was the driver I originally was running when I encountered this issue, with the specs that I referenced in my 3rd comment in this thread.

**Comment by liberza** [comment]
Just want to mention that I'm now set up to build from git, and can test a potential fix if that's useful. I'll continue to poke around but don't really know what I'm looking at :)

**Comment by JulianGro** [comment]
You could enable "Send crashes" at the bottom of the General settings. I think you might need to restart Vircadia for that to take affect, but that should send a crash report to sentry whenever you crash which might contain more information.

**Comment by JulianGro** [comment]
The driver version this is a problem is in is quite old now. The issue doesn't happen on my end on 20.10.35.02 27.20.1034.6 and 21.4.1 27.20.21002.112
