### ISSUE TITLE
Allowing The abilitie to use blend shapes on soft attachments

### ISSUE THREAD

**Issue by Novajone** [vircadia/vircadia#993]
So far i know this only works on  just fbx models them self but not on soft attachments and this will be a good thing for allowing more customization to clothing

**Comment by HifiExperiments** [comment]
do you have a script or test steps that show the problem?  I haven’t touched soft attachments much but I don’t know what would explicitly be stopping this from working

**Comment by HifiExperiments** [comment]
I've confirmed that this should work.  here's a simple example:

- make a "soft attachment", which is just an avatar entity with relayParentJoints set to true.  this makes a copy of your avatar that follows you:
```
var id = Entities.addEntity({
          type: "Model",
          modelURL:MyAvatar.skeletonModelURL,
          position: Vec3.sum(MyAvatar.position, {x: 1, y: 0, z: 0}),
          parentID: "{00000000-0000-0000-0000-000000000001}",
          relayParentJoints: true
     }, "avatar");
```
- edit it as you would a normal model entity:
```
Entities.editEntity(id, { blendshapeCoefficients: JSON.stringify({ "JawOpen": 1.0 }) });
```
- viola!  the soft attachment's mouth will open
