### ISSUE TITLE
Low latency & efficient voice mixing with a Mumble backend?

### ISSUE THREAD

**Issue by poVoq** [vircadia/vircadia#995]
Another suggestion on utilizing existing and highly performant systems: [Mumble](https://wiki.mumble.info/) is a voice chat program with [build in positional audio](https://wiki.mumble.info/wiki/Positional-Audio) widely used for gaming. The main client is written in qt and there is an [easy to use C++ interface](https://github.com/mumble-voip/mumble-plugin-cpp).

It is known for being extremely resource and bandwidth efficient, while maintaining a good audio quality. It is also completely open-source with lightweight server implementations. There are also clients (& libraries) on nearly all major platforms including webbrowsers or Android.

Maybe worth considering as an alternative given that you had to change to a less efficient audio system after the switch to a fully open-surce code-base.

**Comment by daleglass** [comment]
I'd rather just improve our code instead, which is likely easier than grafting Mumble onto it. 

We use most of the same tech anyway, and the difficulty is mainly that Opus encoding is done server-side and must be done per client due to positional audio -- everyone is getting their own particular mix.

There are known parts that can be tuned, this is on my list to look into soon-ish.

**Comment by poVoq** [comment]
Fair enough. One benefit of running in separately would be to distribute the load more easily on different servers though.

**Comment by JulianGro** [comment]
Our audio mixer is already a separate component which can run on a different machine, so I am not sure how Mumble would be better at distributing load.

There is still a lot that can be done for performance on the audio mixer. The main thing seems to be the audio encoding, so a different codec setting, a different codec, or maybe even a smart codec selection depending on server load and/or client preference would be able to help significantly with that. Obviously Mumble is as limited in encoder choices as we are, so I don't see any improvement there.
Also performance is not necessarily worse than before. Opus with our current settings uses more CPU while using less bandwidth. In a data center that might be worse, but for home servers that is likely preferable.

**Comment by daleglass** [comment]
Closing, we already have audio codec work being planned.
